class MessageDef {

	public static postUseItemSuccess = "postUseItemSuccess"
	public static postInitActorInfo = "postInitActorInfo"

	public static LUCK_RECORD = "LUCK_RECORD"
	public static LUCK_RET_ANIM = "LUCK_RET_ANIM"
	public static LUCK_RET_SUC = "LUCK_RET_SUC"
	
	public static MAIN_CITY_INFO = "MAIN_CITY_INFO"
	public static CHANNEL_UPDATE_INFO = "CHANNEL_UPDATE_INFO"
	public static CHANNEL_UPDATE_LIST = "CHANNEL_UPDATE_LIST"

	//战斗相关
	public static BATTLE_TURN = "BATTLE_TURN"
	public static BATTLE_TURN_START = "BATTLE_TURN_START"

	public static RP_FORGE = "RP_FORGE"
	public static FORGE_UPDATE = "FORGE_UPDATE"
	public static FORGE_ITEM_01_UPDATE = "FORGE_ITEM_01_UPDATE"
	public static FORGE_ITEM_02_UPDATE = "FORGE_ITEM_02_UPDATE"
	public static FORGE_ITEM_03_UPDATE = "FORGE_ITEM_03_UPDATE"

	// 坐骑
	public static ROLE_RIDE_INIT = "ROLE_RIDE_INIT"
	public static ROLE_RIDE_UPDATE = "ROLE_RIDE_UPDATE"
	public static ROLE_RIDE_UPDATE_EXP = "ROLE_RIDE_UPDATE_EXP"
	public static ROLE_RIDE_UPDATE_EQUIP = "ROLE_RIDE_UPDATE_EQUIP"
	public static ROLE_RIDE_UPDATE_DRUG = "ROLE_RIDE_UPDATE_DRUG"

	// 翅膀
	public static ROLE_WING_UPDATE = "ROLE_WING_UPDATE"
	public static ROLE_WING_UPDATE_EXP = "ROLE_WING_UPDATE_EXP"
	public static ROLE_WING_UPDATE_DRUG = "ROLE_WING_UPDATE_DRUG"
	public static ROLE_WING_INIT = "ROLE_WING_INIT"
	public static ROLE_WING_UPDATE_EQUIP = "ROLE_WING_UPDATE_EQUIP"


	//称号
	public static ROLE_TITLE_UPDATE = "ROLE_TITLE_UPDATE"

	//时装
	public static ROLE_SKIN_UPDATE = "ROLE_SKIN_UPDATE"

	//丹药
	public static ROLE_ELIXIR_UPDATE = "ROLE_ELIXIR_UPDATE"

	// 宠物通灵
	public static PET_TONGL_UPDATE_EXP = "PET_TONGL_UPDATE_EXP"
	public static PET_TONGL_UPDATE_DRUG = "PET_TONGL_UPDATE_DRUG"
	public static PET_TONGL_UPDATE = "PET_TONGL_UPDATE"
	public static PET_TONGL_INIT = "PET_TONGL_INIT"
	public static PET_TONGL_UPDATE_EQUIP = "PET_TONGL_UPDATE_EQUIP"
	public static RP_BAG_PET_TONGL_EQUIP_UP = "RP_BAG_PET_TONGL_EQUIP_UP"

	// 神剑
	public static ROLE_SWORD_UPDATE_EXP = "ROLE_SWORD_UPDATE_EXP"
	public static ROLE_SWORD_UPDATE_DRUG = "ROLE_SWORD_UPDATE_DRUG"
	public static ROLE_SWORD_UPDATE = "ROLE_SWORD_UPDATE"
	public static ROLE_SWORD_INIT = "ROLE_SWORD_INIT"
	public static ROLE_SWORD_UPDATE_EQUIP = "ROLE_SWORD_UPDATE_EQUIP"
	public static RP_BAG_SWORD_EQUIP_UP = "RP_BAG_SWORD_EQUIP_UP"

	// 宠物兽魂
	public static PET_SHOUH_UPDATE_EXP = "PET_SHOUH_UPDATE_EXP"
	public static PET_SHOUH_UPDATE_DRUG = "PET_SHOUH_UPDATE_DRUG"
	public static PET_SHOUH_UPDATE = "PET_SHOUH_UPDATE"
	public static PET_SHOUH_INIT = "PET_SHOUH_INIT"
	public static PET_SHOUH_UPDATE_EQUIP = "PET_SHOUH_UPDATE_EQUIP"
	public static RP_BAG_PET_SHOUH_EQUIP_UP = "RP_BAG_PET_SHOUH_EQUIP_UP"

	// 玄女
	public static HAVING_UPDATE_EXP = "HAVING_UPDATE_EXP"
	public static HAVING_UPDATE_DRUG = "HAVING_UPDATE_DRUG"
	public static HAVING_UPDATE = "HAVING_UPDATE"
	public static HAVING_INIT = "HAVING_INIT"
	public static HAVING_SKILL_ITEM_UPDATE = "HAVING_SKILL_ITEM_UPDATE"

	// 玄女花辇
	public static HAVING_HUAN_UPDATE_EXP = "HAVING_HUAN_UPDATE_EXP"
	public static HAVING_HUAN_UPDATE_DRUG = "HAVING_HUAN_UPDATE_DRUG"
	public static HAVING_HUAN_UPDATE = "HAVING_HUAN_UPDATE"
	public static HAVING_HUAN_INIT = "HAVING_HUAN_INIT"
	public static HAVING_HUAN_UPDATE_EQUIP = "HAVING_HUAN_UPDATE_EQUIP"
	public static RP_BAG_HAVING_HUAN_EQUIP_UP = "RP_BAG_HAVING_HUAN_EQUIP_UP"

	// 玄女灵气
	public static HAVING_LINGQ_UPDATE_EXP = "HAVING_LINGQ_UPDATE_EXP"
	public static HAVING_LINGQ_UPDATE_DRUG = "HAVING_LINGQ_UPDATE_DRUG"
	public static HAVING_LINGQ_UPDATE = "HAVING_LINGQ_UPDATE"
	public static HAVING_LINGQ_INIT = "HAVING_LINGQ_INIT"
	public static HAVING_LINGQ_UPDATE_EQUIP = "HAVING_LINGQ_UPDATE_EQUIP"
	public static RP_BAG_HAVING_LINGQ_EQUIP_UP = "RP_BAG_HAVING_LINGQ_EQUIP_UP"

	// 守护
	public static ROLE_TIANX_UPDATE_EXP = "ROLE_TIANX_UPDATE_EXP"
	public static ROLE_TIANX_UPDATE_DRUG = "ROLE_TIANX_UPDATE_DRUG"
	public static ROLE_TIANX_UPDATE = "ROLE_TIANX_UPDATE"
	public static ROLE_TIANX_INIT = "ROLE_TIANX_INIT"
	public static ROLE_TIANX_UPDATE_EQUIP = "ROLE_TIANX_UPDATE_EQUIP"
	public static RP_BAG_TIANX_EQUIP_UP = "RP_BAG_TIANX_EQUIP_UP"

	// 仙侣法阵
	public static XIANLV_FZ_UPDATE_EXP = "XIANLV_FZ_UPDATE_EXP"
	public static XIANLV_FZ_UPDATE_DRUG = "XIANLV_FZ_UPDATE_DRUG"
	public static XIANLV_FZ_UPDATE = "XIANLV_FZ_UPDATE"
	public static XIANLV_FZ_INIT = "XIANLV_FZ_INIT"
	public static XIANLV_FZ_UPDATE_EQUIP = "XIANLV_FZ_UPDATE_EQUIP"
	public static RP_BAG_XIANLV_FZ_EQUIP_UP = "RP_BAG_XIANLV_FZ_EQUIP_UP"

	// 仙侣仙位
	public static XIANLV_XW_UPDATE_EXP = "XIANLV_XW_UPDATE_EXP"
	public static XIANLV_XW_UPDATE_DRUG = "XIANLV_XW_UPDATE_DRUG"
	public static XIANLV_XW_UPDATE = "XIANLV_XW_UPDATE"
	public static XIANLV_XW_INIT = "XIANLV_XW_INIT"
	public static XIANLV_XW_UPDATE_EQUIP = "XIANLV_XW_UPDATE_EQUIP"
	public static RP_BAG_XIANLV_XW_EQUIP_UP = "RP_BAG_XIANLV_XW_EQUIP_UP"

	// 灵童
	public static ROLE_LINGTONG_UPDATE_EXP = "ROLE_LINGTONG_UPDATE_EXP"
	public static ROLE_LINGTONG_UPDATE_DRUG = "ROLE_LINGTONG_UPDATE_DRUG"
	public static ROLE_LINGTONG_UPDATE = "ROLE_LINGTONG_UPDATE"
	public static ROLE_LINGTONG_INIT = "ROLE_LINGTONG_INIT"
	public static ROLE_LINGTONG_UPDATE_EQUIP = "ROLE_LINGTONG_UPDATE_EQUIP"
	public static RP_BAG_LINGTONG_EQUIP_UP = "RP_BAG_LINGTONG_EQUIP_UP"

	public static LINGTONG_UPDATE_INFO = "LINGTONG_UPDATE_INFO"
	public static LINGTONG_UPDATE_GIFT_INFO = "LINGTONG_UPDATE_GIFT_INFO"
	public static RP_LINGTONG = "RP_LINGTONG"
	public static LINGTONG_ACT_ITEM = "LINGTONG_ACT_ITEM"
	public static LINGTONG_RANK_ITEM = "LINGTONG_RANK_ITEM"
	public static LINGTONG_SKILL_ITEM = "LINGTONG_SKILL_ITEM"

	public static SEND_MSG_INFO_SUCCESS = "SEND_MSG_INFO_SUCCESS"

	public static readonly GAME_SERVER_UPDATE_DAY = "GAME_SERVER_UPDATE_DAY"
	public static readonly GAME_DEBLOCKING = "GAME_DEBLOCKING"

	public static SHOP_REFRESH = "SHOP_REFRESH"
	public static MINI_CHAT_PANEL_STATE = "MINI_CHAT_PANEL_STATE"
	public static YB_TURNTABLE_UPDATE = "YB_TURNTABLE_UPDATE"

	public static RAID_KILL_MONSTER_COUNT = "RAID_KILL_MONSTER_COUNT"
	public static FIND_ASSETS_UPDATE = "FIND_ASSETS_UPDATE"

	public static ACTOR_PRESTIGE_UPDATE = "ACTOR_PRESTIGE_UPDATE"

	public static LEVEL_CHANGE = "LEVEL_CHANGE"
	public static GOLD_CHANGE = "GOLD_CHANGE"

	public static SKILL_SORT_CHANGE = "SKILL_SORT_CHANGE" //技能顺序改变

	public static INIT_ACTOR = "INIT_ACTOR"
	public static YB_CHANGE = "YB_CHANGE"
	public static BYB_CHANGE = "BYB_CHANGE"
	public static EXP_CHANGE = "EXP_CHANGE"
	public static NAME_CHANGE = "NAME_CHANGE"
	public static POWER_CHANGE = "POWER_CHANGE"
	public static SOUL_CHANGE = "SOUL_CHANGE"
	public static POWER_BOOST = "POWER_BOOST"
	public static GUANQIA_CHANGE = "GUANQIA_CHANGE"
	public static FUNC_OPEN_UPDATE = "FUNC_OPEN_UPDATE"
	public static GUILD_CONTRIB_UPDATE = "GUILD_CONTRIB_UPDATE"//个人帮贡更新

	public static CHECK_HAVE_CAN = "CHECK_HAVE_CAN"

	public static VIP_LEVEL_CHANGE = "VIP_LEVEL_CHANGE"
	public static UPDATA_VIP_AWARDS = "UPDATA_VIP_AWARDS"
	public static UPDATA_VIP_EXP = "UPDATA_VIP_EXP"

	public static TITLE_SHOW = "TITLE_SHOW"

	public static SUB_ROLE_CHANGE = "SUB_ROLE_CHANGE"

	public static FUBEN_CHANGE = "FUBEN_CHANGE"
	// 切换到挑战副本
	public static CHALLENGE_FUBEN_CHANGE = "CHALLENGE_FUBEN_CHANGE"

	/**派发角色按钮提示 */
	public static ROLE_HINT = "ROLE_HINT"
	public static RP_ROLE_HINT = "RP_ROLE_HINT"
	/** 装备数量更新 */
	public static BAG_USER_EQUIP_COUNT_UPDATE = "BAG_USER_EQUIP_COUNT_UPDATE"
	/** 皮肤道具 */
	public static BAG_USER_SKIN_COUNT_UPDATE = "BAG_USER_SKIN_COUNT_UPDATE"
	public static BAG_USER_TITLE_COUNT_UPDATE = "BAG_USER_TITLE_COUNT_UPDATE"
	/** 橙装碎片 */
	public static BAG_USER_ORANGE_COUNT_UPDATE = "BAG_USER_ORANGE_COUNT_UPDATE"

	/** 副本数量更新 */
	public static FB_COUNT_UPDATE = "FB_COUNT_UPDATE"

	/*藏宝图*/
	public static FB_CBT_UPDATE = "FB_CBT_UPDATE"
	//藏宝图 奖励
	public static FB_CBT_UPDATE_REWARD = "FB_CBT_UPDATE_REWARD"

	//跨服boss
	public static ACROSS_BOSS = "ACROSS_BOSS"

	//世界地图
	public static WORLDMAP_LOCATETO = "WORLDMAP_LOCATETO"

	//地图类型变更
	public static MAP_TYPE_CHANGE = "MAP_TYPE_CHANGE"

	//天庭副本刷新
	public static FB_TIANTING_UPDATE = "FB_TIANTING_UPDATE"

	public static FB_REDPOINT_NOTICE = "FB_REDPOINT_NOTICE"
	/** 派发全民boss列表数据 */
	public static PUBLIC_BOSS_LIST_DATA = "PUBLIC_BOSS_LIST_DATA"
	public static PUBLIC_BOSS_RANK_UPDATE = "PUBLIC_BOSS_RANK_UPDATE"
	public static PUBLIC_BOSS_RECORD_UPDATE = "PUBLIC_BOSS_RECORD_UPDATE"
	public static PUBLIC_BOSS_RELIVE_UPDATE = "PUBLIC_BOSS_RELIVE_UPDATE"
	public static PUBLIC_BOSS_OWNER_CHNAGE = "PUBLIC_BOSS_OWNER_CHNAGE"
	/** 红包 */
	public static REDBAG_JM_DATA = "REDBAG_JM_DATA"
	public static ISHSAREDBAG = "ISHSAREDBAG"

	public static SKILL_UPGRADE = "SKILL_UPGRADE"
	/**派发技能一键升级消息 */
	public static SKILL_GREWUPALL = "SKILL_GREWUPALL"
	/* 技能一键红点提示 */
	public static RP_SKILL_UPGRADE = "RP_SKILL_UPGRADE"

	//商店购买变化
	public static SHOP_CHANGE = "SHOP_CHANGE"

	//法宝内容变化
	public static TREASURE_CHANGE = "TREASURE_CHANGE"
	public static TREASURE_UPDATE_LV = "TREASURE_UPDATE_LV"
	public static TREASURE_UPDATE_MAKE = "TREASURE_UPDATE_MAKE"
	public static TREASURE_LOCK = "TREASURE_LOCK"
	public static TREASURE_ITEM_CHANGE = "TREASURE_ITEM_CHANGE"
	public static RP_TREASURE = "RP_TREASURE"

	//灵童命格
	public static DESTINY_RP = "DESTINY_RP"
	public static DESTINY_UP_ITEM = "DESTINY_UP_ITEM"
	public static DESTINY_CHANGE = "DESTINY_CHANGE"
	public static DESTINY_SMELT = "DESTINY_SMELT"
	public static DESTINY_CLICK= "DESTINY_CLICK"
	public static DESTINY_GET_REWARD= "DESTINY_GET_REWARD"
	public static DESTINY_EQUIP_REWARD= "DESTINY_EQUIP_REWARD"
	
	

	//师徒数据变化
	public static TEACHER_CHANGE = "TEACHER_CHANGE"
	public static TEACHER_TURN = "TEACHER_TURN"


	//答题内容变化
	public static ANSWER_CHANGE = "ANSWER_CHANGE"
	//答题奖励弹窗界面数据
	public static ANSWER_REWARD = "ANSWER_REWARD"


	/**合成物品消息 */
	public static MIX_REUSLT = "MIX_REUSLT"

	//////////////////////////////////////////   背包   //////////////////////////////////////////////////////////////////////////////////////

	/** 派发删除道具 */
	public static DELETE_ITEM = "DELETE_ITEM"
	public static ADD_ITEM = "ADD_ITEM"
	public static CHANGE_ITEM = "CHANGE_ITEM"

	/********************* 组合字符串 *******************************/
	public static USER_TEMPLATE_RANK_UP_ = "USER_TEMPLATE_RANK_UP_"
	public static USER_TEMPLATE_RANK_REWARD_UPDATE_ = "USER_TEMPLATE_RANK_REWARD_UPDATE_"
	public static USER_TEMPLATE_RANK_REWARD_UPDATE_ALL___ = "USER_TEMPLATE_RANK_REWARD_UPDATE_ALL___"
	// 装备更新
	public static USER_TEMPLATE_EQUIP_UPDATE_ = "USER_TEMPLATE_EQUIP_UPDATE_"
	// 技能
	public static USER_TEMPLATE_SKILL_UPDATE_ = "USER_TEMPLATE_SKILL_UPDATE_"
	// 皮肤
	public static USER_TEMPLATE_SKIN_UPDATE_ = "USER_TEMPLATE_SKIN_UPDATE_"
	// 属性丹
	public static USER_TEMPLATE_ATTR_ITEM_UPDATE_ = "USER_TEMPLATE_ATTR_ITEM_UPDATE_"
	public static USER_TEMPLATE_UP_LEVEL_ITEM_UPDATE_ = "USER_TEMPLATE_UP_LEVEL_ITEM_UPDATE_"
	// 升阶丹
	public static USER_TEMPLATE_RANK_UPDATE_ = "USER_TEMPLATE_RANK_UPDATE_"
	// 装备更新红点
	public static RP_USER_TEMPLATE_EQUIP_UPDATE_ = "RP_USER_TEMPLATE_EQUIP_UPDATE_"

	// 其它红点
	public static RP_USER_TEMPLATE_UPDATE_ = "RP_USER_TEMPLATE_UPDATE_"

	/*************************************************************/

	/** 道具数量 */
	public static ITEM_COUNT_CHANGE = "ITEM_COUNT_CHANGE"
	public static ITEM_OTHER_COUNT_CHANGE = "ITEM_OTHER_COUNT_CHANGE"

	public static BAG_HUNT_STORE_CHANGE = "BAG_HUNT_STORE_CHANGE"
	public static BAG_VOL_ADD = "BAG_VOL_ADD"
	/** 背包格子数量变更 */
	public static BAG_ITEM_COUNT_CHANGE = "BAG_ITEM_COUNT_CHANGE"

	//熔炼成功消息
	public static BAG_DEAL_SMELT = "BAG_DEAL_SMELT"
	public static postEquipCheckList = "postEquipCheckList"




	/**派发背包数量快不足的提示*/
	public static BAG_WILL_FULL = "BAG_WILL_FULL"

	/**派发是否有可用道具提示*/
	public static BAG_HAS_ITEM_CAN_USE = "BAG_HAS_ITEM_CAN_USE"

	////////////////////////////////////////   商店 //////////////////////////////////////////////////////////////////////////////////////

	public static SHOP_MEADAL_RESULT = "SHOP_MEADAL_RESULT"
	public static SHOP_MEADAL_BUY_RESULT = "SHOP_MEADAL_BUY_RESULT"
	public static SHOP_MYSTERY_REFRESH = "SHOP_MYSTERY_REFRESH"

	////////////////////////////////////////   邮件 //////////////////////////////////////////////////////////////////////////////////////

	public static MAIL_DATA_CHANGE = "MAIL_DATA_CHANGE"
	public static OPEN_MAIL = "OPEN_MAIL"
	public static MAIL_GET_ITEM = "MAIL_GET_ITEM"

	/**派发装备改变 */
	public static CHANGE_EQUIP = "CHANGE_EQUIP"
	// public static CHANGE_GOD_EQUIP = "CHANGE_GOD_EQUIP"
	public static CHANGE_WING = "CHANGE_WING"

	public static DEITYEQUIP_ALL_NOTICE = "DEITYEQUIP_ALL_NOTICE"
	public static DEITYEQUIP_INIT = "DEITYEQUIP_INIT"

	public static EXPJADE_UPDATE = "EXPJADE_UPDATE"

	public static SHOW_OTHER_ACTOR = "SHOW_OTHER_ACTOR"
	public static SHOW_RANK_OTHER_ACTOR = "SHOW_RANK_OTHER_ACTOR"

	public static CHALLENGE_UPDATE_INFO = "CHALLENGE_UPDATE_INFO"

	/*橙装精炼*/
	public static ORANGE_EQUIP_UPDATE = "ORANGE_EQUIP_UPDATE"
	public static ORANGE_UPDATE_REFINE = "ORANGE_UPDATE_REFINE"
	/** 材料更新 */
	public static ORANGE_REFINE_UPDATE = "ORANGE_REFINE_UPDATE"

	public static GUILD_ROBBER_NOTICE = "GUILD_ROBBER_NOTICE"
	public static GUILD_UPDATE_NAME = "GUILD_UPDATE_NAME"

	public static GUILD_BOSS_CALL_INFO = "GUILD_BOSS_CALL_INFO"
	public static GUILD_BOSS_OPEN_INFO = "GUILD_BOSS_OPEN_INFO"
	public static GUILD_REWARD_WINNER_INFO = "GUILD_REWARD_WINNER_INFO"
	public static GUILD_REWARD_UPDATE_DISP_INFO = "GUILD_REWARD_UPDATE_DISP_INFO"


	public static RING_UPDATE_DATA = "RING_UPDATE_DATA"
	public static RING_INIT_DATA = "RING_INIT_DATA"
	public static RING_UPDATE_OPEN_DATA = "RING_UPDATE_OPEN_DATA"
	public static RING_UPDATE_TASK_DATA = "RING_UPDATE_TASK_DATA"

	public static RAID_RELIVE_TIME_GD_BOSS = "RAID_RELIVE_TIME_GD_BOSS"

	public static EGG_BROKEN_RESULT = "EGG_BROKEN_RESULT"

	public static LONG_HUN_ITEM_UPDATE = "LONG_HUN_ITEM_UPDATE"

	public static ELITE_BOSS_INIT_INFO = "ELITE_BOSS_INIT_INFO"
	public static ELITE_BOSS_ACTOR_INFO = "ELITE_BOSS_ACTOR_INFO"

	//天降馅饼  
	public static GOGPIE_UPDATE = "GOGPIE_UPDATE"

	public static CROSS_ACTIVITY_ALL_SERVER = "CROSS_ACTIVITY_ALL_SERVER"
	public static CROSS_ACTIVITY_UPDATE_DATA = "CROSS_ACTIVITY_UPDATE_DATA"
	public static CROSS_ACTIVITY_GROUP_BUY_UPDATE = "CROSS_ACTIVITY_GROUP_BUY_UPDATE"


	public static SHARE_FOCUSE_INFO = "SHARE_FOCUSE_INFO"

	//宠物
	public static PET_INIT_INFO = "PET_INIT_INFO"
	public static PET_UPATE_ZIZHI = "PET_UPATE_ZIZHI"
	public static PET_UPATE_INFO = "PET_UPATE_INFO"
	public static PET_ACTIVE = "PET_ACTIVE"
	public static PET_UPATE_EXP = "PET_UPATE_EXP"
	public static BZ_PET_INFO = "BZ_PET_INFO"
	
	// 宠物激活道具
	public static BAG_PET_ACT_ITEM = "BAG_PET_ACT_ITEM"
	public static RP_BAG_PET_ACT_ITEM = "RP_BAG_PET_ACT_ITEM"
	public static BAG_PET_LEVEL_ITEM = "BAG_PET_LEVEL_ITEM"
	public static BAG_PET_SKILL_ITEM = "BAG_PET_SKILL_ITEM"
	public static PET_BATTLE = "PET_BATTLE"
	public static RP_PET = "RP_PET"


	//仙侣
	public static XIANLV_ACTIVE = "XIANLV_ACTIVE"
	public static XIANLV_INIT_INFO = "XIANLV_INIT_INFO"
	public static XIANLV_UPATE_INFO = "XIANLV_UPATE_INFO"
	public static XIANLV_UPATE_BATTLE = "XIANLV_UPATE_BATTLE"
	public static XIANLV_UPATE_EXP = "XIANLV_UPATE_EXP"

	public static RP_XIANLV = "RP_XIANLV"
	public static BAG_XIANLV_ACT_ITEM = "BAG_XIANLV_ACT_ITEM"
	public static RP_BAG_XIANLV_ACT_ITEM = "RP_BAG_XIANLV_ACT_ITEM"
	public static BAG_XIANLV_RANK_ITEM = "BAG_XIANLV_RANK_ITEM"
	public static BAG_XIANLV_STAR_ITEM = "BAG_XIANLV_STAR_ITEM"

	public static WORLD_BOSS_UPDATE_BLOOD = "WORLD_BOSS_UPDATE_BLOOD"
	public static WORLD_BOSS_ATT_LIST = "WORLD_BOSS_ATT_LIST"
	public static WORLD_RANK_DATA = "WORLD_RANK_DATA"
	public static WORLD_OPEN = "WORLD_OPEN"

	//阵型
	public static FORMATION_ACTIVE = "FORMATION_ACTIVE"
	public static FORMATION_UPDATE_INFO = "FORMATION_UPDATE_INFO"
	public static FORMATION_UPDATE_EXP = "FORMATION_UPDATE_EXP"
	public static FORMATION_UPDATE_SOUL_EXP = "FORMATION_UPDATE_SOUL_EXP"
	public static FORMATION_USE_DRUG = "FORMATION_USE_DRUG"
	public static FORMATION_UPDATE_SKILL_INFO = "FORMATION_UPDATE_SKILL_INFO"
	public static FORMATION_ALL_NOTICE = "FORMATION_ALL_NOTICE"

	//取经东归
	public static QUJING_UPDATE_BASEINFO = "QUJING_UPDATE_BASEINFO"
	public static QUJING_SHOW_REWARD = "QUJING_SHOW_REWARD"
	public static QUJING_UPDATE_RECORD = "QUJING_UPDATE_RECORD"
	public static QUJING_UPDATE_ESCORTLIST = "QUJING_UPDATE_ESCORTLIST"
	public static QUJING_SHOW_ROBVIEW = "QUJING_SHOW_ROBVIEW"
	public static QUJING_ROBBEDFLAG_CHANGE = "QUJING_ROBBEDFLAG_CHANGE"

	//帮会
	public static GANG_INIT = "GANG_INIT"
	public static GANG_UPDATE_LIST = "GANG_UPDATE_LIST"
	public static GANG_UPDATE_APPLIED_LIST = "GANG_UPDATE_APPLIED_LIST"
	public static GANG_UPDATE_BASE_INFO = "GANG_UPDATE_BASE_INFO"
	public static GANG_UPDATE_APPLICANT_LIST = "GANG_UPDATE_APPLICANT_LIST"
	public static GANG_UPDATE_PANTAOINFO = "GANG_UPDATE_PANTAOINFO"

	public static GANG_CHANGE_NAME = "GANG_CHANGE_NAME"
	public static GANG_SKILL_UP = "GANG_SKILL_UP"
	public static GANG_SKILL_LEARN_UP = "GANG_SKILL_LEARN_UP"

	public static GANG_UPDATE_MEMBER_LIST = "GANG_UPDATE_MEMBER_LIST"
	public static GANG_UPDATE_MEMBER_INFO = "GANG_UPDATE_MEMBER_INFO"
	public static GANG_EXIT_NOTICE = "GANG_EXIT_NOTICE"
	public static GANG_UPDATA_RECORD = "GANG_UPDATA_RECORD"
	public static GANG_UPDATA_PROTECTOR_INFO = "GANG_UPDATA_PROTECTOR_INFO"
	public static GANG_UPDATA_PROTECTOR_TASK_INFO = "GANG_UPDATA_PROTECTOR_TASK_INFO"
	public static GANG_UPDATA_GANG_BOSS_INFO = "GANG_UPDATA_GANG_BOSS_INFO"
	public static GANGMAP_ONEKEYFINISH = "GANGMAP_ONEKEYFINISH"
	public static GANG_UPDATE_FBCOUNT = "GANG_UPDATE_FBCOUNT"
	public static GANG_UPDATE_CONTRIBUTECOUNT = "GANG_UPDATE_CONTRIBUTECOUNT"
	public static GANG_ID_CHANGE = "GANG_ID_CHANGE"

	public static GANG_ALL_NOTICE = "GANG_ALL_NOTICE"

	//帮会地图
	public static GANGMAP_MAPENTITY_INIT = "GANGMAP_MAPENTITY_INIT"
	public static GANGMAP_UPDATE_TASKINFO = "GANGMAP_UPDATE_TASKINFO"
	public static GANGMAP_UPDATE_EXCHANGEINFO = "GANGMAP_UPDATE_EXCHANGEINFO"
	public static GANGMAP_UPDATE_UPDATEENTITY = "GANGMAP_UPDATE_UPDATEENTITY"
	public static GANGMAP_START_PICKPLANT_NOTICY = "GANGMAP_START_PICKPLANT_NOTICY"
	public static GANGMAP_AUTO_TASK = "GANGMAP_AUTO_TASK"
	public static GANGMAP_RESET_MAPENTITY = "GANGMAP_RESET_MAPENTITY"
	public static GANGMAP_HIDEPICKPROGRESS = "GANGMAP_HIDEPICKPROGRESS"

	//帮会boss
	public static GANGBOSS_DEAD = "GANGBOSS_DEAD"
	public static GANGBOSS_RANK_NOW = "GANGBOSS_RANK_NOW"
	public static GANGBOSS_UPDATE_HP = "GANGBOSS_UPDATE_HP"
	public static GANGBOSS_BOX = "GANGBOSS_BOX"
	public static GANGBOSS_BOX_COLLENT = "GANGBOSS_BOX_COLLENT"
	public static GANGBOSS_UPDATE_INFO = "GANGBOSS_UPDATE_INFO"
	public static GANGBOSS_CHANGE = "GANGBOSS_CHANGE"

	//boss
	public static FIELD_BOSS_UPDATE = "FIELD_BOSS_UPDATE"
	public static PUBLIC_BOSS_UPDATE = "PUBLIC_BOSS_UPDATE"
	public static PERSON_BOSS_UPDATE = "PERSON_BOSS_UPDATE"
	public static PUBLIC_BOSS_RECORD = "PUBLIC_BOSS_RECORD"
	public static PUBLIC_BOSS_RECORD_KILL = "PUBLIC_BOSS_RECORD_KILL"
	public static VIP_BOSS_UPDATE = "VIP_BOSS_UPDATE"
	public static ALL_BOSS_NOTICE = "ALL_BOSS_NOTICE"
	public static PUBLIC_BOSS_REBORN = "PUBLIC_BOSS_REBORN"

	//帮会战
	public static GANGBATTLE_OPEN_GATEVIEW = "GANGBATTLE_OPEN_GATEVIEW"
	public static GANGBATTLE_UPDATE_BOSSINFO = "GANGBATTLE_UPDATE_BOSSINFO"
	public static GANGBATTLE_UPDATE_MYINFO = "GANGBATTLE_UPDATE_MYINFO"
	public static GANGBATTLE_ENTER_NEXT_GATE = "GANGBATTLE_ENTER_NEXT_GATE"
	public static GANGBATTLE_UPDATE_GANGRANK = "GANGBATTLE_UPDATE_GANGRANK"
	public static GANGBATTLE_UPDATE_PLAYERRANK = "GANGBATTLE_UPDATE_PLAYERRANK"
	public static GANGBATTLE_UPDATE_ALLGANGRANK = "GANGBATTLE_UPDATE_ALLGANGRANK"
	public static GANGBATTLE_UPDATE_ALLPLAYERRANK = "GANGBATTLE_UPDATE_ALLPLAYERRANK"
	public static GANGBATTLE_UPDATE_KINGINFO = "GANGBATTLE_UPDATE_KINGINFO"
	public static GANGBATTLE_UPDATE_DURATION = "GANGBATTLE_UPDATE_DURATION"
	public static GANGBATTLE_SHOW_GUARDTIP = "GANGBATTLE_SHOW_GUARDTIP"

	//缘份
	public static YUANFEN_UPDATE_LIST = "YUANFEN_UPDATE_LIST"
	public static YUANFEN_INIT = "YUANFEN_INIT"
	public static YUANFEN_ALL_NOTICE = "YUANFEN_ALL_NOTICE"

	//日常
	public static DAILY_PEACE_UPDATE = "DAILY_PEACE_UPDATE"
	public static DAILY_TEAM_UPDATE = "DAILY_TEAM_UPDATE"
	public static DAILY_ACTIVE_UPDATE = "DAILY_ACTIVE_UPDATE"
	public static DAILY_MEDAL_UPDATE = "DAILY_MEDAL_UPDATE"
	public static DAILY_TASKLIST_UPDATE = "DAILY_TASKLIST_UPDATE"
	public static DAILY_RETRIEVELIST_UPDATE = "DAILY_RETRIEVELIST_UPDATE"
	public static DAILY_REDPOINT_NOTICE = "DAILY_REDPOINT_NOTICE"
	public static DAILY_FOMALHAUT_MONSTERID = "DAILY_FOMALHAUT_MONSTERID"
	public static DAILY_UPDATE_RETREVE_VIEW = "DAILY_UPDATE_RETREVE_VIEW"

	//日常副本
	public static FB_INFO_UPDATE = "FB_INFO_UPDATE"
	//玲珑塔
	public static TA_INFO_UPDATE = "TA_INFO_UPDATE"

	//神兽活动
	public static GODPETACTIVE_UPDATE_INFO = "GODPETACTIVE_UPDATE_INFO"
	public static GODPETACTIVE_UPDATE_AWARDINFO = "GODPETACTIVE_UPDATE_AWARDINFO"
	public static GODPETACTIVE_UPDATE_LOTTERY = "GODPETACTIVE_UPDATE_LOTTERY"
	public static GODPETACTIVE_LOTTERY_NOTICE = "GODPETACTIVE_LOTTERY_NOTICE"

	//天神降临
	public static GODLOTTERY_UPDATE_INFO = "GODLOTTERY_UPDATE_INFO"
	public static GODLOTTERY_UPDATE_LOTTERY = "GODLOTTERY_UPDATE_LOTTERY"

	//竞技场
	public static ARENA_INFO_DATA = 'ARENA_INFO_DATA';
	public static ARENA_BUY_RESULT = 'ARENA_BUY_RESULT';
	public static ARENA_RANK_DATA = 'ARENA_RANK_DATA';

	//经脉
	public static JINGMAI_DATA_UPDATE = 'JINGMAI_DATA_UPDATE';

	//玄女法器
	public static HAVING_WASH_INFO = 'HAVING_WASH_INFO';
	public static HAVING_WASH_REPLACE_INFO = 'HAVING_WASH_REPLACE_INFO';

	//主线任务
	public static UPDATE_MAIN_TASK = 'UPDATE_MAIN_TASK'
	//聊天收缩
	public static UPDATE_CHAT_ZOOM = 'UPDATE_CHAT_ZOOM'

	// 天神
	public static TIANSHEN_ACTIVE = "TIANSHEN_ACTIVE"
	public static TIANSHEN_UPDATE_INFO = "TIANSHEN_UPDATE_INFO"
	public static TIANSHEN_BATTLE = "TIANSHEN_BATTLE"
	public static TIANSHEN_UPDATE_EXP = "TIANSHEN_UPDATE_EXP"
	public static TIANSHEN_UPDATE_DRUG = "TIANSHEN_UPDATE_DRUG"
	public static TIANSHEN_UPDATE_BREACH = "TIANSHEN_UPDATE_BREACH"
	public static TIANSHEN_BAOQI_UPDATE_INFO = "TIANSHEN_BAOQI_UPDATE_INFO"
	public static TIANSHEN_BAOQI_UPDATE_EXP = "TIANSHEN_BAOQI_UPDATE_EXP"

	public static BAG_TIANSHEN_ATTR_ITEM = "BAG_TIANSHEN_ATTR_ITEM"
	public static BAG_TIANSHEN_ACT_ITEM = "BAG_TIANSHEN_ACT_ITEM"
	public static BAG_TIANSHEN_LEVEL_ITEM = "BAG_TIANSHEN_LEVEL_ITEM"
	public static RP_BAG_TIANSHEN_ACT_ITEM = "RP_BAG_TIANSHEN_ACT_ITEM"
	public static RP_TIANSHEN = "RP_TIANSHEN"

	//玩家详情
	public static PALYER_INFO = 'PALYER_INFO'
	public static PLAYER_PREVITE_CHAT = 'PLAYER_PREVITE_CHAT'
	public static PLAYER_PREVITE_CLOSE = 'PLAYER_PREVITE_CLOSE'
	public static PLAYER_PREVITE_CHAT_SUCCESS = 'PLAYER_PREVITE_CHAT_SUCCESS'
	public static PLAYER_CHECK_ONLINE = 'PLAYER_CHECK_ONLINE'
	public static PLAYER_NEWMSG_SHOW_RED_POINT = 'PLAYER_NEWMSG_SHOW_RED_POINT'
	public static PLAYER_COPY_NAME = 'PLAYER_COPY_NAME'
	public static PLAYER_CHANGE_NAME = "PLAYER_CHANGE_NAME"
	public static PLAYER_CHANGE_SYSTEM_SETTING = "PLAYER_CHANGE_SYSTEM_SETTING"
	public static PLAYER_VIEW_ONCITYMAP = "PLAYER_VIEW_ONCITYMAP"

	//迷你聊天框(缩小)
	public static MINICHATSCAL = "MINICHATSCAL"
	public static MINICHATSCAL_ALL = "MINICHATSCAL_ALL"

	//排行榜
	public static UPDATE_PAIHANGBANG_DATA = 'UPDATE_PAIHANGBANG_DATA'
	public static PHB_REPOINT_UPDATE = 'PHB_REPOINT_UPDATE'

	//队伍
	public static UPDATE_TEAM_MYINFO = 'UPDATE_TEAM_MYINFO'
	public static UPDATE_TEAM_LIST = 'UPDATE_TEAM_LIST'
	public static TEAM_FUBEN_INFO = "TEAM_FUBEN_INFO"
	public static TEAM_UPDATE_LEAVE = "TEAM_UPDATE_LEAVE"
	public static TEAM_UPDATE_MAP_LIST = "TEAM_UPDATE_MAP_LIST"
	// 主界面显示队伍信息
	public static UPDATE_TEAM_MAIN_INFO = 'UPDATE_TEAM_MAIN_INFO'

	// 全民boss
	public static PUBLIC_BOSS_UPDATE_ATK = "PUBLIC_BOSS_UPDATE_ATK"

	// 活动大厅
	public static ACTIVITY_LIST_INFO = "ACTIVITY_LIST_INFO"
	public static ACTIVITY_OPEN_UPDATE = "ACTIVITY_OPEN_UPDATE"

	// 矿山争夺
	public static GANGMINE_UPDATE_INFO = "GANGMINE_UPDATE_INFO"
	public static GANGMINE_RANK_INFO = "GANGMINE_RANK_INFO"
	public static PAGE_BUTTON_UPDATE = "PAGE_BUTTON_UPDATE"

	// 仙道会
	public static RP_XIANDAO = "RP_XIANDAO"
	public static XIANDAO_UPDATE = "XIANDAO_UPDATE"
	public static XIANDAO_MAP_UPDATE = "XIANDAO_MAP_UPDATE"

	//跨服争霸
	public static MINI_MAP_UPDATE_LIST = "MINI_MAP_UPDATE_LIST"
	public static KFZB_ONECITY_INFO = "KFZB_ONECITY_INFO"
	public static KFZB_MAINJNFEN_INFO = "KFZB_MAINJNFEN_INFO"
	public static FUHUO_UPDATE_INFO = "FUHUO_UPDATE_INFO"
	public static JF_UPDATE_INFO = "JF_UPDATE_INFO"
	public static MOVE_UPDATE_INFO = "MOVE_UPDATE_INFO"
	public static CITYTYPE_UPDATE_INFO = "CITYTYPE_UPDATE_INFO"
	public static UP_GROUP_SHOW = "UP_GROUP_SHOW"
	public static SHOUCITY_UPDATE_INFO = "SHOUCITY_UPDATE_INFO"
	public static SEND_CITY = "SEND_CITY"

	//九重天
	public static CLOUD_NINE_RANK = "CLOUD_NINE_RANK"
	public static CLOUD_NINE_GIFT_REFRES = "CLOUD_NINE_GIFT_REFRES"
	public static CLOUD_NINE_SCENE_INIT = "CLOUD_NINE_SCENE_INIT"

	//八十一难
	public static TSUMKO_UPDATE_LIST = "TSUMKO_UPDATE_LIST"
	public static TSUMKO_RECORD = "TSUMKO_RECORD"
	public static TSUMKO_UPDATE_CHECKPOINTLIST = "TSUMKO_UPDATE_CHECKPOINTLIST"
	public static ClOSETSUMKOBASEBAGITEMPLANEL = "ClOSETSUMKOBASEBAGITEMPLANEL"
	public static TSUMKO_INFO = "TSUMKO_INFO"
	public static CHOICECHECKPOINT = "CHOICECHECKPOINT"

	// 跨服boss
	public static KF_BOSS_DEAD = "KF_BOSS_DEAD"
	public static KF_BOSS_RANK_NOW = "KF_BOSS_RANK_NOW"
	public static KF_BOSS_UPDATE_HP = "KF_BOSS_UPDATE_HP"
	public static KF_BOSS_BOX = "KF_BOSS_BOX"
	public static KF_BOSS_BOX_COLLENT = "KF_BOSS_BOX_COLLENT"
	public static KF_BOSS_UPDATE_INFO = "KF_BOSS_UPDATE_INFO"


	//好友
	public static FRIEND_DATA_REFRESH = "FRIEND_DATA_REFRESH"
	public static FRIEND_RED_POINT_CHANGE = "FRIEND_RED_POINT_CHANGE"

	//银两兑换
	public static EXCHANGE_COUNT = "EXCHANGE_COUNT"

	//婚姻
	public static YING_YUAN_HEAD = "YING_YUAN_HEAD"
	public static IS_MARRY_INFO = "IS_MARRY_INFO"
	public static QIU_MARRY_INFO = "QIU_MARRY_INFO"
	public static INVITATION_INFO = "INVITATION_INFO"
	public static FLOWER_INFO = "FLOWER_INFO"
	public static MARRY_LOVE_INFO = "MARRY_LOVE_INFO"

	//房屋
	public static HOUSE_UPDATE_INFO = "HOUSE_UPDATE_INFO"
	public static HOUSE_SHARED_NOTICE = "HOUSE_SHARED_NOTICE"
	public static HOUSE_UPDATE_SINGLE = "HOUSE_UPDATE_SINGLE"

	//福利
	public static FULI_GET_GIFT_SUCCEED = "FULI_GET_GIFT_SUCCEED"
	public static FULI_GET_REDEEMCODE = "FULI_GET_REDEEMCODE"
	public static FULI_GET_RECEIVEITEMSIGN = "FULI_GET_RECEIVEITEMSIGN"
	public static FULI_GET_RECEIVEBRIBERY = "FULI_GET_RECEIVEBRIBERY"
	public static FULI_GET_HAVEBRIBERY = "FULI_GET_HAVEBRIBERY"
	public static FULI_MONTH_WEEK_CHANGE = "FULI_MONTH_WEEK_CHANGE"
	public static FULI_GIVEGOLD_INFO = "FULI_GIVEGOLD_INFO"
	public static FULI_GOLDTREE_INFO = "FULI_GOLDTREE_INFO"
	public static RP_SIGN_UPDATE = "RP_SIGN_UPDATE"

	// 剧情
	public static PLOT_PLAY_END = "PLOT_PLAY_END"

	//充值
	public static RECHARGE_UPDATE = "RECHARGE_UPDATE"
	public static RECHARGE_FIRST_UPDATE = "RECHARGE_FIRST_UPDATE"
	public static RECHARGE_DAILY_UPDATE = "RECHARGE_DAILY_UPDATE"
	public static PLAYER_RECHARGE_UPDATE = "PLAYER_RECHARGE_UPDATE"
	/**运营 开服 活动 */
	public static ACTIVITY_JIJIE_CHANGE_TITILE = "ACTIVITY_JIJIE_CHANGE_TITILE"
	public static ACTIVITY_INFO = "ACTIVITY_INFO"
	public static ACTIVITY_UPDATE = "ACTIVITY_UPDATE"
	public static ACTIVITY_DABIAO_UPDATE = "ACTIVITY_DABIAO_UPDATE"
	public static ACTIVITY_IS_GET_AWARDS = "ACTIVITY_IS_GET_AWARDS"
	public static ACTIVITY_RACE_HISTORY = "ACTIVITY_RACE_HISTORY"
	public static ACTIVITY_ADVANCED_INFO = "ACTIVITY_ADVANCED_INFO"
	public static ACTIVITY_ADVANCED_RANK = "ACTIVITY_ADVANCED_RANK"
	public static ACTIVITY_TARGET_ShOP_LOOK = "ACTIVITY_TARGET_ShOP_LOOK"
	public static ACTIVITY_ADVANCED_ICON_SHOW = "ACTIVITY_ADVANCED_ICON_SHOW"
	public static ACTIVITY_ADVANCED_ZHUANG_PAN = "ACTIVITY_ADVANCED_ZHUANG_PAN"
	public static ACTIVITY_ADVANCED_ZHUANG_PAN_RULE = "ACTIVITY_ADVANCED_ZHUANG_PAN_RULE"

	//拍卖
	public static AUCTION_ITEM_PRICE_UPDATE = "AUCTION_ITEM_PRICE_UPDATE"
	public static AUCTION_LIST_UPDATE = "AUCTION_LIST_UPDATE"
	public static AUCTION_RECORD_UPDATE = "AUCTION_RECORD_UPDATE"
	public static AUCTION_REDPOINT_UPDATE = "AUCTION_REDPOINT_UPDATE"

	//预告
	public static SHOWFATEEFF="SHOWFATEEFF";
	
	//登陆活动
	public static LOGINDAYGIF = "LOGINDAYGIF"

	public static LADDER_PLAYER_BACK = "LADDER_PLAYER_BACK"
	public static LADDER_PRE_WEEK_REWARD = "LADDER_PRE_WEEK_REWARD"
	public static LADDER_UPWEEK_RANK_UPDATE = "LADDER_UPWEEK_RANK_UPDATE"
	public static LADDER_WINNER = "LADDER_WINNER"
	public static LADDER_CHANGE = "LADDER_CHANGE"

	//图腾
	public static TOTEMS_UPDATEACTIVATION="TOTEMS_UPDATEACTIVATION";
	public static TOTEMS_INFO="TOTEMS_INFO";
	public static TOTEMS_REDPOINT_NOTICE="TOTEMS_REDPOINT_NOTICE";

	//升級途径-我要变强
	public static UPLVWAY_ACQUIRE_ITEM="UPLVWAY_ACQUIRE_ITEM";
	public static UPLVWAY_CHANGE_SCORE="UPLVWAY_CHANGE_SCORE";
	public static UPLVWAY_REDPOINT_NOTICE="UPLVWAY_REDPOINT_NOTICE";

	// 摇钱树
	public static MONEY_INFO_CHANGE = "MONEY_INFO_CHANGE"
	public static MONEY_RECHARGE_GIFT_CHANGE = "MONEY_RECHARGE_GIFT_CHANGE"
	//阵位预告
	public static POSITION_AWARD_CHANGE = "POSITION_AWARD_CHANGE"
	public static POSITION_STATE_CHANGE = "POSITION_STATE_CHANGE"
}