// Generated by sprotodump. DO NOT EDIT!
var __reflect = (this && this.__reflect) || function (p, c, t) {
    p.__class__ = c, t ? t.push(c) : t = [c], p.__types__ = p.__types__ ? t.concat(p.__types__) : t;
};
var Sproto;
(function (Sproto) {
    var cs_activity_enter_request = (function () {
        function cs_activity_enter_request() {
        }
        return cs_activity_enter_request;
    }());
    Sproto.cs_activity_enter_request = cs_activity_enter_request;
    __reflect(cs_activity_enter_request.prototype, "Sproto.cs_activity_enter_request");
    function _decode_cs_activity_enter_request(d) {
        var o = new cs_activity_enter_request;
        var t = -1;
        while (-1 != (t = d.rt())) {
            switch (t) {
                case 0:
                    o.activity = d.ri();
                    break;
                default:
                    d.nod();
                    break;
            }
        }
        return o;
    }
    function _encode_cs_activity_enter_request(self, st) {
        var se = Sproto.SprotoCore.GetSerialize(st, 1);
        if (self.activity != undefined) {
            se.wi(self.activity, 0);
        }
        return Sproto.SprotoCore.CloseSerialize(se);
    }
    Sproto.ALL_DICT["cs_activity_enter_request"] = { en: _encode_cs_activity_enter_request, de: _decode_cs_activity_enter_request };
    var cs_activity_hall_request = (function () {
        function cs_activity_hall_request() {
        }
        return cs_activity_hall_request;
    }());
    Sproto.cs_activity_hall_request = cs_activity_hall_request;
    __reflect(cs_activity_hall_request.prototype, "Sproto.cs_activity_hall_request");
    function _decode_cs_activity_hall_request(d) {
        var o = new cs_activity_hall_request;
        var t = -1;
        while (-1 != (t = d.rt())) {
            switch (t) {
                default:
                    d.nod();
                    break;
            }
        }
        return o;
    }
    function _encode_cs_activity_hall_request(self, st) {
        var se = Sproto.SprotoCore.GetSerialize(st, 0);
        return Sproto.SprotoCore.CloseSerialize(se);
    }
    Sproto.ALL_DICT["cs_activity_hall_request"] = { en: _encode_cs_activity_hall_request, de: _decode_cs_activity_hall_request };
    var cs_activity_info_req_request = (function () {
        function cs_activity_info_req_request() {
        }
        return cs_activity_info_req_request;
    }());
    Sproto.cs_activity_info_req_request = cs_activity_info_req_request;
    __reflect(cs_activity_info_req_request.prototype, "Sproto.cs_activity_info_req_request");
    function _decode_cs_activity_info_req_request(d) {
        var o = new cs_activity_info_req_request;
        var t = -1;
        while (-1 != (t = d.rt())) {
            switch (t) {
                default:
                    d.nod();
                    break;
            }
        }
        return o;
    }
    function _encode_cs_activity_info_req_request(self, st) {
        var se = Sproto.SprotoCore.GetSerialize(st, 0);
        return Sproto.SprotoCore.CloseSerialize(se);
    }
    Sproto.ALL_DICT["cs_activity_info_req_request"] = { en: _encode_cs_activity_info_req_request, de: _decode_cs_activity_info_req_request };
})(Sproto || (Sproto = {}));
//# sourceMappingURL=activity_c2s.js.map