// Generated by sprotodump. DO NOT EDIT!
var __reflect = (this && this.__reflect) || function (p, c, t) {
    p.__class__ = c, t ? t.push(c) : t = [c], p.__types__ = p.__types__ ? t.concat(p.__types__) : t;
};
var Sproto;
(function (Sproto) {
    var sc_arena_pk_result_request = (function () {
        function sc_arena_pk_result_request() {
        }
        return sc_arena_pk_result_request;
    }());
    Sproto.sc_arena_pk_result_request = sc_arena_pk_result_request;
    __reflect(sc_arena_pk_result_request.prototype, "Sproto.sc_arena_pk_result_request");
    function _decode_sc_arena_pk_result_request(d) {
        var o = new sc_arena_pk_result_request;
        var t = -1;
        while (-1 != (t = d.rt())) {
            switch (t) {
                case 0:
                    o.result = d.ri();
                    break;
                case 1:
                    o.rewards = d.roa("reward_data");
                    break;
                case 2:
                    o.iskill = d.rb();
                    break;
                case 3:
                    o.maxrank = d.ri();
                    break;
                case 4:
                    o.lastmaxrank = d.ri();
                    break;
                case 5:
                    o.rank = d.ri();
                    break;
                case 6:
                    o.lastrank = d.ri();
                    break;
                default:
                    d.nod();
                    break;
            }
        }
        return o;
    }
    function _encode_sc_arena_pk_result_request(self, st) {
        var se = Sproto.SprotoCore.GetSerialize(st, 7);
        if (self.result != undefined) {
            se.wi(self.result, 0);
        }
        if (self.rewards != undefined) {
            se.woa("reward_data", self.rewards, 1);
        }
        if (self.iskill != undefined) {
            se.wb(self.iskill, 2);
        }
        if (self.maxrank != undefined) {
            se.wi(self.maxrank, 3);
        }
        if (self.lastmaxrank != undefined) {
            se.wi(self.lastmaxrank, 4);
        }
        if (self.rank != undefined) {
            se.wi(self.rank, 5);
        }
        if (self.lastrank != undefined) {
            se.wi(self.lastrank, 6);
        }
        return Sproto.SprotoCore.CloseSerialize(se);
    }
    Sproto.ALL_DICT["sc_arena_pk_result_request"] = { en: _encode_sc_arena_pk_result_request, de: _decode_sc_arena_pk_result_request };
})(Sproto || (Sproto = {}));
//# sourceMappingURL=arena_s2c.js.map