// Generated by sprotodump. DO NOT EDIT!
var __reflect = (this && this.__reflect) || function (p, c, t) {
    p.__class__ = c, t ? t.push(c) : t = [c], p.__types__ = p.__types__ ? t.concat(p.__types__) : t;
};
var Sproto;
(function (Sproto) {
    var sc_cashCow_info_request = (function () {
        function sc_cashCow_info_request() {
        }
        return sc_cashCow_info_request;
    }());
    Sproto.sc_cashCow_info_request = sc_cashCow_info_request;
    __reflect(sc_cashCow_info_request.prototype, "Sproto.sc_cashCow_info_request");
    function _decode_sc_cashCow_info_request(d) {
        var o = new sc_cashCow_info_request;
        var t = -1;
        while (-1 != (t = d.rt())) {
            switch (t) {
                case 0:
                    o.level = d.ri();
                    break;
                case 1:
                    o.exp = d.ri();
                    break;
                case 2:
                    o.odds = d.ri();
                    break;
                case 3:
                    o.shake = d.ri();
                    break;
                case 4:
                    o.drawBin = d.ria();
                    break;
                case 5:
                    o.amplitude = d.ri();
                    break;
                default:
                    d.nod();
                    break;
            }
        }
        return o;
    }
    function _encode_sc_cashCow_info_request(self, st) {
        var se = Sproto.SprotoCore.GetSerialize(st, 6);
        if (self.level != undefined) {
            se.wi(self.level, 0);
        }
        if (self.exp != undefined) {
            se.wi(self.exp, 1);
        }
        if (self.odds != undefined) {
            se.wi(self.odds, 2);
        }
        if (self.shake != undefined) {
            se.wi(self.shake, 3);
        }
        if (self.drawBin != undefined) {
            se.wia(self.drawBin, 4);
        }
        if (self.amplitude != undefined) {
            se.wi(self.amplitude, 5);
        }
        return Sproto.SprotoCore.CloseSerialize(se);
    }
    Sproto.ALL_DICT["sc_cashCow_info_request"] = { en: _encode_sc_cashCow_info_request, de: _decode_sc_cashCow_info_request };
})(Sproto || (Sproto = {}));
//# sourceMappingURL=cashCow_s2c.js.map