// Generated by sprotodump. DO NOT EDIT!
var __reflect = (this && this.__reflect) || function (p, c, t) {
    p.__class__ = c, t ? t.push(c) : t = [c], p.__types__ = p.__types__ ? t.concat(p.__types__) : t;
};
var Sproto;
(function (Sproto) {
    var cs_eightyOneHard_buy_request = (function () {
        function cs_eightyOneHard_buy_request() {
        }
        return cs_eightyOneHard_buy_request;
    }());
    Sproto.cs_eightyOneHard_buy_request = cs_eightyOneHard_buy_request;
    __reflect(cs_eightyOneHard_buy_request.prototype, "Sproto.cs_eightyOneHard_buy_request");
    function _decode_cs_eightyOneHard_buy_request(d) {
        var o = new cs_eightyOneHard_buy_request;
        var t = -1;
        while (-1 != (t = d.rt())) {
            switch (t) {
                case 0:
                    o.id = d.ri();
                    break;
                default:
                    d.nod();
                    break;
            }
        }
        return o;
    }
    function _encode_cs_eightyOneHard_buy_request(self, st) {
        var se = Sproto.SprotoCore.GetSerialize(st, 1);
        if (self.id != undefined) {
            se.wi(self.id, 0);
        }
        return Sproto.SprotoCore.CloseSerialize(se);
    }
    Sproto.ALL_DICT["cs_eightyOneHard_buy_request"] = { en: _encode_cs_eightyOneHard_buy_request, de: _decode_cs_eightyOneHard_buy_request };
    var cs_eightyOneHard_record_request = (function () {
        function cs_eightyOneHard_record_request() {
        }
        return cs_eightyOneHard_record_request;
    }());
    Sproto.cs_eightyOneHard_record_request = cs_eightyOneHard_record_request;
    __reflect(cs_eightyOneHard_record_request.prototype, "Sproto.cs_eightyOneHard_record_request");
    function _decode_cs_eightyOneHard_record_request(d) {
        var o = new cs_eightyOneHard_record_request;
        var t = -1;
        while (-1 != (t = d.rt())) {
            switch (t) {
                case 0:
                    o.id = d.ri();
                    break;
                default:
                    d.nod();
                    break;
            }
        }
        return o;
    }
    function _encode_cs_eightyOneHard_record_request(self, st) {
        var se = Sproto.SprotoCore.GetSerialize(st, 1);
        if (self.id != undefined) {
            se.wi(self.id, 0);
        }
        return Sproto.SprotoCore.CloseSerialize(se);
    }
    Sproto.ALL_DICT["cs_eightyOneHard_record_request"] = { en: _encode_cs_eightyOneHard_record_request, de: _decode_cs_eightyOneHard_record_request };
    var cs_eightyOneHard_record_response = (function () {
        function cs_eightyOneHard_record_response() {
        }
        return cs_eightyOneHard_record_response;
    }());
    Sproto.cs_eightyOneHard_record_response = cs_eightyOneHard_record_response;
    __reflect(cs_eightyOneHard_record_response.prototype, "Sproto.cs_eightyOneHard_record_response");
    function _decode_cs_eightyOneHard_record_response(d) {
        var o = new cs_eightyOneHard_record_response;
        var t = -1;
        while (-1 != (t = d.rt())) {
            switch (t) {
                case 0:
                    o.first = d.ro("eightyOneHard_clear_data");
                    break;
                case 1:
                    o.fast = d.ro("eightyOneHard_clear_data");
                    break;
                default:
                    d.nod();
                    break;
            }
        }
        return o;
    }
    function _encode_cs_eightyOneHard_record_response(self, st) {
        var se = Sproto.SprotoCore.GetSerialize(st, 2);
        if (self.first != undefined) {
            se.wo("eightyOneHard_clear_data", self.first, 0);
        }
        if (self.fast != undefined) {
            se.wo("eightyOneHard_clear_data", self.fast, 1);
        }
        return Sproto.SprotoCore.CloseSerialize(se);
    }
    Sproto.ALL_DICT["cs_eightyOneHard_record_response"] = { en: _encode_cs_eightyOneHard_record_response, de: _decode_cs_eightyOneHard_record_response };
    var cs_eightyOneHard_sweep_request = (function () {
        function cs_eightyOneHard_sweep_request() {
        }
        return cs_eightyOneHard_sweep_request;
    }());
    Sproto.cs_eightyOneHard_sweep_request = cs_eightyOneHard_sweep_request;
    __reflect(cs_eightyOneHard_sweep_request.prototype, "Sproto.cs_eightyOneHard_sweep_request");
    function _decode_cs_eightyOneHard_sweep_request(d) {
        var o = new cs_eightyOneHard_sweep_request;
        var t = -1;
        while (-1 != (t = d.rt())) {
            switch (t) {
                case 0:
                    o.id = d.ri();
                    break;
                default:
                    d.nod();
                    break;
            }
        }
        return o;
    }
    function _encode_cs_eightyOneHard_sweep_request(self, st) {
        var se = Sproto.SprotoCore.GetSerialize(st, 1);
        if (self.id != undefined) {
            se.wi(self.id, 0);
        }
        return Sproto.SprotoCore.CloseSerialize(se);
    }
    Sproto.ALL_DICT["cs_eightyOneHard_sweep_request"] = { en: _encode_cs_eightyOneHard_sweep_request, de: _decode_cs_eightyOneHard_sweep_request };
    var cs_eightyOneHard_sweep_all_request = (function () {
        function cs_eightyOneHard_sweep_all_request() {
        }
        return cs_eightyOneHard_sweep_all_request;
    }());
    Sproto.cs_eightyOneHard_sweep_all_request = cs_eightyOneHard_sweep_all_request;
    __reflect(cs_eightyOneHard_sweep_all_request.prototype, "Sproto.cs_eightyOneHard_sweep_all_request");
    function _decode_cs_eightyOneHard_sweep_all_request(d) {
        var o = new cs_eightyOneHard_sweep_all_request;
        var t = -1;
        while (-1 != (t = d.rt())) {
            switch (t) {
                default:
                    d.nod();
                    break;
            }
        }
        return o;
    }
    function _encode_cs_eightyOneHard_sweep_all_request(self, st) {
        var se = Sproto.SprotoCore.GetSerialize(st, 0);
        return Sproto.SprotoCore.CloseSerialize(se);
    }
    Sproto.ALL_DICT["cs_eightyOneHard_sweep_all_request"] = { en: _encode_cs_eightyOneHard_sweep_all_request, de: _decode_cs_eightyOneHard_sweep_all_request };
    var eightyOneHard_clear_data = (function () {
        function eightyOneHard_clear_data() {
        }
        return eightyOneHard_clear_data;
    }());
    Sproto.eightyOneHard_clear_data = eightyOneHard_clear_data;
    __reflect(eightyOneHard_clear_data.prototype, "Sproto.eightyOneHard_clear_data");
    function _decode_eightyOneHard_clear_data(d) {
        var o = new eightyOneHard_clear_data;
        var t = -1;
        while (-1 != (t = d.rt())) {
            switch (t) {
                case 0:
                    o.name1 = d.rs();
                    break;
                case 1:
                    o.name2 = d.rs();
                    break;
                case 2:
                    o.name3 = d.rs();
                    break;
                case 3:
                    o.round = d.ri();
                    break;
                case 4:
                    o.time = d.ri();
                    break;
                default:
                    d.nod();
                    break;
            }
        }
        return o;
    }
    function _encode_eightyOneHard_clear_data(self, st) {
        var se = Sproto.SprotoCore.GetSerialize(st, 5);
        if (self.name1 != undefined) {
            se.ws(self.name1, 0);
        }
        if (self.name2 != undefined) {
            se.ws(self.name2, 1);
        }
        if (self.name3 != undefined) {
            se.ws(self.name3, 2);
        }
        if (self.round != undefined) {
            se.wi(self.round, 3);
        }
        if (self.time != undefined) {
            se.wi(self.time, 4);
        }
        return Sproto.SprotoCore.CloseSerialize(se);
    }
    Sproto.ALL_DICT["eightyOneHard_clear_data"] = { en: _encode_eightyOneHard_clear_data, de: _decode_eightyOneHard_clear_data };
})(Sproto || (Sproto = {}));
//# sourceMappingURL=eightyOneHard_c2s.js.map