// Generated by sprotodump. DO NOT EDIT!
var __reflect = (this && this.__reflect) || function (p, c, t) {
    p.__class__ = c, t ? t.push(c) : t = [c], p.__types__ = p.__types__ ? t.concat(p.__types__) : t;
};
var Sproto;
(function (Sproto) {
    var eightyOneHard_data = (function () {
        function eightyOneHard_data() {
        }
        return eightyOneHard_data;
    }());
    Sproto.eightyOneHard_data = eightyOneHard_data;
    __reflect(eightyOneHard_data.prototype, "Sproto.eightyOneHard_data");
    function _decode_eightyOneHard_data(d) {
        var o = new eightyOneHard_data;
        var t = -1;
        while (-1 != (t = d.rt())) {
            switch (t) {
                case 0:
                    o.key1 = d.ri();
                    break;
                case 1:
                    o.key2 = d.ri();
                    break;
                default:
                    d.nod();
                    break;
            }
        }
        return o;
    }
    function _encode_eightyOneHard_data(self, st) {
        var se = Sproto.SprotoCore.GetSerialize(st, 2);
        if (self.key1 != undefined) {
            se.wi(self.key1, 0);
        }
        if (self.key2 != undefined) {
            se.wi(self.key2, 1);
        }
        return Sproto.SprotoCore.CloseSerialize(se);
    }
    Sproto.ALL_DICT["eightyOneHard_data"] = { en: _encode_eightyOneHard_data, de: _decode_eightyOneHard_data };
    var sc_fuben_eightyOneHard_info_request = (function () {
        function sc_fuben_eightyOneHard_info_request() {
        }
        return sc_fuben_eightyOneHard_info_request;
    }());
    Sproto.sc_fuben_eightyOneHard_info_request = sc_fuben_eightyOneHard_info_request;
    __reflect(sc_fuben_eightyOneHard_info_request.prototype, "Sproto.sc_fuben_eightyOneHard_info_request");
    function _decode_sc_fuben_eightyOneHard_info_request(d) {
        var o = new sc_fuben_eightyOneHard_info_request;
        var t = -1;
        while (-1 != (t = d.rt())) {
            switch (t) {
                case 0:
                    o.clear = d.ri();
                    break;
                case 1:
                    o.helpReward = d.ri();
                    break;
                case 2:
                    o.buy = d.roa("eightyOneHard_data");
                    break;
                case 3:
                    o.todayClearlist = d.roa("eightyOneHard_data");
                    break;
                default:
                    d.nod();
                    break;
            }
        }
        return o;
    }
    function _encode_sc_fuben_eightyOneHard_info_request(self, st) {
        var se = Sproto.SprotoCore.GetSerialize(st, 4);
        if (self.clear != undefined) {
            se.wi(self.clear, 0);
        }
        if (self.helpReward != undefined) {
            se.wi(self.helpReward, 1);
        }
        if (self.buy != undefined) {
            se.woa("eightyOneHard_data", self.buy, 2);
        }
        if (self.todayClearlist != undefined) {
            se.woa("eightyOneHard_data", self.todayClearlist, 3);
        }
        return Sproto.SprotoCore.CloseSerialize(se);
    }
    Sproto.ALL_DICT["sc_fuben_eightyOneHard_info_request"] = { en: _encode_sc_fuben_eightyOneHard_info_request, de: _decode_sc_fuben_eightyOneHard_info_request };
    var sc_fuben_eightyOneHard_info_update_request = (function () {
        function sc_fuben_eightyOneHard_info_update_request() {
        }
        return sc_fuben_eightyOneHard_info_update_request;
    }());
    Sproto.sc_fuben_eightyOneHard_info_update_request = sc_fuben_eightyOneHard_info_update_request;
    __reflect(sc_fuben_eightyOneHard_info_update_request.prototype, "Sproto.sc_fuben_eightyOneHard_info_update_request");
    function _decode_sc_fuben_eightyOneHard_info_update_request(d) {
        var o = new sc_fuben_eightyOneHard_info_update_request;
        var t = -1;
        while (-1 != (t = d.rt())) {
            switch (t) {
                case 0:
                    o.clear = d.ri();
                    break;
                case 1:
                    o.helpReward = d.ri();
                    break;
                case 2:
                    o.buy = d.roa("eightyOneHard_data");
                    break;
                case 3:
                    o.todayClearlist = d.roa("eightyOneHard_data");
                    break;
                default:
                    d.nod();
                    break;
            }
        }
        return o;
    }
    function _encode_sc_fuben_eightyOneHard_info_update_request(self, st) {
        var se = Sproto.SprotoCore.GetSerialize(st, 4);
        if (self.clear != undefined) {
            se.wi(self.clear, 0);
        }
        if (self.helpReward != undefined) {
            se.wi(self.helpReward, 1);
        }
        if (self.buy != undefined) {
            se.woa("eightyOneHard_data", self.buy, 2);
        }
        if (self.todayClearlist != undefined) {
            se.woa("eightyOneHard_data", self.todayClearlist, 3);
        }
        return Sproto.SprotoCore.CloseSerialize(se);
    }
    Sproto.ALL_DICT["sc_fuben_eightyOneHard_info_update_request"] = { en: _encode_sc_fuben_eightyOneHard_info_update_request, de: _decode_sc_fuben_eightyOneHard_info_update_request };
})(Sproto || (Sproto = {}));
//# sourceMappingURL=eightyOneHard_s2c.js.map