// Generated by sprotodump. DO NOT EDIT!
var __reflect = (this && this.__reflect) || function (p, c, t) {
    p.__class__ = c, t ? t.push(c) : t = [c], p.__types__ = p.__types__ ? t.concat(p.__types__) : t;
};
var Sproto;
(function (Sproto) {
    var cs_guildmine_enter_request = (function () {
        function cs_guildmine_enter_request() {
        }
        return cs_guildmine_enter_request;
    }());
    Sproto.cs_guildmine_enter_request = cs_guildmine_enter_request;
    __reflect(cs_guildmine_enter_request.prototype, "Sproto.cs_guildmine_enter_request");
    function _decode_cs_guildmine_enter_request(d) {
        var o = new cs_guildmine_enter_request;
        var t = -1;
        while (-1 != (t = d.rt())) {
            switch (t) {
                default:
                    d.nod();
                    break;
            }
        }
        return o;
    }
    function _encode_cs_guildmine_enter_request(self, st) {
        var se = Sproto.SprotoCore.GetSerialize(st, 0);
        return Sproto.SprotoCore.CloseSerialize(se);
    }
    Sproto.ALL_DICT["cs_guildmine_enter_request"] = { en: _encode_cs_guildmine_enter_request, de: _decode_cs_guildmine_enter_request };
    var cs_guildmine_force_join_request = (function () {
        function cs_guildmine_force_join_request() {
        }
        return cs_guildmine_force_join_request;
    }());
    Sproto.cs_guildmine_force_join_request = cs_guildmine_force_join_request;
    __reflect(cs_guildmine_force_join_request.prototype, "Sproto.cs_guildmine_force_join_request");
    function _decode_cs_guildmine_force_join_request(d) {
        var o = new cs_guildmine_force_join_request;
        var t = -1;
        while (-1 != (t = d.rt())) {
            switch (t) {
                case 0:
                    o.mineId = d.ri();
                    break;
                default:
                    d.nod();
                    break;
            }
        }
        return o;
    }
    function _encode_cs_guildmine_force_join_request(self, st) {
        var se = Sproto.SprotoCore.GetSerialize(st, 1);
        if (self.mineId != undefined) {
            se.wi(self.mineId, 0);
        }
        return Sproto.SprotoCore.CloseSerialize(se);
    }
    Sproto.ALL_DICT["cs_guildmine_force_join_request"] = { en: _encode_cs_guildmine_force_join_request, de: _decode_cs_guildmine_force_join_request };
    var cs_guildmine_force_join_response = (function () {
        function cs_guildmine_force_join_response() {
        }
        return cs_guildmine_force_join_response;
    }());
    Sproto.cs_guildmine_force_join_response = cs_guildmine_force_join_response;
    __reflect(cs_guildmine_force_join_response.prototype, "Sproto.cs_guildmine_force_join_response");
    function _decode_cs_guildmine_force_join_response(d) {
        var o = new cs_guildmine_force_join_response;
        var t = -1;
        while (-1 != (t = d.rt())) {
            switch (t) {
                case 0:
                    o.ret = d.rb();
                    break;
                default:
                    d.nod();
                    break;
            }
        }
        return o;
    }
    function _encode_cs_guildmine_force_join_response(self, st) {
        var se = Sproto.SprotoCore.GetSerialize(st, 1);
        if (self.ret != undefined) {
            se.wb(self.ret, 0);
        }
        return Sproto.SprotoCore.CloseSerialize(se);
    }
    Sproto.ALL_DICT["cs_guildmine_force_join_response"] = { en: _encode_cs_guildmine_force_join_response, de: _decode_cs_guildmine_force_join_response };
    var cs_guildmine_gather_request = (function () {
        function cs_guildmine_gather_request() {
        }
        return cs_guildmine_gather_request;
    }());
    Sproto.cs_guildmine_gather_request = cs_guildmine_gather_request;
    __reflect(cs_guildmine_gather_request.prototype, "Sproto.cs_guildmine_gather_request");
    function _decode_cs_guildmine_gather_request(d) {
        var o = new cs_guildmine_gather_request;
        var t = -1;
        while (-1 != (t = d.rt())) {
            switch (t) {
                default:
                    d.nod();
                    break;
            }
        }
        return o;
    }
    function _encode_cs_guildmine_gather_request(self, st) {
        var se = Sproto.SprotoCore.GetSerialize(st, 0);
        return Sproto.SprotoCore.CloseSerialize(se);
    }
    Sproto.ALL_DICT["cs_guildmine_gather_request"] = { en: _encode_cs_guildmine_gather_request, de: _decode_cs_guildmine_gather_request };
    var cs_guildmine_gather_response = (function () {
        function cs_guildmine_gather_response() {
        }
        return cs_guildmine_gather_response;
    }());
    Sproto.cs_guildmine_gather_response = cs_guildmine_gather_response;
    __reflect(cs_guildmine_gather_response.prototype, "Sproto.cs_guildmine_gather_response");
    function _decode_cs_guildmine_gather_response(d) {
        var o = new cs_guildmine_gather_response;
        var t = -1;
        while (-1 != (t = d.rt())) {
            switch (t) {
                case 0:
                    o.ret = d.rb();
                    break;
                default:
                    d.nod();
                    break;
            }
        }
        return o;
    }
    function _encode_cs_guildmine_gather_response(self, st) {
        var se = Sproto.SprotoCore.GetSerialize(st, 1);
        if (self.ret != undefined) {
            se.wb(self.ret, 0);
        }
        return Sproto.SprotoCore.CloseSerialize(se);
    }
    Sproto.ALL_DICT["cs_guildmine_gather_response"] = { en: _encode_cs_guildmine_gather_response, de: _decode_cs_guildmine_gather_response };
    var cs_guildmine_join_mine_request = (function () {
        function cs_guildmine_join_mine_request() {
        }
        return cs_guildmine_join_mine_request;
    }());
    Sproto.cs_guildmine_join_mine_request = cs_guildmine_join_mine_request;
    __reflect(cs_guildmine_join_mine_request.prototype, "Sproto.cs_guildmine_join_mine_request");
    function _decode_cs_guildmine_join_mine_request(d) {
        var o = new cs_guildmine_join_mine_request;
        var t = -1;
        while (-1 != (t = d.rt())) {
            switch (t) {
                case 0:
                    o.mineId = d.ri();
                    break;
                default:
                    d.nod();
                    break;
            }
        }
        return o;
    }
    function _encode_cs_guildmine_join_mine_request(self, st) {
        var se = Sproto.SprotoCore.GetSerialize(st, 1);
        if (self.mineId != undefined) {
            se.wi(self.mineId, 0);
        }
        return Sproto.SprotoCore.CloseSerialize(se);
    }
    Sproto.ALL_DICT["cs_guildmine_join_mine_request"] = { en: _encode_cs_guildmine_join_mine_request, de: _decode_cs_guildmine_join_mine_request };
    var cs_guildmine_join_mine_response = (function () {
        function cs_guildmine_join_mine_response() {
        }
        return cs_guildmine_join_mine_response;
    }());
    Sproto.cs_guildmine_join_mine_response = cs_guildmine_join_mine_response;
    __reflect(cs_guildmine_join_mine_response.prototype, "Sproto.cs_guildmine_join_mine_response");
    function _decode_cs_guildmine_join_mine_response(d) {
        var o = new cs_guildmine_join_mine_response;
        var t = -1;
        while (-1 != (t = d.rt())) {
            switch (t) {
                case 0:
                    o.ret = d.rb();
                    break;
                default:
                    d.nod();
                    break;
            }
        }
        return o;
    }
    function _encode_cs_guildmine_join_mine_response(self, st) {
        var se = Sproto.SprotoCore.GetSerialize(st, 1);
        if (self.ret != undefined) {
            se.wb(self.ret, 0);
        }
        return Sproto.SprotoCore.CloseSerialize(se);
    }
    Sproto.ALL_DICT["cs_guildmine_join_mine_response"] = { en: _encode_cs_guildmine_join_mine_response, de: _decode_cs_guildmine_join_mine_response };
    var cs_guildmine_leave_mine_request = (function () {
        function cs_guildmine_leave_mine_request() {
        }
        return cs_guildmine_leave_mine_request;
    }());
    Sproto.cs_guildmine_leave_mine_request = cs_guildmine_leave_mine_request;
    __reflect(cs_guildmine_leave_mine_request.prototype, "Sproto.cs_guildmine_leave_mine_request");
    function _decode_cs_guildmine_leave_mine_request(d) {
        var o = new cs_guildmine_leave_mine_request;
        var t = -1;
        while (-1 != (t = d.rt())) {
            switch (t) {
                default:
                    d.nod();
                    break;
            }
        }
        return o;
    }
    function _encode_cs_guildmine_leave_mine_request(self, st) {
        var se = Sproto.SprotoCore.GetSerialize(st, 0);
        return Sproto.SprotoCore.CloseSerialize(se);
    }
    Sproto.ALL_DICT["cs_guildmine_leave_mine_request"] = { en: _encode_cs_guildmine_leave_mine_request, de: _decode_cs_guildmine_leave_mine_request };
    var cs_guildmine_mine_info_request = (function () {
        function cs_guildmine_mine_info_request() {
        }
        return cs_guildmine_mine_info_request;
    }());
    Sproto.cs_guildmine_mine_info_request = cs_guildmine_mine_info_request;
    __reflect(cs_guildmine_mine_info_request.prototype, "Sproto.cs_guildmine_mine_info_request");
    function _decode_cs_guildmine_mine_info_request(d) {
        var o = new cs_guildmine_mine_info_request;
        var t = -1;
        while (-1 != (t = d.rt())) {
            switch (t) {
                case 0:
                    o.mineId = d.ri();
                    break;
                default:
                    d.nod();
                    break;
            }
        }
        return o;
    }
    function _encode_cs_guildmine_mine_info_request(self, st) {
        var se = Sproto.SprotoCore.GetSerialize(st, 1);
        if (self.mineId != undefined) {
            se.wi(self.mineId, 0);
        }
        return Sproto.SprotoCore.CloseSerialize(se);
    }
    Sproto.ALL_DICT["cs_guildmine_mine_info_request"] = { en: _encode_cs_guildmine_mine_info_request, de: _decode_cs_guildmine_mine_info_request };
    var cs_guildmine_score_rank_request = (function () {
        function cs_guildmine_score_rank_request() {
        }
        return cs_guildmine_score_rank_request;
    }());
    Sproto.cs_guildmine_score_rank_request = cs_guildmine_score_rank_request;
    __reflect(cs_guildmine_score_rank_request.prototype, "Sproto.cs_guildmine_score_rank_request");
    function _decode_cs_guildmine_score_rank_request(d) {
        var o = new cs_guildmine_score_rank_request;
        var t = -1;
        while (-1 != (t = d.rt())) {
            switch (t) {
                case 0:
                    o.rankType = d.ri();
                    break;
                default:
                    d.nod();
                    break;
            }
        }
        return o;
    }
    function _encode_cs_guildmine_score_rank_request(self, st) {
        var se = Sproto.SprotoCore.GetSerialize(st, 1);
        if (self.rankType != undefined) {
            se.wi(self.rankType, 0);
        }
        return Sproto.SprotoCore.CloseSerialize(se);
    }
    Sproto.ALL_DICT["cs_guildmine_score_rank_request"] = { en: _encode_cs_guildmine_score_rank_request, de: _decode_cs_guildmine_score_rank_request };
})(Sproto || (Sproto = {}));
//# sourceMappingURL=guildmine_c2s.js.map