// Generated by sprotodump. DO NOT EDIT!
var __reflect = (this && this.__reflect) || function (p, c, t) {
    p.__class__ = c, t ? t.push(c) : t = [c], p.__types__ = p.__types__ ? t.concat(p.__types__) : t;
};
var Sproto;
(function (Sproto) {
    var sc_money_recharge_gift_info_request = (function () {
        function sc_money_recharge_gift_info_request() {
        }
        return sc_money_recharge_gift_info_request;
    }());
    Sproto.sc_money_recharge_gift_info_request = sc_money_recharge_gift_info_request;
    __reflect(sc_money_recharge_gift_info_request.prototype, "Sproto.sc_money_recharge_gift_info_request");
    function _decode_sc_money_recharge_gift_info_request(d) {
        var o = new sc_money_recharge_gift_info_request;
        var t = -1;
        while (-1 != (t = d.rt())) {
            switch (t) {
                case 0:
                    o.day = d.ri();
                    break;
                case 1:
                    o.awards = d.ria();
                    break;
                default:
                    d.nod();
                    break;
            }
        }
        return o;
    }
    function _encode_sc_money_recharge_gift_info_request(self, st) {
        var se = Sproto.SprotoCore.GetSerialize(st, 2);
        if (self.day != undefined) {
            se.wi(self.day, 0);
        }
        if (self.awards != undefined) {
            se.wia(self.awards, 1);
        }
        return Sproto.SprotoCore.CloseSerialize(se);
    }
    Sproto.ALL_DICT["sc_money_recharge_gift_info_request"] = { en: _encode_sc_money_recharge_gift_info_request, de: _decode_sc_money_recharge_gift_info_request };
    var sc_money_tree_info_request = (function () {
        function sc_money_tree_info_request() {
        }
        return sc_money_tree_info_request;
    }());
    Sproto.sc_money_tree_info_request = sc_money_tree_info_request;
    __reflect(sc_money_tree_info_request.prototype, "Sproto.sc_money_tree_info_request");
    function _decode_sc_money_tree_info_request(d) {
        var o = new sc_money_tree_info_request;
        var t = -1;
        while (-1 != (t = d.rt())) {
            switch (t) {
                case 0:
                    o.playNum = d.ri();
                    break;
                case 1:
                    o.boxOn = d.ri();
                    break;
                case 2:
                    o.addCoefficient = d.ri();
                    break;
                case 3:
                    o.exp = d.ri();
                    break;
                case 4:
                    o.boxInfo = d.ri();
                    break;
                default:
                    d.nod();
                    break;
            }
        }
        return o;
    }
    function _encode_sc_money_tree_info_request(self, st) {
        var se = Sproto.SprotoCore.GetSerialize(st, 5);
        if (self.playNum != undefined) {
            se.wi(self.playNum, 0);
        }
        if (self.boxOn != undefined) {
            se.wi(self.boxOn, 1);
        }
        if (self.addCoefficient != undefined) {
            se.wi(self.addCoefficient, 2);
        }
        if (self.exp != undefined) {
            se.wi(self.exp, 3);
        }
        if (self.boxInfo != undefined) {
            se.wi(self.boxInfo, 4);
        }
        return Sproto.SprotoCore.CloseSerialize(se);
    }
    Sproto.ALL_DICT["sc_money_tree_info_request"] = { en: _encode_sc_money_tree_info_request, de: _decode_sc_money_tree_info_request };
    var sc_money_tree_play_info_request = (function () {
        function sc_money_tree_play_info_request() {
        }
        return sc_money_tree_play_info_request;
    }());
    Sproto.sc_money_tree_play_info_request = sc_money_tree_play_info_request;
    __reflect(sc_money_tree_play_info_request.prototype, "Sproto.sc_money_tree_play_info_request");
    function _decode_sc_money_tree_play_info_request(d) {
        var o = new sc_money_tree_play_info_request;
        var t = -1;
        while (-1 != (t = d.rt())) {
            switch (t) {
                case 0:
                    o.playNum = d.ri();
                    break;
                case 1:
                    o.boxOn = d.ri();
                    break;
                case 2:
                    o.addCoefficient = d.ri();
                    break;
                case 3:
                    o.exp = d.ri();
                    break;
                case 4:
                    o.baoji = d.ri();
                    break;
                default:
                    d.nod();
                    break;
            }
        }
        return o;
    }
    function _encode_sc_money_tree_play_info_request(self, st) {
        var se = Sproto.SprotoCore.GetSerialize(st, 5);
        if (self.playNum != undefined) {
            se.wi(self.playNum, 0);
        }
        if (self.boxOn != undefined) {
            se.wi(self.boxOn, 1);
        }
        if (self.addCoefficient != undefined) {
            se.wi(self.addCoefficient, 2);
        }
        if (self.exp != undefined) {
            se.wi(self.exp, 3);
        }
        if (self.baoji != undefined) {
            se.wi(self.baoji, 4);
        }
        return Sproto.SprotoCore.CloseSerialize(se);
    }
    Sproto.ALL_DICT["sc_money_tree_play_info_request"] = { en: _encode_sc_money_tree_play_info_request, de: _decode_sc_money_tree_play_info_request };
    var sc_money_tree_reward_info_request = (function () {
        function sc_money_tree_reward_info_request() {
        }
        return sc_money_tree_reward_info_request;
    }());
    Sproto.sc_money_tree_reward_info_request = sc_money_tree_reward_info_request;
    __reflect(sc_money_tree_reward_info_request.prototype, "Sproto.sc_money_tree_reward_info_request");
    function _decode_sc_money_tree_reward_info_request(d) {
        var o = new sc_money_tree_reward_info_request;
        var t = -1;
        while (-1 != (t = d.rt())) {
            switch (t) {
                case 0:
                    o.boxInfo = d.ri();
                    break;
                default:
                    d.nod();
                    break;
            }
        }
        return o;
    }
    function _encode_sc_money_tree_reward_info_request(self, st) {
        var se = Sproto.SprotoCore.GetSerialize(st, 1);
        if (self.boxInfo != undefined) {
            se.wi(self.boxInfo, 0);
        }
        return Sproto.SprotoCore.CloseSerialize(se);
    }
    Sproto.ALL_DICT["sc_money_tree_reward_info_request"] = { en: _encode_sc_money_tree_reward_info_request, de: _decode_sc_money_tree_reward_info_request };
    var sc_qdday_reward_info_request = (function () {
        function sc_qdday_reward_info_request() {
        }
        return sc_qdday_reward_info_request;
    }());
    Sproto.sc_qdday_reward_info_request = sc_qdday_reward_info_request;
    __reflect(sc_qdday_reward_info_request.prototype, "Sproto.sc_qdday_reward_info_request");
    function _decode_sc_qdday_reward_info_request(d) {
        var o = new sc_qdday_reward_info_request;
        var t = -1;
        while (-1 != (t = d.rt())) {
            switch (t) {
                case 0:
                    o.qdday = d.ri();
                    break;
                case 1:
                    o.bqday = d.ri();
                    break;
                case 2:
                    o.drawBin = d.ri();
                    break;
                case 3:
                    o.isqd = d.ri();
                    break;
                default:
                    d.nod();
                    break;
            }
        }
        return o;
    }
    function _encode_sc_qdday_reward_info_request(self, st) {
        var se = Sproto.SprotoCore.GetSerialize(st, 4);
        if (self.qdday != undefined) {
            se.wi(self.qdday, 0);
        }
        if (self.bqday != undefined) {
            se.wi(self.bqday, 1);
        }
        if (self.drawBin != undefined) {
            se.wi(self.drawBin, 2);
        }
        if (self.isqd != undefined) {
            se.wi(self.isqd, 3);
        }
        return Sproto.SprotoCore.CloseSerialize(se);
    }
    Sproto.ALL_DICT["sc_qdday_reward_info_request"] = { en: _encode_sc_qdday_reward_info_request, de: _decode_sc_qdday_reward_info_request };
})(Sproto || (Sproto = {}));
//# sourceMappingURL=money_tree_s2c.js.map