// Generated by sprotodump. DO NOT EDIT!
var __reflect = (this && this.__reflect) || function (p, c, t) {
    p.__class__ = c, t ? t.push(c) : t = [c], p.__types__ = p.__types__ ? t.concat(p.__types__) : t;
};
var Sproto;
(function (Sproto) {
    var cs_money_recharge_get_request = (function () {
        function cs_money_recharge_get_request() {
        }
        return cs_money_recharge_get_request;
    }());
    Sproto.cs_money_recharge_get_request = cs_money_recharge_get_request;
    __reflect(cs_money_recharge_get_request.prototype, "Sproto.cs_money_recharge_get_request");
    function _decode_cs_money_recharge_get_request(d) {
        var o = new cs_money_recharge_get_request;
        var t = -1;
        while (-1 != (t = d.rt())) {
            switch (t) {
                case 0:
                    o.day = d.ri();
                    break;
                default:
                    d.nod();
                    break;
            }
        }
        return o;
    }
    function _encode_cs_money_recharge_get_request(self, st) {
        var se = Sproto.SprotoCore.GetSerialize(st, 1);
        if (self.day != undefined) {
            se.wi(self.day, 0);
        }
        return Sproto.SprotoCore.CloseSerialize(se);
    }
    Sproto.ALL_DICT["cs_money_recharge_get_request"] = { en: _encode_cs_money_recharge_get_request, de: _decode_cs_money_recharge_get_request };
    var cs_money_tree_reward_request = (function () {
        function cs_money_tree_reward_request() {
        }
        return cs_money_tree_reward_request;
    }());
    Sproto.cs_money_tree_reward_request = cs_money_tree_reward_request;
    __reflect(cs_money_tree_reward_request.prototype, "Sproto.cs_money_tree_reward_request");
    function _decode_cs_money_tree_reward_request(d) {
        var o = new cs_money_tree_reward_request;
        var t = -1;
        while (-1 != (t = d.rt())) {
            switch (t) {
                case 0:
                    o.id = d.ri();
                    break;
                default:
                    d.nod();
                    break;
            }
        }
        return o;
    }
    function _encode_cs_money_tree_reward_request(self, st) {
        var se = Sproto.SprotoCore.GetSerialize(st, 1);
        if (self.id != undefined) {
            se.wi(self.id, 0);
        }
        return Sproto.SprotoCore.CloseSerialize(se);
    }
    Sproto.ALL_DICT["cs_money_tree_reward_request"] = { en: _encode_cs_money_tree_reward_request, de: _decode_cs_money_tree_reward_request };
    var cs_qd_get_reward_request = (function () {
        function cs_qd_get_reward_request() {
        }
        return cs_qd_get_reward_request;
    }());
    Sproto.cs_qd_get_reward_request = cs_qd_get_reward_request;
    __reflect(cs_qd_get_reward_request.prototype, "Sproto.cs_qd_get_reward_request");
    function _decode_cs_qd_get_reward_request(d) {
        var o = new cs_qd_get_reward_request;
        var t = -1;
        while (-1 != (t = d.rt())) {
            switch (t) {
                case 0:
                    o.index = d.ri();
                    break;
                default:
                    d.nod();
                    break;
            }
        }
        return o;
    }
    function _encode_cs_qd_get_reward_request(self, st) {
        var se = Sproto.SprotoCore.GetSerialize(st, 1);
        if (self.index != undefined) {
            se.wi(self.index, 0);
        }
        return Sproto.SprotoCore.CloseSerialize(se);
    }
    Sproto.ALL_DICT["cs_qd_get_reward_request"] = { en: _encode_cs_qd_get_reward_request, de: _decode_cs_qd_get_reward_request };
    var cs_qd_recharge_get_request = (function () {
        function cs_qd_recharge_get_request() {
        }
        return cs_qd_recharge_get_request;
    }());
    Sproto.cs_qd_recharge_get_request = cs_qd_recharge_get_request;
    __reflect(cs_qd_recharge_get_request.prototype, "Sproto.cs_qd_recharge_get_request");
    function _decode_cs_qd_recharge_get_request(d) {
        var o = new cs_qd_recharge_get_request;
        var t = -1;
        while (-1 != (t = d.rt())) {
            switch (t) {
                case 0:
                    o.day = d.ri();
                    break;
                default:
                    d.nod();
                    break;
            }
        }
        return o;
    }
    function _encode_cs_qd_recharge_get_request(self, st) {
        var se = Sproto.SprotoCore.GetSerialize(st, 1);
        if (self.day != undefined) {
            se.wi(self.day, 0);
        }
        return Sproto.SprotoCore.CloseSerialize(se);
    }
    Sproto.ALL_DICT["cs_qd_recharge_get_request"] = { en: _encode_cs_qd_recharge_get_request, de: _decode_cs_qd_recharge_get_request };
})(Sproto || (Sproto = {}));
//# sourceMappingURL=money_tree_c2s.js.map