// Generated by sprotodump. DO NOT EDIT!
var __reflect = (this && this.__reflect) || function (p, c, t) {
    p.__class__ = c, t ? t.push(c) : t = [c], p.__types__ = p.__types__ ? t.concat(p.__types__) : t;
};
var Sproto;
(function (Sproto) {
    var cs_rechargew_getawards_request = (function () {
        function cs_rechargew_getawards_request() {
        }
        return cs_rechargew_getawards_request;
    }());
    Sproto.cs_rechargew_getawards_request = cs_rechargew_getawards_request;
    __reflect(cs_rechargew_getawards_request.prototype, "Sproto.cs_rechargew_getawards_request");
    function _decode_cs_rechargew_getawards_request(d) {
        var o = new cs_rechargew_getawards_request;
        var t = -1;
        while (-1 != (t = d.rt())) {
            switch (t) {
                case 0:
                    o.payType = d.ri();
                    break;
                case 1:
                    o.gid = d.ri();
                    break;
                case 2:
                    o.index = d.ri();
                    break;
                default:
                    d.nod();
                    break;
            }
        }
        return o;
    }
    function _encode_cs_rechargew_getawards_request(self, st) {
        var se = Sproto.SprotoCore.GetSerialize(st, 3);
        if (self.payType != undefined) {
            se.wi(self.payType, 0);
        }
        if (self.gid != undefined) {
            se.wi(self.gid, 1);
        }
        if (self.index != undefined) {
            se.wi(self.index, 2);
        }
        return Sproto.SprotoCore.CloseSerialize(se);
    }
    Sproto.ALL_DICT["cs_rechargew_getawards_request"] = { en: _encode_cs_rechargew_getawards_request, de: _decode_cs_rechargew_getawards_request };
    var cs_rechargew_setpop_request = (function () {
        function cs_rechargew_setpop_request() {
        }
        return cs_rechargew_setpop_request;
    }());
    Sproto.cs_rechargew_setpop_request = cs_rechargew_setpop_request;
    __reflect(cs_rechargew_setpop_request.prototype, "Sproto.cs_rechargew_setpop_request");
    function _decode_cs_rechargew_setpop_request(d) {
        var o = new cs_rechargew_setpop_request;
        var t = -1;
        while (-1 != (t = d.rt())) {
            switch (t) {
                case 0:
                    o.payType = d.ri();
                    break;
                case 1:
                    o.gid = d.ri();
                    break;
                case 2:
                    o.nopop = d.rb();
                    break;
                default:
                    d.nod();
                    break;
            }
        }
        return o;
    }
    function _encode_cs_rechargew_setpop_request(self, st) {
        var se = Sproto.SprotoCore.GetSerialize(st, 3);
        if (self.payType != undefined) {
            se.wi(self.payType, 0);
        }
        if (self.gid != undefined) {
            se.wi(self.gid, 1);
        }
        if (self.nopop != undefined) {
            se.wb(self.nopop, 2);
        }
        return Sproto.SprotoCore.CloseSerialize(se);
    }
    Sproto.ALL_DICT["cs_rechargew_setpop_request"] = { en: _encode_cs_rechargew_setpop_request, de: _decode_cs_rechargew_setpop_request };
})(Sproto || (Sproto = {}));
//# sourceMappingURL=rechargew_c2s.js.map