// Generated by sprotodump. DO NOT EDIT!
var __reflect = (this && this.__reflect) || function (p, c, t) {
    p.__class__ = c, t ? t.push(c) : t = [c], p.__types__ = p.__types__ ? t.concat(p.__types__) : t;
};
var Sproto;
(function (Sproto) {
    var cs_task_info_request = (function () {
        function cs_task_info_request() {
        }
        return cs_task_info_request;
    }());
    Sproto.cs_task_info_request = cs_task_info_request;
    __reflect(cs_task_info_request.prototype, "Sproto.cs_task_info_request");
    function _decode_cs_task_info_request(d) {
        var o = new cs_task_info_request;
        var t = -1;
        while (-1 != (t = d.rt())) {
            switch (t) {
                case 0:
                    o.type = d.ri();
                    break;
                default:
                    d.nod();
                    break;
            }
        }
        return o;
    }
    function _encode_cs_task_info_request(self, st) {
        var se = Sproto.SprotoCore.GetSerialize(st, 1);
        if (self.type != undefined) {
            se.wi(self.type, 0);
        }
        return Sproto.SprotoCore.CloseSerialize(se);
    }
    Sproto.ALL_DICT["cs_task_info_request"] = { en: _encode_cs_task_info_request, de: _decode_cs_task_info_request };
    var cs_task_reward_request = (function () {
        function cs_task_reward_request() {
        }
        return cs_task_reward_request;
    }());
    Sproto.cs_task_reward_request = cs_task_reward_request;
    __reflect(cs_task_reward_request.prototype, "Sproto.cs_task_reward_request");
    function _decode_cs_task_reward_request(d) {
        var o = new cs_task_reward_request;
        var t = -1;
        while (-1 != (t = d.rt())) {
            switch (t) {
                case 0:
                    o.id = d.ri();
                    break;
                default:
                    d.nod();
                    break;
            }
        }
        return o;
    }
    function _encode_cs_task_reward_request(self, st) {
        var se = Sproto.SprotoCore.GetSerialize(st, 1);
        if (self.id != undefined) {
            se.wi(self.id, 0);
        }
        return Sproto.SprotoCore.CloseSerialize(se);
    }
    Sproto.ALL_DICT["cs_task_reward_request"] = { en: _encode_cs_task_reward_request, de: _decode_cs_task_reward_request };
})(Sproto || (Sproto = {}));
//# sourceMappingURL=task_c2s.js.map