// Generated by sprotodump. DO NOT EDIT!
var __reflect = (this && this.__reflect) || function (p, c, t) {
    p.__class__ = c, t ? t.push(c) : t = [c], p.__types__ = p.__types__ ? t.concat(p.__types__) : t;
};
var Sproto;
(function (Sproto) {
    var sc_vein_update_request = (function () {
        function sc_vein_update_request() {
        }
        return sc_vein_update_request;
    }());
    Sproto.sc_vein_update_request = sc_vein_update_request;
    __reflect(sc_vein_update_request.prototype, "Sproto.sc_vein_update_request");
    function _decode_sc_vein_update_request(d) {
        var o = new sc_vein_update_request;
        var t = -1;
        while (-1 != (t = d.rt())) {
            switch (t) {
                case 0:
                    o.totalattr = d.roa("attribute_data");
                    break;
                case 1:
                    o.level = d.ri();
                    break;
                default:
                    d.nod();
                    break;
            }
        }
        return o;
    }
    function _encode_sc_vein_update_request(self, st) {
        var se = Sproto.SprotoCore.GetSerialize(st, 2);
        if (self.totalattr != undefined) {
            se.woa("attribute_data", self.totalattr, 0);
        }
        if (self.level != undefined) {
            se.wi(self.level, 1);
        }
        return Sproto.SprotoCore.CloseSerialize(se);
    }
    Sproto.ALL_DICT["sc_vein_update_request"] = { en: _encode_sc_vein_update_request, de: _decode_sc_vein_update_request };
})(Sproto || (Sproto = {}));
//# sourceMappingURL=vein_s2c.js.map