// Generated by sprotodump. DO NOT EDIT!
var __reflect = (this && this.__reflect) || function (p, c, t) {
    p.__class__ = c, t ? t.push(c) : t = [c], p.__types__ = p.__types__ ? t.concat(p.__types__) : t;
};
var Sproto;
(function (Sproto) {
    var sc_xianlv_init_request = (function () {
        function sc_xianlv_init_request() {
        }
        return sc_xianlv_init_request;
    }());
    Sproto.sc_xianlv_init_request = sc_xianlv_init_request;
    __reflect(sc_xianlv_init_request.prototype, "Sproto.sc_xianlv_init_request");
    function _decode_sc_xianlv_init_request(d) {
        var o = new sc_xianlv_init_request;
        var t = -1;
        while (-1 != (t = d.rt())) {
            switch (t) {
                case 0:
                    o.list = d.roa("xianlv_info");
                    break;
                case 1:
                    o.outbound = d.ria();
                    break;
                default:
                    d.nod();
                    break;
            }
        }
        return o;
    }
    function _encode_sc_xianlv_init_request(self, st) {
        var se = Sproto.SprotoCore.GetSerialize(st, 2);
        if (self.list != undefined) {
            se.woa("xianlv_info", self.list, 0);
        }
        if (self.outbound != undefined) {
            se.wia(self.outbound, 1);
        }
        return Sproto.SprotoCore.CloseSerialize(se);
    }
    Sproto.ALL_DICT["sc_xianlv_init_request"] = { en: _encode_sc_xianlv_init_request, de: _decode_sc_xianlv_init_request };
    var xianlv_info = (function () {
        function xianlv_info() {
        }
        return xianlv_info;
    }());
    Sproto.xianlv_info = xianlv_info;
    __reflect(xianlv_info.prototype, "Sproto.xianlv_info");
    function _decode_xianlv_info(d) {
        var o = new xianlv_info;
        var t = -1;
        while (-1 != (t = d.rt())) {
            switch (t) {
                case 0:
                    o.id = d.ri();
                    break;
                case 1:
                    o.exp = d.ri();
                    break;
                case 2:
                    o.level = d.ri();
                    break;
                case 3:
                    o.star = d.ri();
                    break;
                default:
                    d.nod();
                    break;
            }
        }
        return o;
    }
    function _encode_xianlv_info(self, st) {
        var se = Sproto.SprotoCore.GetSerialize(st, 4);
        if (self.id != undefined) {
            se.wi(self.id, 0);
        }
        if (self.exp != undefined) {
            se.wi(self.exp, 1);
        }
        if (self.level != undefined) {
            se.wi(self.level, 2);
        }
        if (self.star != undefined) {
            se.wi(self.star, 3);
        }
        return Sproto.SprotoCore.CloseSerialize(se);
    }
    Sproto.ALL_DICT["xianlv_info"] = { en: _encode_xianlv_info, de: _decode_xianlv_info };
})(Sproto || (Sproto = {}));
//# sourceMappingURL=xianlv_s2c.js.map