// Generated by sprotodump. DO NOT EDIT!

namespace Sproto { 
	export class cs_activity_enter_request {
		public activity: number; // tag 0
	}

	function _decode_cs_activity_enter_request(d: SprotoTypeDeserialize) {
		let o = new cs_activity_enter_request;
		let t = -1;
		while (-1 != (t = d.rt())) {
			switch (t) {
			case 0:
				o.activity = d.ri ();
				break;
			default:
				d.nod ();
				break;
			}
		}
		return o
	}

	function _encode_cs_activity_enter_request(self: cs_activity_enter_request, st: Sproto.SprotoStream) {
		let se = SprotoCore.GetSerialize(st, 1);

		if (self.activity != undefined) {
			se.wi (self.activity, 0);
		}

		return SprotoCore.CloseSerialize(se);
	}

	ALL_DICT["cs_activity_enter_request"] = {en: _encode_cs_activity_enter_request, de: _decode_cs_activity_enter_request}
	export class cs_activity_hall_request {
	}

	function _decode_cs_activity_hall_request(d: SprotoTypeDeserialize) {
		let o = new cs_activity_hall_request;
		let t = -1;
		while (-1 != (t = d.rt())) {
			switch (t) {
			default:
				d.nod ();
				break;
			}
		}
		return o
	}

	function _encode_cs_activity_hall_request(self: cs_activity_hall_request, st: Sproto.SprotoStream) {
		let se = SprotoCore.GetSerialize(st, 0);

		return SprotoCore.CloseSerialize(se);
	}

	ALL_DICT["cs_activity_hall_request"] = {en: _encode_cs_activity_hall_request, de: _decode_cs_activity_hall_request}
	export class cs_activity_info_req_request {
	}

	function _decode_cs_activity_info_req_request(d: SprotoTypeDeserialize) {
		let o = new cs_activity_info_req_request;
		let t = -1;
		while (-1 != (t = d.rt())) {
			switch (t) {
			default:
				d.nod ();
				break;
			}
		}
		return o
	}

	function _encode_cs_activity_info_req_request(self: cs_activity_info_req_request, st: Sproto.SprotoStream) {
		let se = SprotoCore.GetSerialize(st, 0);

		return SprotoCore.CloseSerialize(se);
	}

	ALL_DICT["cs_activity_info_req_request"] = {en: _encode_cs_activity_info_req_request, de: _decode_cs_activity_info_req_request}
}

