// Generated by sprotodump. DO NOT EDIT!

namespace Sproto { 
	export class cs_cashCow_box_rewards_request {
		public boxid: number; // tag 0
	}

	function _decode_cs_cashCow_box_rewards_request(d: SprotoTypeDeserialize) {
		let o = new cs_cashCow_box_rewards_request;
		let t = -1;
		while (-1 != (t = d.rt())) {
			switch (t) {
			case 0:
				o.boxid = d.ri ();
				break;
			default:
				d.nod ();
				break;
			}
		}
		return o
	}

	function _encode_cs_cashCow_box_rewards_request(self: cs_cashCow_box_rewards_request, st: Sproto.SprotoStream) {
		let se = SprotoCore.GetSerialize(st, 1);

		if (self.boxid != undefined) {
			se.wi (self.boxid, 0);
		}

		return SprotoCore.CloseSerialize(se);
	}

	ALL_DICT["cs_cashCow_box_rewards_request"] = {en: _encode_cs_cashCow_box_rewards_request, de: _decode_cs_cashCow_box_rewards_request}
	export class cs_cashCow_shake_request {
	}

	function _decode_cs_cashCow_shake_request(d: SprotoTypeDeserialize) {
		let o = new cs_cashCow_shake_request;
		let t = -1;
		while (-1 != (t = d.rt())) {
			switch (t) {
			default:
				d.nod ();
				break;
			}
		}
		return o
	}

	function _encode_cs_cashCow_shake_request(self: cs_cashCow_shake_request, st: Sproto.SprotoStream) {
		let se = SprotoCore.GetSerialize(st, 0);

		return SprotoCore.CloseSerialize(se);
	}

	ALL_DICT["cs_cashCow_shake_request"] = {en: _encode_cs_cashCow_shake_request, de: _decode_cs_cashCow_shake_request}
}

