// Generated by sprotodump. DO NOT EDIT!

namespace Sproto { 
	export class cs_guildmine_enter_request {
	}

	function _decode_cs_guildmine_enter_request(d: SprotoTypeDeserialize) {
		let o = new cs_guildmine_enter_request;
		let t = -1;
		while (-1 != (t = d.rt())) {
			switch (t) {
			default:
				d.nod ();
				break;
			}
		}
		return o
	}

	function _encode_cs_guildmine_enter_request(self: cs_guildmine_enter_request, st: Sproto.SprotoStream) {
		let se = SprotoCore.GetSerialize(st, 0);

		return SprotoCore.CloseSerialize(se);
	}

	ALL_DICT["cs_guildmine_enter_request"] = {en: _encode_cs_guildmine_enter_request, de: _decode_cs_guildmine_enter_request}
	export class cs_guildmine_force_join_request {
		public mineId: number; // tag 0
	}

	function _decode_cs_guildmine_force_join_request(d: SprotoTypeDeserialize) {
		let o = new cs_guildmine_force_join_request;
		let t = -1;
		while (-1 != (t = d.rt())) {
			switch (t) {
			case 0:
				o.mineId = d.ri ();
				break;
			default:
				d.nod ();
				break;
			}
		}
		return o
	}

	function _encode_cs_guildmine_force_join_request(self: cs_guildmine_force_join_request, st: Sproto.SprotoStream) {
		let se = SprotoCore.GetSerialize(st, 1);

		if (self.mineId != undefined) {
			se.wi (self.mineId, 0);
		}

		return SprotoCore.CloseSerialize(se);
	}

	ALL_DICT["cs_guildmine_force_join_request"] = {en: _encode_cs_guildmine_force_join_request, de: _decode_cs_guildmine_force_join_request}
	export class cs_guildmine_force_join_response {
		public ret: boolean; // tag 0
	}

	function _decode_cs_guildmine_force_join_response(d: SprotoTypeDeserialize) {
		let o = new cs_guildmine_force_join_response;
		let t = -1;
		while (-1 != (t = d.rt())) {
			switch (t) {
			case 0:
				o.ret = d.rb ();
				break;
			default:
				d.nod ();
				break;
			}
		}
		return o
	}

	function _encode_cs_guildmine_force_join_response(self: cs_guildmine_force_join_response, st: Sproto.SprotoStream) {
		let se = SprotoCore.GetSerialize(st, 1);

		if (self.ret != undefined) {
			se.wb (self.ret, 0);
		}

		return SprotoCore.CloseSerialize(se);
	}

	ALL_DICT["cs_guildmine_force_join_response"] = {en: _encode_cs_guildmine_force_join_response, de: _decode_cs_guildmine_force_join_response}
	export class cs_guildmine_gather_request {
	}

	function _decode_cs_guildmine_gather_request(d: SprotoTypeDeserialize) {
		let o = new cs_guildmine_gather_request;
		let t = -1;
		while (-1 != (t = d.rt())) {
			switch (t) {
			default:
				d.nod ();
				break;
			}
		}
		return o
	}

	function _encode_cs_guildmine_gather_request(self: cs_guildmine_gather_request, st: Sproto.SprotoStream) {
		let se = SprotoCore.GetSerialize(st, 0);

		return SprotoCore.CloseSerialize(se);
	}

	ALL_DICT["cs_guildmine_gather_request"] = {en: _encode_cs_guildmine_gather_request, de: _decode_cs_guildmine_gather_request}
	export class cs_guildmine_gather_response {
		public ret: boolean; // tag 0
	}

	function _decode_cs_guildmine_gather_response(d: SprotoTypeDeserialize) {
		let o = new cs_guildmine_gather_response;
		let t = -1;
		while (-1 != (t = d.rt())) {
			switch (t) {
			case 0:
				o.ret = d.rb ();
				break;
			default:
				d.nod ();
				break;
			}
		}
		return o
	}

	function _encode_cs_guildmine_gather_response(self: cs_guildmine_gather_response, st: Sproto.SprotoStream) {
		let se = SprotoCore.GetSerialize(st, 1);

		if (self.ret != undefined) {
			se.wb (self.ret, 0);
		}

		return SprotoCore.CloseSerialize(se);
	}

	ALL_DICT["cs_guildmine_gather_response"] = {en: _encode_cs_guildmine_gather_response, de: _decode_cs_guildmine_gather_response}
	export class cs_guildmine_join_mine_request {
		public mineId: number; // tag 0
	}

	function _decode_cs_guildmine_join_mine_request(d: SprotoTypeDeserialize) {
		let o = new cs_guildmine_join_mine_request;
		let t = -1;
		while (-1 != (t = d.rt())) {
			switch (t) {
			case 0:
				o.mineId = d.ri ();
				break;
			default:
				d.nod ();
				break;
			}
		}
		return o
	}

	function _encode_cs_guildmine_join_mine_request(self: cs_guildmine_join_mine_request, st: Sproto.SprotoStream) {
		let se = SprotoCore.GetSerialize(st, 1);

		if (self.mineId != undefined) {
			se.wi (self.mineId, 0);
		}

		return SprotoCore.CloseSerialize(se);
	}

	ALL_DICT["cs_guildmine_join_mine_request"] = {en: _encode_cs_guildmine_join_mine_request, de: _decode_cs_guildmine_join_mine_request}
	export class cs_guildmine_join_mine_response {
		public ret: boolean; // tag 0
	}

	function _decode_cs_guildmine_join_mine_response(d: SprotoTypeDeserialize) {
		let o = new cs_guildmine_join_mine_response;
		let t = -1;
		while (-1 != (t = d.rt())) {
			switch (t) {
			case 0:
				o.ret = d.rb ();
				break;
			default:
				d.nod ();
				break;
			}
		}
		return o
	}

	function _encode_cs_guildmine_join_mine_response(self: cs_guildmine_join_mine_response, st: Sproto.SprotoStream) {
		let se = SprotoCore.GetSerialize(st, 1);

		if (self.ret != undefined) {
			se.wb (self.ret, 0);
		}

		return SprotoCore.CloseSerialize(se);
	}

	ALL_DICT["cs_guildmine_join_mine_response"] = {en: _encode_cs_guildmine_join_mine_response, de: _decode_cs_guildmine_join_mine_response}
	export class cs_guildmine_leave_mine_request {
	}

	function _decode_cs_guildmine_leave_mine_request(d: SprotoTypeDeserialize) {
		let o = new cs_guildmine_leave_mine_request;
		let t = -1;
		while (-1 != (t = d.rt())) {
			switch (t) {
			default:
				d.nod ();
				break;
			}
		}
		return o
	}

	function _encode_cs_guildmine_leave_mine_request(self: cs_guildmine_leave_mine_request, st: Sproto.SprotoStream) {
		let se = SprotoCore.GetSerialize(st, 0);

		return SprotoCore.CloseSerialize(se);
	}

	ALL_DICT["cs_guildmine_leave_mine_request"] = {en: _encode_cs_guildmine_leave_mine_request, de: _decode_cs_guildmine_leave_mine_request}
	export class cs_guildmine_mine_info_request {
		public mineId: number; // tag 0
	}

	function _decode_cs_guildmine_mine_info_request(d: SprotoTypeDeserialize) {
		let o = new cs_guildmine_mine_info_request;
		let t = -1;
		while (-1 != (t = d.rt())) {
			switch (t) {
			case 0:
				o.mineId = d.ri ();
				break;
			default:
				d.nod ();
				break;
			}
		}
		return o
	}

	function _encode_cs_guildmine_mine_info_request(self: cs_guildmine_mine_info_request, st: Sproto.SprotoStream) {
		let se = SprotoCore.GetSerialize(st, 1);

		if (self.mineId != undefined) {
			se.wi (self.mineId, 0);
		}

		return SprotoCore.CloseSerialize(se);
	}

	ALL_DICT["cs_guildmine_mine_info_request"] = {en: _encode_cs_guildmine_mine_info_request, de: _decode_cs_guildmine_mine_info_request}
	export class cs_guildmine_score_rank_request {
		public rankType: number; // tag 0
	}

	function _decode_cs_guildmine_score_rank_request(d: SprotoTypeDeserialize) {
		let o = new cs_guildmine_score_rank_request;
		let t = -1;
		while (-1 != (t = d.rt())) {
			switch (t) {
			case 0:
				o.rankType = d.ri ();
				break;
			default:
				d.nod ();
				break;
			}
		}
		return o
	}

	function _encode_cs_guildmine_score_rank_request(self: cs_guildmine_score_rank_request, st: Sproto.SprotoStream) {
		let se = SprotoCore.GetSerialize(st, 1);

		if (self.rankType != undefined) {
			se.wi (self.rankType, 0);
		}

		return SprotoCore.CloseSerialize(se);
	}

	ALL_DICT["cs_guildmine_score_rank_request"] = {en: _encode_cs_guildmine_score_rank_request, de: _decode_cs_guildmine_score_rank_request}
}

