// Generated by sprotodump. DO NOT EDIT!

namespace Sproto { 
	export class sc_holy_pet_info_request {
		public cash: number; // tag 0
		public reward: number; // tag 1
		public sTime: number; // tag 2
		public eTime: number; // tag 3
		public day: number; // tag 4
	}

	function _decode_sc_holy_pet_info_request(d: SprotoTypeDeserialize) {
		let o = new sc_holy_pet_info_request;
		let t = -1;
		while (-1 != (t = d.rt())) {
			switch (t) {
			case 0:
				o.cash = d.ri ();
				break;
			case 1:
				o.reward = d.ri ();
				break;
			case 2:
				o.sTime = d.ri ();
				break;
			case 3:
				o.eTime = d.ri ();
				break;
			case 4:
				o.day = d.ri ();
				break;
			default:
				d.nod ();
				break;
			}
		}
		return o
	}

	function _encode_sc_holy_pet_info_request(self: sc_holy_pet_info_request, st: Sproto.SprotoStream) {
		let se = SprotoCore.GetSerialize(st, 5);

		if (self.cash != undefined) {
			se.wi (self.cash, 0);
		}

		if (self.reward != undefined) {
			se.wi (self.reward, 1);
		}

		if (self.sTime != undefined) {
			se.wi (self.sTime, 2);
		}

		if (self.eTime != undefined) {
			se.wi (self.eTime, 3);
		}

		if (self.day != undefined) {
			se.wi (self.day, 4);
		}

		return SprotoCore.CloseSerialize(se);
	}

	ALL_DICT["sc_holy_pet_info_request"] = {en: _encode_sc_holy_pet_info_request, de: _decode_sc_holy_pet_info_request}
}

