// Generated by sprotodump. DO NOT EDIT!

namespace Sproto { 
	export class cs_panacea_use_request {
		public posid: number; // tag 0
	}

	function _decode_cs_panacea_use_request(d: SprotoTypeDeserialize) {
		let o = new cs_panacea_use_request;
		let t = -1;
		while (-1 != (t = d.rt())) {
			switch (t) {
			case 0:
				o.posid = d.ri ();
				break;
			default:
				d.nod ();
				break;
			}
		}
		return o
	}

	function _encode_cs_panacea_use_request(self: cs_panacea_use_request, st: Sproto.SprotoStream) {
		let se = SprotoCore.GetSerialize(st, 1);

		if (self.posid != undefined) {
			se.wi (self.posid, 0);
		}

		return SprotoCore.CloseSerialize(se);
	}

	ALL_DICT["cs_panacea_use_request"] = {en: _encode_cs_panacea_use_request, de: _decode_cs_panacea_use_request}
}

