// Generated by sprotodump. DO NOT EDIT!

class S2cProtocol extends Sproto.ProtocolBase {
	public static readonly sc_base_game_time: number = 6
	public static readonly sc_base_open_day: number = 7
	public static readonly sc_base_replace_account: number = 8
	public static readonly sc_error_code: number = 9
	public static readonly sc_actor_base: number = 101
	public static readonly sub_roles: number = 102
	public static readonly gold_change: number = 106
	public static readonly exp_change: number = 107
	public static readonly sub_role_att_change: number = 108
	public static readonly blood_update: number = 109
	public static readonly remove_entity: number = 110
	public static readonly move_entity: number = 111
	public static readonly stop_move_entity: number = 112
	public static readonly sync_entity_pos: number = 113
	public static readonly entity_mp_update: number = 114
	public static readonly sc_show_other_player: number = 116
	public static readonly show_server_tip: number = 117
	public static readonly first_register: number = 118
	public static readonly actor_die_notice: number = 120
	public static readonly player_guild_change: number = 121
	public static readonly sc_rename_result: number = 122
	public static readonly sc_record_datas: number = 125
	public static readonly sc_record_add: number = 126
	public static readonly sc_show_rank_player: number = 127
	public static readonly sc_cross_team_reward_count: number = 130
	public static readonly sc_welcome: number = 131
	public static readonly sc_accu_login: number = 132
	public static readonly sc_recharge_count: number = 133
	public static readonly sc_rank_worship: number = 134
	public static readonly sc_rename_count: number = 135
	public static readonly sc_show_other_spellsRes: number = 136
	public static readonly sc_show_other_pet: number = 137
	public static readonly sc_other_item: number = 138
	public static readonly sc_other_equip: number = 139
	public static readonly sc_other_xianlv: number = 140
	public static readonly sc_raid_chapter_init_info: number = 201
	public static readonly sc_raid_chapter_wave_data: number = 202
	public static readonly sc_raid_chapter_boss_result: number = 203
	public static readonly sc_raid_role_all_die: number = 204
	public static readonly sc_raid_chapter_reward: number = 205
	public static readonly sc_raid_chapter_world_reward: number = 206
	public static readonly sc_raid_chapter_mondata: number = 207
	public static readonly sc_raid_chapter_collaborate: number = 209
	public static readonly sc_raid_info_init: number = 210
	public static readonly sc_raid_update_info: number = 211
	public static readonly sc_raid_chapter_offline_reward: number = 212
	public static readonly sc_raid_time: number = 213
	public static readonly sc_raid_boss_box_num: number = 214
	public static readonly sc_raid_reborn_cd: number = 215
	public static readonly sc_raid_myboss_top: number = 216
	public static readonly sc_raid_material_info_init: number = 218
	public static readonly sc_raid_material_update_info: number = 219
	public static readonly sc_raid_material_result: number = 220
	public static readonly sc_raid_sweep_reward: number = 221
	public static readonly sc_skill_upgrade_result: number = 304
	public static readonly sc_skill_all_upgrade_result: number = 305
	public static readonly sc_bag_init_data: number = 401
	public static readonly sc_bag_deal_valumn_add: number = 402
	public static readonly sc_bag_deal_delete_item: number = 403
	public static readonly sc_bag_deal_add_item: number = 404
	public static readonly sc_bag_update_item_data: number = 405
	public static readonly sc_bag_user_item_back: number = 406
	public static readonly sc_bag_get_treasure_equip: number = 408
	public static readonly sc_bag_deal_smelt_result: number = 409
	public static readonly sc_equip_update_data: number = 501
	public static readonly sc_equip_update_suitlv: number = 505
	public static readonly sc_equip_forge: number = 511
	public static readonly sc_pet_init: number = 601
	public static readonly sc_pet_update: number = 606
	public static readonly sc_pet_catch: number = 621
	public static readonly sc_pet_catch_result: number = 622
	public static readonly sc_xianlv_init: number = 701
	public static readonly sc_mail_init_info: number = 901
	public static readonly sc_mail_detailed_info: number = 902
	public static readonly sc_mail_delete: number = 903
	public static readonly sc_mail_update_info: number = 904
	public static readonly sc_mail_add_info: number = 905
	public static readonly sc_shop_buy: number = 1701
	public static readonly sc_shop_buy_update: number = 1710
	public static readonly sc_shop_mystical_update: number = 1711
	public static readonly sc_shop_buy_unlockdata: number = 1716
	public static readonly sc_recharge_double: number = 1801
	public static readonly sc_recharge_first_info: number = 1802
	public static readonly sc_recharge_dailyrechare: number = 1806
	public static readonly sc_rank_data: number = 1901
	public static readonly sc_rank_worship_data: number = 1902
	public static readonly sc_rank_worship_success: number = 1903
	public static readonly sc_rank_worship_all_count_ret: number = 1904
	public static readonly sc_kfboss_info: number = 2101
	public static readonly sc_kfboss_update_info: number = 2102
	public static readonly sc_kfboss_box_all: number = 2103
	public static readonly sc_kfboss_box_one: number = 2104
	public static readonly sc_kfboss_player_dead: number = 2105
	public static readonly sc_kfboss_rank_now: number = 2106
	public static readonly sc_kfboss_rewards: number = 2107
	public static readonly sc_kfboss_rank_last: number = 2108
	public static readonly sc_kfboss_collect_now: number = 2109
	public static readonly sc_kfboss_collect_all: number = 2110
	public static readonly sc_kfboss_report: number = 2111
	public static readonly sc_cashCow_info: number = 2201
	public static readonly sc_activity_init_info: number = 2601
	public static readonly sc_activity_reward_result: number = 2602
	public static readonly sc_activity_dabiao_info: number = 2603
	public static readonly sc_activity_dabiao_reward: number = 2604
	public static readonly sc_activity_update_info: number = 2606
	public static readonly sc_activity_race_history: number = 2607
	public static readonly sc_activity_close_cross: number = 2608
	public static readonly sc_activity_luckwheel_ret: number = 2609
	public static readonly sc_luck_info: number = 2701
	public static readonly sc_luck_ret: number = 2702
	public static readonly sc_auction_select: number = 2801
	public static readonly sc_auction_list: number = 2802
	public static readonly sc_auction_record: number = 2803
	public static readonly sc_auction_update: number = 2804
	public static readonly sc_ratio_change: number = 2805
	public static readonly sc_aution_notice: number = 2806
	public static readonly sc_chat_new_msg: number = 3101
	public static readonly sc_chat_init_msg: number = 3102
	public static readonly sc_chat_is_send_success: number = 3103
	public static readonly sc_chat_private_new_msg: number = 3131
	public static readonly sc_chat_private_init_msg: number = 3132
	public static readonly sc_chat_filte_list: number = 3133
	public static readonly sc_ladder_info: number = 3501
	public static readonly sc_ladder_player_back: number = 3502
	public static readonly sc_ladder_result: number = 3503
	public static readonly sc_ladder_rank_list: number = 3505
	public static readonly sc_ladder_buy_count: number = 3506
	public static readonly sc_ladder_winner_info: number = 3507
	public static readonly sc_ladder_winner_records: number = 3508
	public static readonly sc_money_tree_info: number = 3701
	public static readonly sc_money_tree_play_info: number = 3702
	public static readonly sc_money_tree_reward_info: number = 3703
	public static readonly sc_money_recharge_gift_info: number = 3704
	public static readonly sc_qdday_reward_info: number = 3705
	public static readonly sc_guild_info: number = 3801
	public static readonly sc_guild_members: number = 3802
	public static readonly sc_guild_list: number = 3803
	public static readonly sc_guild_create_ret: number = 3804
	public static readonly sc_guild_join_info: number = 3806
	public static readonly sc_guild_apply: number = 3807
	public static readonly sc_guild_notice_apply: number = 3808
	public static readonly sc_guild_change_office_ret: number = 3809
	public static readonly sc_guild_kick_ret: number = 3811
	public static readonly sc_guild_fund: number = 3813
	public static readonly sc_guild_change_notice_ret: number = 3814
	public static readonly sc_guild_record_add: number = 3821
	public static readonly sc_guild_record_data: number = 3822
	public static readonly sc_guild_playerinfo: number = 3825
	public static readonly sc_guild_autoadd_ret: number = 3828
	public static readonly sc_guild_rename: number = 3829
	public static readonly sc_guild_rename_ret: number = 3830
	public static readonly sc_guild_apply_list: number = 3831
	public static readonly sc_guild_donate_ret: number = 3841
	public static readonly sc_guild_donate_info: number = 3842
	public static readonly sc_guild_peach_info: number = 3846
	public static readonly sc_guild_peach_record: number = 3847
	public static readonly sc_guild_peach_record_add: number = 3848
	public static readonly sc_guild_protector_info: number = 3851
	public static readonly sc_guild_protector_task_info: number = 3852
	public static readonly sc_guild_skill_info: number = 3856
	public static readonly sc_guild_skill_learn_ret: number = 3857
	public static readonly sc_guild_map_reward: number = 3861
	public static readonly sc_guild_map_one_update: number = 3862
	public static readonly sc_guild_boss_info: number = 3863
	public static readonly sc_guild_robot_datas: number = 3864
	public static readonly sc_template_init_data: number = 5001
	public static readonly sc_template_update_data: number = 5002
	public static readonly sc_wing_upgrade_level: number = 5101
	public static readonly sc_wing_upgrade_skill: number = 5102
	public static readonly sc_wing_equip: number = 5103
	public static readonly sc_fuben_material_info: number = 5201
	public static readonly sc_fuben_treasuremap_info: number = 5202
	public static readonly sc_fuben_treasuremap_star_reward: number = 5203
	public static readonly sc_fuben_wildgeeseFb_info: number = 5204
	public static readonly sc_fuben_heavenFb_info: number = 5205
	public static readonly sc_fuben_heavenFb_reward: number = 5206
	public static readonly sc_tiannv_equip: number = 5301
	public static readonly sc_tiannv_wash_res: number = 5302
	public static readonly sc_tiannv_wash_replace_res: number = 5303
	public static readonly sc_spellsRes_info: number = 5401
	public static readonly sc_tianshen_info: number = 5501
	public static readonly sc_tianshen_spells_info: number = 5502
	public static readonly sc_formation_info: number = 5601
	public static readonly sc_dailyTask_info: number = 5701
	public static readonly sc_dailyTask_update: number = 5702
	public static readonly sc_answer_info: number = 5801
	public static readonly sc_answer_update: number = 5802
	public static readonly sc_answer_reward: number = 5803
	public static readonly sc_answer_rank_res: number = 5804
	public static readonly sc_advanced_info: number = 5901
	public static readonly sc_advanced_update: number = 5902
	public static readonly sc_advanced_rank: number = 5903
	public static readonly sc_vipboss_base_list: number = 6002
	public static readonly sc_vipboss_update_one: number = 6003
	public static readonly sc_holy_pet_info: number = 6101
	public static readonly sc_totems_info: number = 6201
	public static readonly sc_enhance_info: number = 6301
	public static readonly sc_enhance_add_info: number = 6302
	public static readonly sc_rechargew_shit: number = 6401
	public static readonly sc_rechargew_shitstep: number = 6402
	public static readonly sc_rechargew_shitindex: number = 6403
	public static readonly sc_rechargew_shitclose: number = 6404
	public static readonly sc_rechargew_shitinit: number = 6405
	public static readonly sc_position_info: number = 6501
	public static readonly sc_battle_action: number = 7000
	public static readonly sc_battle_entitys: number = 7001
	public static readonly sc_battle_record: number = 7002
	public static readonly sc_battle_manual: number = 7003
	public static readonly sc_battle_set_auto: number = 7004
	public static readonly sc_brother_info: number = 8001
	public static readonly sc_marry_info: number = 8101
	public static readonly sc_marry_friends: number = 8102
	public static readonly sc_marry_asked: number = 8103
	public static readonly sc_marry_remove_asked: number = 8104
	public static readonly sc_marry_answer: number = 8105
	public static readonly sc_marry_invitation: number = 8106
	public static readonly sc_marry_recv_flower: number = 8107
	public static readonly sc_marry_flower_bro: number = 8108
	public static readonly sc_marry_login_tip: number = 8109
	public static readonly sc_marry_token_status: number = 8110
	public static readonly sc_marry_divorce_bro: number = 8111
	public static readonly sc_marry_love_info: number = 8112
	public static readonly sc_marry_house_partner_up: number = 8113
	public static readonly sc_marry_new: number = 8114
	public static readonly sc_baby_init: number = 8201
	public static readonly sc_baby_star_init: number = 8202
	public static readonly sc_field_boss_base_list: number = 11002
	public static readonly sc_field_boss_update_one: number = 11003
	public static readonly sc_public_boss_challenge_fail: number = 12010
	public static readonly sc_public_boss_base_list: number = 12011
	public static readonly sc_public_boss_update_one: number = 12012
	public static readonly sc_public_boss_update_challenge: number = 12020
	public static readonly sc_public_boss_update_attack: number = 12021
	public static readonly sc_public_boss_record_attack: number = 12030
	public static readonly sc_public_boss_record_kill: number = 12031
	public static readonly sc_arena_pk_result: number = 13001
	public static readonly sc_effect_title_update: number = 14001
	public static readonly sc_effect_skin_update: number = 14011
	public static readonly sc_vein_update: number = 15001
	public static readonly sc_panacea_update: number = 16001
	public static readonly sc_team_info: number = 17001
	public static readonly sc_team_list: number = 17002
	public static readonly sc_team_one: number = 17003
	public static readonly sc_task_info: number = 18001
	public static readonly sc_task_update: number = 18002
	public static readonly sc_escort_info_update: number = 20001
	public static readonly sc_escort_reward_show: number = 20007
	public static readonly sc_escort_record_data: number = 20030
	public static readonly sc_escort_record_update: number = 20031
	public static readonly sc_vip_update_data: number = 21001
	public static readonly sc_activity_info_res: number = 22001
	public static readonly sc_activity_msg: number = 22002
	public static readonly sc_activity_hall: number = 22003
	public static readonly sc_qualifyingMgr_info_res: number = 22101
	public static readonly sc_qualifyingMgr_map_info_res: number = 22102
	public static readonly sc_qualifyingMgr_war_info: number = 22103
	public static readonly sc_map_enter: number = 23001
	public static readonly sc_map_other_enter: number = 23002
	public static readonly sc_map_other_leave: number = 23003
	public static readonly sc_map_other_move: number = 23004
	public static readonly sc_map_other_fly: number = 23005
	public static readonly sc_map_player_status: number = 23006
	public static readonly sc_map_player_update: number = 23007
	public static readonly sc_map_maincity_info: number = 23035
	public static readonly sc_king_info: number = 24001
	public static readonly sc_king_city_data: number = 24002
	public static readonly sc_king_begin_act: number = 24003
	public static readonly sc_king_status_change: number = 24004
	public static readonly sc_king_fighting_change: number = 24005
	public static readonly sc_king_player_enter: number = 24006
	public static readonly sc_king_player_leave: number = 24007
	public static readonly sc_king_point_info: number = 24008
	public static readonly sc_king_point_data: number = 24009
	public static readonly sc_king_city_occupy: number = 24010
	public static readonly sc_king_transform_change: number = 24011
	public static readonly sc_king_attack_result: number = 24012
	public static readonly sc_king_pk_result: number = 24013
	public static readonly sc_king_reborn_countdown: number = 24014
	public static readonly sc_king_update_city: number = 24015
	public static readonly sc_king_my_guard_city: number = 24016
	public static readonly sc_king_info_update: number = 24017
	public static readonly sc_guildmine_mine_info: number = 25001
	public static readonly sc_guildmine_mine_one_info: number = 25002
	public static readonly sc_guildmine_mine_mystatus: number = 25003
	public static readonly sc_guildmine_score_rank_day: number = 25016
	public static readonly sc_guildmine_rob_info: number = 25021
	public static readonly sc_climb_all_rank: number = 26001
	public static readonly sc_climb_info: number = 26002
	public static readonly sc_climb_curr_rank: number = 26003
	public static readonly sc_climb_refresh_mon: number = 26004
	public static readonly sc_climb_score_info: number = 26005
	public static readonly sc_climb_fighting_change: number = 26006
	public static readonly sc_climb_king: number = 26007
	public static readonly sc_climb_report: number = 26008
	public static readonly sc_guildwar_player_info: number = 27001
	public static readonly sc_guildwar_guild_info: number = 27002
	public static readonly sc_guildwar_guild_rank: number = 27003
	public static readonly sc_guildwar_player_rank: number = 27004
	public static readonly sc_guildwar_barrier_info: number = 27005
	public static readonly sc_guildwar_boss_info: number = 27006
	public static readonly sc_guildwar_guard_info: number = 27007
	public static readonly sc_guildwar_four_king_info: number = 27008
	public static readonly sc_guildwar_player_global_info: number = 27009
	public static readonly sc_guildwar_myguild_global_info: number = 27010
	public static readonly sc_king_report: number = 27018
	public static readonly sc_guildwar_all_guild_rank_info: number = 27030
	public static readonly sc_guildwar_all_player_rank_info: number = 27031
	public static readonly sc_guildwar_enter_dragon_guild: number = 27035
	public static readonly sc_guildwar_ultimate_attack: number = 27036
	public static readonly sc_guildwar_enter_war_guild: number = 27041
	public static readonly sc_guildwar_report: number = 27042
	public static readonly sc_fuben_eightyOneHard_info: number = 28001
	public static readonly sc_fuben_eightyOneHard_info_update: number = 28002
	public static readonly sc_teachers_info: number = 29001
	public static readonly sc_teachers_update: number = 29002
	public static readonly sc_teachers_graduation: number = 29003
	public static readonly sc_teachers_message_add: number = 29004
	public static readonly sc_friend_follow_data: number = 30001
	public static readonly sc_friend_follow_update: number = 30002
	public static readonly sc_friend_funs_data: number = 30006
	public static readonly sc_friend_funs_update: number = 30007
	public static readonly sc_friend_funs_remove: number = 30008
	public static readonly sc_friend_black_list: number = 30011
	public static readonly sc_friend_blacklist_update: number = 30012
	public static readonly sc_friend_gift_receive_info: number = 30016
	public static readonly sc_friend_follow_nominate_list: number = 30021
	public static readonly sc_welfare_signin_info: number = 31001
	public static readonly sc_welfare_bonus_add: number = 31006
	public static readonly sc_welfare_login_gift_info: number = 31011
	public static readonly sc_welfare_info: number = 31050
	public static readonly sc_guildboss_info: number = 32001
	public static readonly sc_guildboss_update_info: number = 32002
	public static readonly sc_guildboss_box_all: number = 32003
	public static readonly sc_guildboss_box_one: number = 32004
	public static readonly sc_guildboss_player_dead: number = 32005
	public static readonly sc_guildboss_rank_now: number = 32006
	public static readonly sc_guildboss_rewards: number = 32007
	public static readonly sc_guildboss_rank_last: number = 32008
	public static readonly sc_guildboss_collect_now: number = 32009
	public static readonly sc_guildboss_collect_all: number = 32010
	public constructor() {
		super()
		let prof = this.Protocol
		prof.Set(120, "actor_die_notice_request", null);
		prof.Set(109, "blood_update_request", null);
		prof.Set(114, "entity_mp_update_request", null);
		prof.Set(107, "exp_change_request", null);
		prof.Set(118, "first_register_request", null);
		prof.Set(106, "gold_change_request", null);
		prof.Set(111, "move_entity_request", null);
		prof.Set(121, "player_guild_change_request", null);
		prof.Set(110, "remove_entity_request", null);
		prof.Set(132, "sc_accu_login_request", null);
		prof.Set(2608, null, null);
		prof.Set(2603, "sc_activity_dabiao_info_request", null);
		prof.Set(2604, "sc_activity_dabiao_reward_request", null);
		prof.Set(22003, "sc_activity_hall_request", null);
		prof.Set(22001, "sc_activity_info_res_request", null);
		prof.Set(2601, "sc_activity_init_info_request", null);
		prof.Set(2609, "sc_activity_luckwheel_ret_request", null);
		prof.Set(22002, "sc_activity_msg_request", null);
		prof.Set(2607, "sc_activity_race_history_request", null);
		prof.Set(2602, "sc_activity_reward_result_request", null);
		prof.Set(2606, "sc_activity_update_info_request", null);
		prof.Set(101, "sc_actor_base_request", null);
		prof.Set(5901, "sc_advanced_info_request", null);
		prof.Set(5903, "sc_advanced_rank_request", null);
		prof.Set(5902, "sc_advanced_update_request", null);
		prof.Set(5801, "sc_answer_info_request", null);
		prof.Set(5804, "sc_answer_rank_res_request", null);
		prof.Set(5803, "sc_answer_reward_request", null);
		prof.Set(5802, "sc_answer_update_request", null);
		prof.Set(13001, "sc_arena_pk_result_request", null);
		prof.Set(2802, "sc_auction_list_request", null);
		prof.Set(2803, "sc_auction_record_request", null);
		prof.Set(2801, "sc_auction_select_request", null);
		prof.Set(2804, "sc_auction_update_request", null);
		prof.Set(2806, null, null);
		prof.Set(8201, "sc_baby_init_request", null);
		prof.Set(8202, "sc_baby_star_init_request", null);
		prof.Set(404, "sc_bag_deal_add_item_request", null);
		prof.Set(403, "sc_bag_deal_delete_item_request", null);
		prof.Set(409, "sc_bag_deal_smelt_result_request", null);
		prof.Set(402, "sc_bag_deal_valumn_add_request", null);
		prof.Set(408, "sc_bag_get_treasure_equip_request", null);
		prof.Set(401, "sc_bag_init_data_request", null);
		prof.Set(405, "sc_bag_update_item_data_request", null);
		prof.Set(406, "sc_bag_user_item_back_request", null);
		prof.Set(6, "sc_base_game_time_request", null);
		prof.Set(7, "sc_base_open_day_request", null);
		prof.Set(8, null, null);
		prof.Set(7000, "sc_battle_action_request", null);
		prof.Set(7001, "sc_battle_entitys_request", null);
		prof.Set(7003, "sc_battle_manual_request", null);
		prof.Set(7002, "sc_battle_record_request", null);
		prof.Set(7004, "sc_battle_set_auto_request", null);
		prof.Set(8001, "sc_brother_info_request", null);
		prof.Set(2201, "sc_cashCow_info_request", null);
		prof.Set(3133, "sc_chat_filte_list_request", null);
		prof.Set(3102, "sc_chat_init_msg_request", null);
		prof.Set(3103, "sc_chat_is_send_success_request", null);
		prof.Set(3101, "sc_chat_new_msg_request", null);
		prof.Set(3132, "sc_chat_private_init_msg_request", null);
		prof.Set(3131, "sc_chat_private_new_msg_request", null);
		prof.Set(26001, "sc_climb_all_rank_request", null);
		prof.Set(26003, "sc_climb_curr_rank_request", null);
		prof.Set(26006, "sc_climb_fighting_change_request", null);
		prof.Set(26002, "sc_climb_info_request", null);
		prof.Set(26007, "sc_climb_king_request", null);
		prof.Set(26004, "sc_climb_refresh_mon_request", null);
		prof.Set(26008, "sc_climb_report_request", null);
		prof.Set(26005, "sc_climb_score_info_request", null);
		prof.Set(130, "sc_cross_team_reward_count_request", null);
		prof.Set(5701, "sc_dailyTask_info_request", null);
		prof.Set(5702, "sc_dailyTask_update_request", null);
		prof.Set(14011, "sc_effect_skin_update_request", null);
		prof.Set(14001, "sc_effect_title_update_request", null);
		prof.Set(6302, "sc_enhance_add_info_request", null);
		prof.Set(6301, "sc_enhance_info_request", null);
		prof.Set(511, "sc_equip_forge_request", null);
		prof.Set(501, "sc_equip_update_data_request", null);
		prof.Set(505, "sc_equip_update_suitlv_request", null);
		prof.Set(9, "sc_error_code_request", null);
		prof.Set(20001, "sc_escort_info_update_request", null);
		prof.Set(20030, "sc_escort_record_data_request", null);
		prof.Set(20031, "sc_escort_record_update_request", null);
		prof.Set(20007, "sc_escort_reward_show_request", null);
		prof.Set(11002, "sc_field_boss_base_list_request", null);
		prof.Set(11003, "sc_field_boss_update_one_request", null);
		prof.Set(5601, "sc_formation_info_request", null);
		prof.Set(30011, "sc_friend_black_list_request", null);
		prof.Set(30012, "sc_friend_blacklist_update_request", null);
		prof.Set(30001, "sc_friend_follow_data_request", null);
		prof.Set(30021, "sc_friend_follow_nominate_list_request", null);
		prof.Set(30002, "sc_friend_follow_update_request", null);
		prof.Set(30006, "sc_friend_funs_data_request", null);
		prof.Set(30008, "sc_friend_funs_remove_request", null);
		prof.Set(30007, "sc_friend_funs_update_request", null);
		prof.Set(30016, "sc_friend_gift_receive_info_request", null);
		prof.Set(28001, "sc_fuben_eightyOneHard_info_request", null);
		prof.Set(28002, "sc_fuben_eightyOneHard_info_update_request", null);
		prof.Set(5205, "sc_fuben_heavenFb_info_request", null);
		prof.Set(5206, "sc_fuben_heavenFb_reward_request", null);
		prof.Set(5201, "sc_fuben_material_info_request", null);
		prof.Set(5202, "sc_fuben_treasuremap_info_request", null);
		prof.Set(5203, "sc_fuben_treasuremap_star_reward_request", null);
		prof.Set(5204, "sc_fuben_wildgeeseFb_info_request", null);
		prof.Set(3807, "sc_guild_apply_request", null);
		prof.Set(3831, "sc_guild_apply_list_request", null);
		prof.Set(3828, "sc_guild_autoadd_ret_request", null);
		prof.Set(3863, "sc_guild_boss_info_request", null);
		prof.Set(3814, "sc_guild_change_notice_ret_request", null);
		prof.Set(3809, "sc_guild_change_office_ret_request", null);
		prof.Set(3804, "sc_guild_create_ret_request", null);
		prof.Set(3842, "sc_guild_donate_info_request", null);
		prof.Set(3841, "sc_guild_donate_ret_request", null);
		prof.Set(3813, "sc_guild_fund_request", null);
		prof.Set(3801, "sc_guild_info_request", null);
		prof.Set(3806, null, null);
		prof.Set(3811, "sc_guild_kick_ret_request", null);
		prof.Set(3803, "sc_guild_list_request", null);
		prof.Set(3862, "sc_guild_map_one_update_request", null);
		prof.Set(3861, "sc_guild_map_reward_request", null);
		prof.Set(3802, "sc_guild_members_request", null);
		prof.Set(3808, "sc_guild_notice_apply_request", null);
		prof.Set(3846, "sc_guild_peach_info_request", null);
		prof.Set(3847, "sc_guild_peach_record_request", null);
		prof.Set(3848, "sc_guild_peach_record_add_request", null);
		prof.Set(3825, "sc_guild_playerinfo_request", null);
		prof.Set(3851, "sc_guild_protector_info_request", null);
		prof.Set(3852, "sc_guild_protector_task_info_request", null);
		prof.Set(3821, "sc_guild_record_add_request", null);
		prof.Set(3822, "sc_guild_record_data_request", null);
		prof.Set(3829, "sc_guild_rename_request", null);
		prof.Set(3830, "sc_guild_rename_ret_request", null);
		prof.Set(3864, "sc_guild_robot_datas_request", null);
		prof.Set(3856, "sc_guild_skill_info_request", null);
		prof.Set(3857, "sc_guild_skill_learn_ret_request", null);
		prof.Set(32003, "sc_guildboss_box_all_request", null);
		prof.Set(32004, "sc_guildboss_box_one_request", null);
		prof.Set(32010, "sc_guildboss_collect_all_request", null);
		prof.Set(32009, "sc_guildboss_collect_now_request", null);
		prof.Set(32001, "sc_guildboss_info_request", null);
		prof.Set(32005, "sc_guildboss_player_dead_request", null);
		prof.Set(32008, "sc_guildboss_rank_last_request", null);
		prof.Set(32006, "sc_guildboss_rank_now_request", null);
		prof.Set(32007, "sc_guildboss_rewards_request", null);
		prof.Set(32002, "sc_guildboss_update_info_request", null);
		prof.Set(25001, "sc_guildmine_mine_info_request", null);
		prof.Set(25003, "sc_guildmine_mine_mystatus_request", null);
		prof.Set(25002, "sc_guildmine_mine_one_info_request", null);
		prof.Set(25021, "sc_guildmine_rob_info_request", null);
		prof.Set(25016, "sc_guildmine_score_rank_day_request", null);
		prof.Set(27030, "sc_guildwar_all_guild_rank_info_request", null);
		prof.Set(27031, "sc_guildwar_all_player_rank_info_request", null);
		prof.Set(27005, "sc_guildwar_barrier_info_request", null);
		prof.Set(27006, "sc_guildwar_boss_info_request", null);
		prof.Set(27035, "sc_guildwar_enter_dragon_guild_request", null);
		prof.Set(27041, "sc_guildwar_enter_war_guild_request", null);
		prof.Set(27008, "sc_guildwar_four_king_info_request", null);
		prof.Set(27007, "sc_guildwar_guard_info_request", null);
		prof.Set(27002, "sc_guildwar_guild_info_request", null);
		prof.Set(27003, "sc_guildwar_guild_rank_request", null);
		prof.Set(27010, "sc_guildwar_myguild_global_info_request", null);
		prof.Set(27009, "sc_guildwar_player_global_info_request", null);
		prof.Set(27001, "sc_guildwar_player_info_request", null);
		prof.Set(27004, "sc_guildwar_player_rank_request", null);
		prof.Set(27042, "sc_guildwar_report_request", null);
		prof.Set(27036, "sc_guildwar_ultimate_attack_request", null);
		prof.Set(6101, "sc_holy_pet_info_request", null);
		prof.Set(2103, "sc_kfboss_box_all_request", null);
		prof.Set(2104, "sc_kfboss_box_one_request", null);
		prof.Set(2110, "sc_kfboss_collect_all_request", null);
		prof.Set(2109, "sc_kfboss_collect_now_request", null);
		prof.Set(2101, "sc_kfboss_info_request", null);
		prof.Set(2105, "sc_kfboss_player_dead_request", null);
		prof.Set(2108, "sc_kfboss_rank_last_request", null);
		prof.Set(2106, "sc_kfboss_rank_now_request", null);
		prof.Set(2111, "sc_kfboss_report_request", null);
		prof.Set(2107, "sc_kfboss_rewards_request", null);
		prof.Set(2102, "sc_kfboss_update_info_request", null);
		prof.Set(24012, "sc_king_attack_result_request", null);
		prof.Set(24003, "sc_king_begin_act_request", null);
		prof.Set(24002, "sc_king_city_data_request", null);
		prof.Set(24010, "sc_king_city_occupy_request", null);
		prof.Set(24005, "sc_king_fighting_change_request", null);
		prof.Set(24001, "sc_king_info_request", null);
		prof.Set(24017, "sc_king_info_update_request", null);
		prof.Set(24016, "sc_king_my_guard_city_request", null);
		prof.Set(24013, "sc_king_pk_result_request", null);
		prof.Set(24006, "sc_king_player_enter_request", null);
		prof.Set(24007, "sc_king_player_leave_request", null);
		prof.Set(24009, "sc_king_point_data_request", null);
		prof.Set(24008, "sc_king_point_info_request", null);
		prof.Set(24014, "sc_king_reborn_countdown_request", null);
		prof.Set(27018, "sc_king_report_request", null);
		prof.Set(24004, "sc_king_status_change_request", null);
		prof.Set(24011, "sc_king_transform_change_request", null);
		prof.Set(24015, "sc_king_update_city_request", null);
		prof.Set(3506, "sc_ladder_buy_count_request", null);
		prof.Set(3501, "sc_ladder_info_request", null);
		prof.Set(3502, "sc_ladder_player_back_request", null);
		prof.Set(3505, "sc_ladder_rank_list_request", null);
		prof.Set(3503, "sc_ladder_result_request", null);
		prof.Set(3507, "sc_ladder_winner_info_request", null);
		prof.Set(3508, "sc_ladder_winner_records_request", null);
		prof.Set(2701, "sc_luck_info_request", null);
		prof.Set(2702, "sc_luck_ret_request", null);
		prof.Set(905, "sc_mail_add_info_request", null);
		prof.Set(903, "sc_mail_delete_request", null);
		prof.Set(902, "sc_mail_detailed_info_request", null);
		prof.Set(901, "sc_mail_init_info_request", null);
		prof.Set(904, "sc_mail_update_info_request", null);
		prof.Set(23001, "sc_map_enter_request", null);
		prof.Set(23035, "sc_map_maincity_info_request", null);
		prof.Set(23002, "sc_map_other_enter_request", null);
		prof.Set(23005, "sc_map_other_fly_request", null);
		prof.Set(23003, "sc_map_other_leave_request", null);
		prof.Set(23004, "sc_map_other_move_request", null);
		prof.Set(23006, "sc_map_player_status_request", null);
		prof.Set(23007, "sc_map_player_update_request", null);
		prof.Set(8105, "sc_marry_answer_request", null);
		prof.Set(8103, "sc_marry_asked_request", null);
		prof.Set(8111, "sc_marry_divorce_bro_request", null);
		prof.Set(8108, "sc_marry_flower_bro_request", null);
		prof.Set(8102, "sc_marry_friends_request", null);
		prof.Set(8113, "sc_marry_house_partner_up_request", null);
		prof.Set(8101, "sc_marry_info_request", null);
		prof.Set(8106, "sc_marry_invitation_request", null);
		prof.Set(8109, "sc_marry_login_tip_request", null);
		prof.Set(8112, "sc_marry_love_info_request", null);
		prof.Set(8114, "sc_marry_new_request", null);
		prof.Set(8107, "sc_marry_recv_flower_request", null);
		prof.Set(8104, "sc_marry_remove_asked_request", null);
		prof.Set(8110, "sc_marry_token_status_request", null);
		prof.Set(3704, "sc_money_recharge_gift_info_request", null);
		prof.Set(3701, "sc_money_tree_info_request", null);
		prof.Set(3702, "sc_money_tree_play_info_request", null);
		prof.Set(3703, "sc_money_tree_reward_info_request", null);
		prof.Set(139, "sc_other_equip_request", null);
		prof.Set(138, "sc_other_item_request", null);
		prof.Set(140, "sc_other_xianlv_request", null);
		prof.Set(16001, "sc_panacea_update_request", null);
		prof.Set(621, "sc_pet_catch_request", null);
		prof.Set(622, "sc_pet_catch_result_request", null);
		prof.Set(601, "sc_pet_init_request", null);
		prof.Set(606, "sc_pet_update_request", null);
		prof.Set(6501, "sc_position_info_request", null);
		prof.Set(12011, "sc_public_boss_base_list_request", null);
		prof.Set(12010, "sc_public_boss_challenge_fail_request", null);
		prof.Set(12030, "sc_public_boss_record_attack_request", null);
		prof.Set(12031, "sc_public_boss_record_kill_request", null);
		prof.Set(12021, "sc_public_boss_update_attack_request", null);
		prof.Set(12020, "sc_public_boss_update_challenge_request", null);
		prof.Set(12012, "sc_public_boss_update_one_request", null);
		prof.Set(3705, "sc_qdday_reward_info_request", null);
		prof.Set(22101, "sc_qualifyingMgr_info_res_request", null);
		prof.Set(22102, "sc_qualifyingMgr_map_info_res_request", null);
		prof.Set(22103, "sc_qualifyingMgr_war_info_request", null);
		prof.Set(214, "sc_raid_boss_box_num_request", null);
		prof.Set(203, "sc_raid_chapter_boss_result_request", null);
		prof.Set(209, "sc_raid_chapter_collaborate_request", null);
		prof.Set(201, "sc_raid_chapter_init_info_request", null);
		prof.Set(207, "sc_raid_chapter_mondata_request", null);
		prof.Set(212, "sc_raid_chapter_offline_reward_request", null);
		prof.Set(205, "sc_raid_chapter_reward_request", null);
		prof.Set(202, "sc_raid_chapter_wave_data_request", null);
		prof.Set(206, "sc_raid_chapter_world_reward_request", null);
		prof.Set(210, "sc_raid_info_init_request", null);
		prof.Set(218, "sc_raid_material_info_init_request", null);
		prof.Set(220, "sc_raid_material_result_request", null);
		prof.Set(219, "sc_raid_material_update_info_request", null);
		prof.Set(216, "sc_raid_myboss_top_request", null);
		prof.Set(215, "sc_raid_reborn_cd_request", null);
		prof.Set(204, "sc_raid_role_all_die_request", null);
		prof.Set(221, "sc_raid_sweep_reward_request", null);
		prof.Set(213, "sc_raid_time_request", null);
		prof.Set(211, "sc_raid_update_info_request", null);
		prof.Set(1901, "sc_rank_data_request", null);
		prof.Set(134, "sc_rank_worship_request", null);
		prof.Set(1904, "sc_rank_worship_all_count_ret_request", null);
		prof.Set(1902, "sc_rank_worship_data_request", null);
		prof.Set(1903, "sc_rank_worship_success_request", null);
		prof.Set(2805, "sc_ratio_change_request", null);
		prof.Set(133, "sc_recharge_count_request", null);
		prof.Set(1806, "sc_recharge_dailyrechare_request", null);
		prof.Set(1801, "sc_recharge_double_request", null);
		prof.Set(1802, "sc_recharge_first_info_request", null);
		prof.Set(6401, "sc_rechargew_shit_request", null);
		prof.Set(6404, "sc_rechargew_shitclose_request", null);
		prof.Set(6403, "sc_rechargew_shitindex_request", null);
		prof.Set(6405, "sc_rechargew_shitinit_request", null);
		prof.Set(6402, "sc_rechargew_shitstep_request", null);
		prof.Set(126, "sc_record_add_request", null);
		prof.Set(125, "sc_record_datas_request", null);
		prof.Set(135, "sc_rename_count_request", null);
		prof.Set(122, "sc_rename_result_request", null);
		prof.Set(1701, "sc_shop_buy_request", null);
		prof.Set(1716, "sc_shop_buy_unlockdata_request", null);
		prof.Set(1710, "sc_shop_buy_update_request", null);
		prof.Set(1711, "sc_shop_mystical_update_request", null);
		prof.Set(137, "sc_show_other_pet_request", null);
		prof.Set(116, "sc_show_other_player_request", null);
		prof.Set(136, "sc_show_other_spellsRes_request", null);
		prof.Set(127, "sc_show_rank_player_request", null);
		prof.Set(305, "sc_skill_all_upgrade_result_request", null);
		prof.Set(304, "sc_skill_upgrade_result_request", null);
		prof.Set(5401, "sc_spellsRes_info_request", null);
		prof.Set(18001, "sc_task_info_request", null);
		prof.Set(18002, "sc_task_update_request", null);
		prof.Set(29003, "sc_teachers_graduation_request", null);
		prof.Set(29001, "sc_teachers_info_request", null);
		prof.Set(29004, "sc_teachers_message_add_request", null);
		prof.Set(29002, "sc_teachers_update_request", null);
		prof.Set(17001, "sc_team_info_request", null);
		prof.Set(17002, "sc_team_list_request", null);
		prof.Set(17003, "sc_team_one_request", null);
		prof.Set(5001, "sc_template_init_data_request", null);
		prof.Set(5002, "sc_template_update_data_request", null);
		prof.Set(5301, "sc_tiannv_equip_request", null);
		prof.Set(5303, "sc_tiannv_wash_replace_res_request", null);
		prof.Set(5302, "sc_tiannv_wash_res_request", null);
		prof.Set(5501, "sc_tianshen_info_request", null);
		prof.Set(5502, "sc_tianshen_spells_info_request", null);
		prof.Set(6201, "sc_totems_info_request", null);
		prof.Set(15001, "sc_vein_update_request", null);
		prof.Set(21001, "sc_vip_update_data_request", null);
		prof.Set(6002, "sc_vipboss_base_list_request", null);
		prof.Set(6003, "sc_vipboss_update_one_request", null);
		prof.Set(131, "sc_welcome_request", null);
		prof.Set(31006, "sc_welfare_bonus_add_request", null);
		prof.Set(31050, "sc_welfare_info_request", null);
		prof.Set(31011, "sc_welfare_login_gift_info_request", null);
		prof.Set(31001, "sc_welfare_signin_info_request", null);
		prof.Set(5103, "sc_wing_equip_request", null);
		prof.Set(5101, "sc_wing_upgrade_level_request", null);
		prof.Set(5102, "sc_wing_upgrade_skill_request", null);
		prof.Set(701, "sc_xianlv_init_request", null);
		prof.Set(117, "show_server_tip_request", null);
		prof.Set(112, "stop_move_entity_request", null);
		prof.Set(108, "sub_role_att_change_request", null);
		prof.Set(102, "sub_roles_request", null);
		prof.Set(113, "sync_entity_pos_request", null);
	}

}