// Generated by sprotodump. DO NOT EDIT!

namespace Sproto { 
	export class cs_skill_sort_release_request {
		public skills: number[]; // tag 0
	}

	function _decode_cs_skill_sort_release_request(d: SprotoTypeDeserialize) {
		let o = new cs_skill_sort_release_request;
		let t = -1;
		while (-1 != (t = d.rt())) {
			switch (t) {
			case 0:
				o.skills = d.ria ();
				break;
			default:
				d.nod ();
				break;
			}
		}
		return o
	}

	function _encode_cs_skill_sort_release_request(self: cs_skill_sort_release_request, st: Sproto.SprotoStream) {
		let se = SprotoCore.GetSerialize(st, 1);

		if (self.skills != undefined) {
			se.wia (self.skills, 0);
		}

		return SprotoCore.CloseSerialize(se);
	}

	ALL_DICT["cs_skill_sort_release_request"] = {en: _encode_cs_skill_sort_release_request, de: _decode_cs_skill_sort_release_request}
	export class cs_skill_upgrade_request {
		public skillID: number; // tag 0
	}

	function _decode_cs_skill_upgrade_request(d: SprotoTypeDeserialize) {
		let o = new cs_skill_upgrade_request;
		let t = -1;
		while (-1 != (t = d.rt())) {
			switch (t) {
			case 0:
				o.skillID = d.ri ();
				break;
			default:
				d.nod ();
				break;
			}
		}
		return o
	}

	function _encode_cs_skill_upgrade_request(self: cs_skill_upgrade_request, st: Sproto.SprotoStream) {
		let se = SprotoCore.GetSerialize(st, 1);

		if (self.skillID != undefined) {
			se.wi (self.skillID, 0);
		}

		return SprotoCore.CloseSerialize(se);
	}

	ALL_DICT["cs_skill_upgrade_request"] = {en: _encode_cs_skill_upgrade_request, de: _decode_cs_skill_upgrade_request}
	export class cs_skill_upgrade_all_request {
	}

	function _decode_cs_skill_upgrade_all_request(d: SprotoTypeDeserialize) {
		let o = new cs_skill_upgrade_all_request;
		let t = -1;
		while (-1 != (t = d.rt())) {
			switch (t) {
			default:
				d.nod ();
				break;
			}
		}
		return o
	}

	function _encode_cs_skill_upgrade_all_request(self: cs_skill_upgrade_all_request, st: Sproto.SprotoStream) {
		let se = SprotoCore.GetSerialize(st, 0);

		return SprotoCore.CloseSerialize(se);
	}

	ALL_DICT["cs_skill_upgrade_all_request"] = {en: _encode_cs_skill_upgrade_all_request, de: _decode_cs_skill_upgrade_all_request}
}

