var RES_REF = {
    "ActivityRewardShowPanel": ["ui_hddt_bm_jiuchongtianBG"],
    "PlayerInfoSkin": ["ui_bh_icon_VIP", "chongzhi_json", "boss_json"],
    "FuliGoldTreeSkin": ["xiyoulilian_json", "js_json", "ui_fldt_bt_bj", "fulidating_json"],
    "CustomServicePanelSkin": ["ui_fk_banner"],
    "ReferrerSkin": ["haoyou_json"],
    "FeatsShopItem": ["shangcheng_json"],
    "TreasureBaseIconSkin": ["jineng_json"],
    "briberyItem": ["hongbao_json"],
    "GangMemberListItemSkin": ["guankia_json"],
    "DeityEquipMainSkin": ["shenzhuang_json"],
    "TsumKoBaseMemberSkin": ["shenjiang_json"],
    "PetInfoSkin": ["chongwu_json", "tujian_json", "ui_skill_31"],
    "BtnTab5Skin": ["yunyinghuodong_json"],
    "FuliSignBoardSkin": ["ui_fldt_bm_qiandaoBanner", "fuben_json"],
    "DailyFomalhautMainSkin": ["ui_smrw_bm_yuanhua", "zuoqi_json"],
    "NpcDialogSkin": ["npc_800001"],
    "ChatFaceSkin": ["faceIcon_json", "wanjiaxiangqing_json"],
    "KaiFuJiJieBtnSkin": ["jineng_json"],
    "GBattleGangRankItemSkin": ["chongwu_json"],
    "ForgeEquipSkin": ["duanzao_json"],
    "YingYuanZhengShuSkin": ["yinyuan_json"],
    "GBattleGateSkin": ["zd_json", "ui_kfbz_bm_yuanhua", "huodongdating_json", "kuafuboss_json", "ui_kfbz_bm_jiangliBG", "kuafubangzhan_json"],
    "StudentSkin": ["fuben_json"],
    "CangbaotuPopSkin": ["fuben_json"],
    "RoleHeadSkin": ["boss_json"],
    "GodPetActiveTipSkin": ["chongwu_json"],
    "PageButtonSkin": ["paihangbang_json"],
    "briberyOpenSkin": ["ui_hb_bm_hongbao02", "hongbao_json"],
    "XiandaoSceneSkin": ["zd_json", "banghui_json"],
    "GodPetActiveLotterySkin": ["ui_ssjl_bm_tupian01", "ui_ssjl_bm_bg", "shenshoujianglin_json"],
    "CmLabel3Skin": ["name_bg_json"],
    "DailyTeamSkin": ["zuoqi_json", "ui_xyll_bm_kuafuzudui"],
    "GangProtectorAwarkListItemSkin": ["guankia_json"],
    "GameBattleSelectSkin": ["zd_json"],
    "TreasureResultSkin": ["xunbao_json"],
    "KaiFuJiJieShopItemSkin": ["jinjiekuanghuan_json", "shangcheng_json"],
    "OpenDayGifItemSkin": ["denglusongyuanbao_json", "fuben_json"],
    "FieldBossSkin": ["zd_json", "boss_json", "name_bg_json"],
    "FriendMainSkin": ["haoyou_json"],
    "FuliLvNoticeSkin": ["ui_fldt_bm_gonggaoBanner"],
    "RoleSuitSkin": ["js_json", "name_bg_json", "jineng_json", "taozhuang_json", "chibang_json"],
    "OpenDayGifSkin": ["denglusongyuanbao_json", "fuben_json"],
    "FuliWeeklyCardSkin": ["ui_fldt_bm_zhoukaBanner", "qujingdonggui_json", "fulidating_json"],
    "MainPlayerInfoSkin": [],
    "FuliBtnSkin": ["jineng_json", "fulidating_json"],
    "QujingRecordListItemSkin": ["qujingdonggui_json"],
    "XiandaoRankItemSkin": ["chongwu_json"],
    "FateFadeViewSkin": ["js_json", "ui_zd_bm_taizi"],
    "DailyResRetrieveSkin": [],
    "briberySkin": ["hongbao_json", "ui_hb_bm_hongbao01"],
    "LadderLevelSkin": ["kuafuwangzhe_json"],
    "ItemAuctionTipsSkin": [],
    "GodPetActiveAwardSkin": ["ui_ssjl_bm_tupian02", "huodongdating_json", "shangcheng_json"],
    "WorldMapContentSkin": ["shijieditu_json", "fuben_json"],
    "AnswerSkin": ["dati_json", "ui_dt_bm_bg", "banghui_json"],
    "UpLvWayMainSkin": ["dati_json", "shengjitujing_json"],
    "XianlvAttrSkin": ["name_bg_json"],
    "GodLotterySkin": ["ui_ts_bm_tupian", "tianshenjianglin_json", "ui_ts_bm_bg"],
    "KaiFuTargetFightPanelSkin": ["chibang_json", "fuben_json", "guankia_json"],
    "GrowUpItemSkin": ["fuben_json"],
    "XiandaoVideoSkin": ["xiandaohui_json", "boss_json"],
    "ChatSkin": [],
    "PetInactiveSkin": ["shenjiang_json", "tujian_json", "chongwu_json", "ui_skill_31"],
    "TianShenHeChengItemSkin": ["shenjiang_json"],
    "TianShenGmSkin": [],
    "XianlvupStarSkin": ["xianlv_json", "name_bg_json", "chongwu_json", "ui_skill_31"],
    "CaiLiaoItem": ["fuben_json"],
    "RideItemSkin": [],
    "PetHeadSkin": ["chongwu_json"],
    "RoleSkillSetSkinItemSkin": ["jineng_json"],
    "ForgeGemSkin": [],
    "RechargeRebateSkin": ["chongzhifanli_json", "chongzhi_json"],
    "XiandaoRankItem2Skin": ["xiandaohui_json"],
    "GangMapSceneSkin": ["zuoqi_json", "zd_json", "banghui_json", "chongwu_json"],
    "HouseDetailSkin": ["fangwu_json"],
    "SystemSettingSkin": ["youjian_json"],
    "CrossBattleItemSkin": ["boss_json"],
    "CommonDialogSkin": [],
    "Btn2Skin": ["zd_json"],
    "DailyFirstChargeSkin": ["ui_yyhd_bm_meirishouchongBG"],
    "FansSkin": ["haoyou_json"],
    "MainGameNoticeSkin": ["xiandaohui_json"],
    "TsumKoListItemSkin": ["qujingdonggui_json", "ui_bsyn_bm_ditu01", "bashiyinan_json"],
    "LadderInfoHeadItemSkin": ["kuafuwangzhe_json"],
    "BagMakeListSkin": [],
    "BossTipsItemSkin": ["chongwu_json"],
    "ShopIntegralItemSkin": ["shangcheng_json"],
    "PlotLeftMsgSkin": ["plot_json"],
    "GangMemberInfoSkin": ["ui_bh_icon_VIP", "chongzhi_json", "guankia_json"],
    "TianShenHeChengSkin": ["shenjiang_json"],
    "GBattleRankItemSkin": ["chongwu_json"],
    "KaiFuTargetPanelSkin": ["jineng_json"],
    "GangMineKuangItemSkin": ["huodongdating_json"],
    "PowerLabel3Skin": ["js_json"],
    "XianlvSkillTipSkin": ["chongwu_json", "ui_skill_31"],
    "TopActivitySkin": ["ui_bm_xuannvxiafan"],
    "XiandaoRankSkin": ["chongwu_json", "xiandaohui_json"],
    "XiandaoSkin": ["xiandaohui_json"],
    "TotemsActivationModelSkin": ["youjian_json", "tuteng_json"],
    "RankDataItemSkin": ["chongwu_json"],
    "RechargeRebateMainSkin": ["jineng_json", "fulidating_json"],
    "DestinyEquipDlgSkin": [],
    "RoleInfoItemSkin": ["js_json"],
    "DestinyArrTipSkin": [],
    "FuliGiveGoldMainSkin": ["ui_yyhd_bm_songshiwanyuanbaoBG", "fuben_json", "qujingdonggui_json"],
    "GBRoleHeadSkin": ["kuafubangzhan_json"],
    "LadderLevelNameSkin": ["kuafuwangzhe_json"],
    "TreasureMakeRectSkin": ["ui_fb_bm_bg", "fabao_json"],
    "zhuangPanItemSkin": ["jinjiekuanghuan_json", "shangcheng_json"],
    "HavingLockItemSkin": ["xianlv_json"],
    "RoleInfoSkin": ["js_json"],
    "PetGodQualitySkin": ["js_json", "chongwu_json", "tujian_json", "ui_skill_31"],
    "HeadSkin": ["boss_json"],
    "TianShenLevelUpSkin": ["shenjiang_json", "zuoqi_json", "name_bg_json", "chongwu_json"],
    "CangbaotuRewardSkin": ["name_bg_json", "fuben_json"],
    "welComeLandingSkin": ["ui_xsyd_bg"],
    "ResultFailSkin": ["jineng_json", "jiesuan_json"],
    "YuanfenTipSkin": ["chongwu_json"],
    "FuliPracticeSkin": ["fuben_json", "xiyoulilian_json", "zuoqi_json", "ui_fldt_bm_fuliBanner", "fulidating_json"],
    "YingyueEnAiSkin": ["yinyuan_json", "huodongdating_json", "shangcheng_json"],
    "DailyExpRetrieveItemSkin": ["chongwu_json"],
    "TeacherSecendSkin": ["shitu_json", "chongwu_json"],
    "RoleHead1Skin": ["xiandaohui_json", "boss_json"],
    "PositionForeshowSkin": ["name_bg_json", "ui_zwgnt_bm_bj", "zhenweigongneng_json", "jiesuan_json", "ui_skill_31", "chongwu_json"],
    "LadderRankPanelSkin": ["kuafuwangzhe_json"],
    "ForgeSkin": ["ui_bm_duanzaowenli", "duanzao_json"],
    "GangMineRankSkin": [],
    "EquipUserTipsSkin": ["tips_json"],
    "DestinyRectInfoSkin": ["zd_json"],
    "FuliActivationCodeSkin": ["ui_fldt_bm_jihuomaBanner"],
    "KaiFuTargetUpLevelPanelSkin": ["ui_kfhd_bm_dengjiBanner", "fuben_json"],
    "ActivityEndAwardIconSkin": ["banghui_json"],
    "InvestmentPlanItemSkin": ["fuben_json"],
    "HavingMagicSkin": ["tiannv_json", "skill_0_3"],
    "TreasureArrRectInfo": ["zd_json"],
    "RoleTemplateRewardSkin": ["ui_jjjl_bg", "fuben_json"],
    "GodPetActiveResultSkin": ["xunbao_json"],
    "CloudNineRankItemSkin": ["ui_ch_bm_xiandaozhizun"],
    "GangMineMyTeamPanelSkin": ["shenjiang_json", "boss_json"],
    "DestinyResolveSkin": ["chongwu_json"],
    "FriendBlacklistSkin": ["haoyou_json"],
    "GuaQiaRankItemSkin": ["chongwu_json"],
    "WorldMapSkin": ["shijieditu_json", "fuben_json"],
    "TeacherFirstSkin": ["shitu_json", "chongwu_json"],
    "DestinyResolveHandleDlgSkin": [],
    "GangApplyListSkin": ["guankia_json"],
    "GangMineRoleItemSkin": ["zuoqi_json"],
    "CommonWindowBgSkin": ["js_json"],
    "DayBtnSkin": ["qitianzunxiang_json"],
    "GangMineCrossRankSkin": ["ui_hddt_bm_kszdpaimingBG"],
    "CloudNineRankSkin": ["ui_hddt_bm_jiuchongtianpaimingBG", "ui_ch_bm_xiandaozhizun"],
    "XianlvAllAttrSkin": ["name_bg_json"],
    "LingtongSkillSkin": ["name_bg_json", "chongwu_json", "ui_skill_31"],
    "TsumKoBaseRecordSkin": ["youjian_json", "name_bg_json", "bashiyinan_json"],
    "HouseUpgradeTipSkin": ["chongwu_json"],
    "TreasureUpPanelSkin": ["duanzao_json", "zd_json", "jineng_json", "chongwu_json"],
    "FuliMonthlyCardSkin": ["ui_fldt_bm_yuekaBanner", "qujingdonggui_json", "fulidating_json"],
    "KaiFuTargetShopItemSkin": ["jinjiekuanghuan_json", "shangcheng_json"],
    "ShopResolveSkin": ["duanzao_json"],
    "YingYuanXianHuaSkin": [],
    "YuanfenItemSkin": ["shenjiang_json", "js_json"],
    "RoleSkillItemSkin": ["jineng_json"],
    "YingYuanZjmSkin": ["boss_json"],
    "XianlvupAttrSkin": ["xianlv_json"],
    "GangJuanXianListItemSkin": ["guankia_json"],
    "CommonDialog2Skin": [],
    "XianlvUpLevelSkin": ["shenjiang_json", "zuoqi_json", "xianlv_json", "name_bg_json", "chongwu_json"],
    "TeacherSendSkin": ["ui_st_bm_chuangongBG"],
    "UpLvWayItemSkin2": ["shengjitujing_json"],
    "PlayerChangeNameSkin": [],
    "RoleSkillSkin": ["jineng_json", "ui_bm_jinengwenli"],
    "MoneyTreeBoxSkin": [],
    "LingLongTaSkin": ["fuben_json", "ui_fb_bm_linglongbaotabg"],
    "TheFirstPlayerTipSkin": ["ui_zjm_mobaiBG"],
    "ChangeLinerSkin": ["chongwu_json"],
    "KaiFuJiJieRankItemSkin": ["chongwu_json"],
    "GangCreateSkin": [],
    "MailContentSkin": ["youjian_json"],
    "AcrossBossSkin": ["name_bg_json", "ui_kf_bm_beijingBG", "kuafubangzhan_json"],
    "GangMapTaskResetTipSkin": [],
    "KaiFuJiJieAwardItemSkin": ["fuben_json"],
    "TiantiRankItem": ["kuafuwangzhe_json"],
    "TianshilianItemSkin": ["fuben_json"],
    "GodPieWinSkin": ["jineng_json", "fulidating_json"],
    "TsumKoPanelSkin": ["bashiyinan_json", "qujingdonggui_json", "ui_bsyn_bm_ditu01"],
    "BagItemTypeSkin": [],
    "TsumKoCheckItemListSkin": ["shenjiang_json", "bashiyinan_json"],
    "GBattleJoinTipSkin": ["banghui_json"],
    "GangMineRankItemSkin": [],
    "HavingSkillIconSkin": ["jineng_json", "chongwu_json"],
    "KaiFuTargetShopSkin": ["ui_kfhd_bm_zhekouBanner", "jinjiekuanghuan_json", "shangcheng_json"],
    "HouseUpgradeTipItemSkin": ["chongwu_json"],
    "TsumKoBaseBagItemSkin": [],
    "TreasureHoldIconSkin": ["jineng_json", "chongwu_json"],
    "PublicBossItemSkin": ["zd_json", "boss_json", "name_bg_json"],
    "ChatItem1Skin": ["wanjiaxiangqing_json", "boss_json"],
    "MapCitySkin": ["ui_hddt_bm_wangcheng", "boss_json"],
    "CrossBattleJfViewSkin": ["huodongdating_json", "shangcheng_json", "vip_json"],
    "zhuangPanPanelSkin": ["zuoqi_json", "jingcaihuodong_json", "ui_jchd_bm_zhuanpan02"],
    "FuliForeverCardSkin": ["qujingdonggui_json", "ui_fldt_bm_zskbanner", "fulidating_json"],
    "DailyPeaceItemSkin": ["fuben_json"],
    "KillBossItemSkin": ["chongwu_json"],
    "bar0Skin": ["zd_json"],
    "CommonFuHuSkin": [],
    "PublicBossSkin": ["zd_json", "boss_json", "name_bg_json"],
    "RoleTemplateSkin": ["zuoqi_json", "name_bg_json"],
    "YingyueInfoSkin": ["yinyuan_json", "fuben_json", "ui_yy_bm_huenliBG", "name_bg_json", "ui_yy_bm_qiuhuenBG", "banghui_json", "xiandaohui_json", "boss_json"],
    "AuctionSelectSkin": ["paimaihang_json"],
    "AcrossBossMiniRankSkin": ["jineng_json", "boss_json"],
    "ShopTitle": ["shangcheng_json"],
    "RideDressItemSkin": ["chibang_json"],
    "XiandaoBetTipSkin": [],
    "PetSkillIcon2Skin": ["ui_skill_31", "chongwu_json"],
    "GBattleDragonSceneSkin": ["ui_bm_tiaozhan", "huodongdating_json", "zd_json", "kuafubangzhan_json", "kuafuboss_json"],
    "TianShenMainSkin": ["js_json", "chongwu_json"],
    "YingyueEnAiItemSkin": ["yinyuan_json", "huodongdating_json", "shangcheng_json"],
    "BossKillRecordSkin": ["chongwu_json"],
    "TeamCheckItemListSkin": ["shenjiang_json", "bashiyinan_json"],
    "HavingTipsSkin": ["xuannvchuzhan_json", "ui_xncz_bm_renwu", "ui_xncz_bm_tupian"],
    "BossHurtItemSkin": ["chongwu_json"],
    "RankWinSkin": ["chongwu_json"],
    "TeacherGetReItemSkin": ["shitu_json", "chongwu_json"],
    "PlayerChatSkin": ["dati_json", "wanjiaxiangqing_json"],
    "VipBossItemSkin": ["boss_json", "name_bg_json"],
    "GangProtectorAwardListSkin": ["guankia_json"],
    "LingtongInactiveSkin": ["lingtong_json", "name_bg_json", "ui_skill_31", "chongwu_json"],
    "YingYuanAddSkin": [],
    "TeamBaseSkin": ["name_bg_json"],
    "CrossBattleMainSkin": ["huodongdating_json"],
    "BagStarTypeSkin": [],
    "QujingRecordListSkin": ["qujingdonggui_json"],
    "TeacherInvItemSkin": ["guankia_json", "chongwu_json"],
    "GangChangeNameSkin": [],
    "PetTuJianItemSkin": ["tujian_json", "chongwu_json"],
    "KaiFuJiJieRankPanelItemSkin": ["jinjiekuanghuan_json"],
    "GangMapExchangItemSkin": ["chongwu_json"],
    "DestinySkin": ["mingge_json", "chongwu_json", "duanzao_json"],
    "KaiFuJiJieRankPanelSkin": ["jinjiekuanghuan_json"],
    "YingYuanHeliSkin": ["boss_json", "shangcheng_json"],
    "GBattleEnterTempleTipSkin": ["kuafubangzhan_json"],
    "HouseUpgradeSkin": ["zuoqi_json", "fangwu_json", "name_bg_json"],
    "PetTuJianSkin": ["tujian_json", "chongwu_json"],
    "TreasureSkillDescSkin": ["chongwu_json"],
    "CrossBattleChargeSkin": ["huodongdating_json"],
    "TsumKoBaseSkin": ["name_bg_json", "bashiyinan_json"],
    "MiniMapCityInfoSkin": ["ui_hddt_bm_wangcheng"],
    "RankingKeyItemSkin": ["paihangbang_json"],
    "TianshilianPopSkin": ["name_bg_json", "zd_json", "fuben_json"],
    "GangMineTeamPanelSkin": ["shenjiang_json", "huodongdating_json"],
    "RoleSuitItemSkin": ["taozhuang_json"],
    "TotemsInfoSkin": ["name_bg_json", "vip_json", "chongwu_json"],
    "KaiFuTargetGuanQiaItmeSkin": ["fuben_json"],
    "TotemsMainSkin": ["vip_json", "js_json", "jineng_json", "name_bg_json", "chongwu_json", "ui_tt_bm_yuanquan"],
    "GainNewImageSkin": ["js_json", "ui_zd_bm_taizi"],
    "GangJuanXianListSkin": ["name_bg_json", "guankia_json"],
    "zhuangPanResultSkin": ["xunbao_json"],
    "YingYuanHeLiItemSkin": ["shangcheng_json"],
    "XianlvInactiveSkin": ["shenjiang_json", "xianlv_json", "name_bg_json", "chongwu_json"],
    "CreateRolSkin": ["chuangjue_json", "ui_cjjs_bm_ditu"],
    "FormationSkillSkin": ["name_bg_json", "zuoqi_json", "chongwu_json", "ui_skill_31"],
    "DeityEquipDetailSkin": ["chongwu_json", "tips_json"],
    "GangMemberListSkin": ["guankia_json", "banghui_json"],
    "TreasureShowSkin": ["fabao_json"],
    "CaiLiaoItemSkin": ["fuben_json"],
    "bar4Skin": ["zd_json"],
    "InvestmentPlanPanelSkin": ["ui_yyhd_bm_touzijihuaBG", "yunyinghuodong_json", "fuben_json"],
    "ChatItem2Skin": ["wanjiaxiangqing_json", "boss_json"],
    "XiandaoApplySkin": ["xiandaohui_json", "boss_json"],
    "GwHeadSkin": ["boss_json"],
    "BtnN7Skin": ["chongzhitehui_json"],
    "KaiFuTargetFuncTargetSkin": ["ui_kfhd_bm_banner", "fuben_json"],
    "QujingEscortItemSkin": ["qujingdonggui_json"],
    "RechargeItemSkin": ["chongzhi_json"],
    "GameCityPanelSkin": ["ui_zc_bm_shenmishangdian", "ui_zc_jz_boss", "ui_zc_jz_jingji", "ui_zc_jz_kuafu", "ui_zc_jz_huodong", "ui_zc_jz_ditu", "ui_zc_bt_szzp", "ui_zc_jz_fuben", "ui_bm_xuannvxiafan", "ui_bm_zjm_songxuannv"],
    "RideDressSkin": ["chibang_json", "zuoqi_json"],
    "AuctionPanelSkin": ["paimaihang_json"],
    "GangMinePanelSkin": ["huodongdating_json", "ui_hddt_bm_wakuangBG", "name_bg_json"],
    "UpLvWayItemSkin": ["shengjitujing_json"],
    "MiniMapSkin": ["huodongdating_json"],
    "TreasureResolvePanelSkin": ["chongwu_json", "jineng_json"],
    "ResultBossWinSkin": ["ui_bm_shengli", "jiesuan_json"],
    "CrossBattleJfItemSkin": ["huodongdating_json", "shangcheng_json", "vip_json"],
    "XiandaoBetSkin": ["xiandaohui_json", "boss_json"],
    "TeacherThird": ["guankia_json", "chongwu_json"],
    "TsumKoCheckpointItemSkin": ["shenjiang_json", "bashiyinan_json"],
    "VipBossSkin": ["boss_json", "name_bg_json"],
    "RankingWinSkin": ["paihangbang_json", "chongwu_json", "js_json"],
    "QujingRevengeSkin": [],
    "TestSkin": [],
    "CrossBattleTipSkin": ["tips_json"],
    "TreasureArrSkin": ["tips_json"],
    "ShopMysterySkin": ["shangcheng_json"],
    "GangBossPanelSkin": ["name_bg_json", "ui_kf_bm_beijingBG", "kuafubangzhan_json"],
    "GangMapTaskItemSkin": ["zd_json"],
    "ActivityTipSkin": [],
    "AreanPKResultSkin": ["banghui_json", "jingjichang_json", "ui_bm_shengli", "jiesuan_json"],
    "GodPetActiveAwardItemSkin": ["huodongdating_json", "shangcheng_json"],
    "TeacherItemInfoSkin": ["shitu_json", "boss_json"],
    "CrossBattleCityInfomaTionSkin": ["boss_json"],
    "PetUpLevelSkin": ["shenjiang_json", "name_bg_json", "zuoqi_json", "tujian_json", "chongwu_json", "ui_skill_31"],
    "FieldBossItemSkin": ["zd_json", "boss_json", "name_bg_json"],
    "DetailsChatSkin": ["wanjiaxiangqing_json"],
    "bar3Skin": ["zd_json"],
    "XianlvupSkin": ["xianlv_json", "name_bg_json", "chongwu_json", "ui_skill_31"],
    "GBattleScoreItemSkin": ["huodongdating_json", "shangcheng_json", "vip_json"],
    "KaiFuQiTianFuLiPanelSkin": ["fuben_json"],
    "XiandaoKnockoutSkin": ["xiandaohui_json", "ui_xdh_bm_xian", "boss_json"],
    "DailyExpRetrieveSkin": ["chongwu_json"],
    "HavingSkillTipSkin": [],
    "GangRecordListSkin": ["chongwu_json"],
    "FateMainSkin": ["name_bg_json"],
    "TeamMemberItemSkin": ["shenjiang_json", "boss_json"],
    "GBattleRankSkin": ["chongwu_json"],
    "zhuangPanShopSkin": ["ui_jjkh_bm_wenbenBG", "jinjiekuanghuan_json", "shangcheng_json"],
    "GangDefendPanelSkin": ["banghui_json", "name_bg_json", "duanzao_json", "guankia_json", "chongwu_json"],
    "PetXilianTipSkin": [],
    "LadderWinnerSkin": ["ui_kfwz_bm_bj", "banghui_json"],
    "PlotRightMsgSkin": ["plot_json"],
    "TeamBaseMemberSkin": ["shenjiang_json", "boss_json"],
    "LadderResultWinSkin": ["ui_bm_shengli", "kuafuwangzhe_json"],
    "KaiFuJiJieSkin": ["ui_jjkh_bm_wenbenBG", "jinjiekuanghuan_json", "fuben_json"],
    "LingtongRankSkin": ["name_bg_json", "zuoqi_json", "duanzao_json", "chongwu_json", "ui_skill_31"],
    "RechargeWinSkin": ["chongzhi_json", "vip_json", "ui_yyhd_bm_shuangbeishouchongBG"],
    "TotemsGoodLuckSkin": ["xunbao_json", "ui_xb_bm_wupinBG"],
    "ItemTipsSkin": ["tips_json"],
    "XiandaoKnockoutHeadSkin": ["boss_json"],
    "FuliGiveGoldItem": ["fuben_json", "qujingdonggui_json"],
    "DailyPeaceSkin": ["ui_xyll_bm_pingdinganbang", "fuben_json"],
    "HelpTipsSkin": ["zd_json", "tips_json"],
    "TianShenBreachSkin": ["xianlv_json", "name_bg_json", "ui_skill_31"],
    "KaiFuTargetReChargePanelSkin": ["ui_kfhd_bm_lianxuchongzhiBanner", "fuben_json"],
    "LadderRankRewardItemSkin": ["kuafuwangzhe_json"],
    "PetMainSkin": ["js_json", "chongwu_json"],
    "CrossGuildSkin": [],
    "XianlvMainSkin": ["js_json", "chongwu_json"],
    "BossHurtRankSkin": ["chongwu_json"],
    "HavingSkillItemSkin": ["jineng_json"],
    "FirstChargePanelSkin": ["fuben_json", "name_bg_json", "yunyinghuodong_json"],
    "YuanfenInfoSkin": ["shenjiang_json", "js_json"],
    "TianShenBaseSkin": ["shenjiang_json", "name_bg_json", "zuoqi_json", "chongwu_json", "jineng_json"],
    "TreasureHuntMainSkin": ["xunbao_json", "ui_xb_bm_wupinBG"],
    "DailyRetrieveCountSkin": ["xiyoulilian_json", "zuoqi_json"],
    "GangListItemSkin": ["guankia_json"],
    "GangRecordListItemSkin": ["chongwu_json"],
    "DailyAwardSkin": [],
    "RewardsWin": [],
    "PetSkillTipSkin": ["chongwu_json", "ui_skill_31"],
    "KaiFuJiJieShopPanelSkin": ["ui_jjkh_bm_wenbenBG", "jinjiekuanghuan_json", "shangcheng_json"],
    "AnswerResultSkin": ["dati_json"],
    "FuliLvGiftBagSkin": ["ui_fldt_bm_shengjiBanner", "fuben_json"],
    "QujingAwardSkin": ["qujingdonggui_json"],
    "ArenaRoleItemSkin": ["jingjichang_json"],
    "GameBattleManualSkin": ["zd_json"],
    "CaiLiaoFB": ["fuben_json"],
    "RoleJingMaiSkin": ["name_bg_json", "jingmai_json", "ui_jm_bm_jingmai"],
    "TeamDataItemSkin": ["shenjiang_json"],
    "LadderPreWeekPanelSkin": ["kuafuwangzhe_json"],
    "OfflineRewardSkin": ["lixianshouyi_json"],
    "RoleSkillSetPanelSkin": ["jineng_json"],
    "ShopRectItemSkin": ["shangcheng_json"],
    "ShopMysteryItemSkin": ["shangcheng_json"],
    "GangMineTeamGuardPanelSkin": ["shenjiang_json", "boss_json"],
    "LadderLevelIconSkin": ["kuafuwangzhe_json"],
    "TotemsMainModelSkin": ["zuoqi_json", "tuteng_json"],
    "MailItemSkin": ["youjian_json"],
    "FormationMainSkin": ["js_json"],
    "GrowUpPanelSkin": ["ui_yyhd_bm_chengzhangjijinBG", "yunyinghuodong_json", "fuben_json"],
    "GBattleScoreListSkin": ["huodongdating_json", "shangcheng_json", "vip_json"],
    "ArenaInfoSkin": ["ui_jjc_bm_ditu", "jingjichang_json"],
    "XianlvBattleSkin": ["chongwu_json"],
    "KaiFuQiTianShopItemSkin": ["jinjiekuanghuan_json", "shangcheng_json"],
    "XianlvQySkin": [],
    "KaiFuTargetTeamBuyPanelSkin": ["ui_kfhd_bm_kaifutuangouBanner", "fuben_json"],
    "RoleSuitHeadSkin": ["jineng_json", "taozhuang_json"],
    "GangApplyListItemSkin": ["guankia_json"],
    "PersonBossItemSkin": ["boss_json", "name_bg_json"],
    "BtnN4Skin": ["paihangbang_json"],
    "GameBattleSkin": ["zd_json", "fuben_json"],
    "QujingChooseItemSkin": ["qujingdonggui_json"],
    "CloudNineSceneSkin": ["huodongdating_json"],
    "CrossGuildWarSkin": [],
    "PetXilianSkillSkin": ["js_json", "chongwu_json", "jineng_json", "ui_skill_31"],
    "GangProtectorJinJieAwardSkin": [],
    "PlotSimpleSkin": ["zd_json"],
    "XianlvBaseSkin": ["xianlv_json", "name_bg_json", "chongwu_json", "ui_skill_31"],
    "ActivityRewardShowItemSkin": [],
    "WorldMapIconSkin": ["shijieditu_json", "fuben_json"],
    "ShootUpPanelSkin": ["yunyinghuodong_json", "2006709_s", "ui_yyhd_bm_zhishengyijieBG"],
    "GangMapExchangeSkin": ["chongwu_json"],
    "GodListItemSkin": [],
    "RoleRideDrugSkin": ["name_bg_json"],
    "CaiLiaoFBSkin": ["fuben_json"],
    "CmLabel2Skin": ["name_bg_json"],
    "CommonMidSkin": [],
    "XiandaoResultSkin": ["xiandaohui_json", "boss_json"],
    "TreasureRectIconSkin": ["fabao_json"],
    "TeacherSkin": ["ui_st_bm_bg", "shitu_json"],
    "CommonDialog3Skin": ["ui_yy_bm_xijielianliBG"],
    "GangInfoSkin": ["boss_json", "chongwu_json", "banghui_json"],
    "BtnTab4Skin": ["shitu_json"],
    "PetSkillSkin": ["chongwu_json", "ui_skill_31"],
    "LittleBg3": ["tips_json"],
    "PetAttrSkin": ["name_bg_json", "chongwu_json"],
    "ActivityItemSkin": ["huodongdating_json", "ui_hddt_bm_kszdBG"],
    "TreasureMakePanelSkin": ["jineng_json", "chongwu_json"],
    "ForgeMasterTipSkin": ["tips_json", "duanzao_json"],
    "KaiFuActivityPanelSkin": ["jineng_json"],
    "ShopCommonSkin": ["shangcheng_json"],
    "TeacherItemDepart": [],
    "AcrossBossFightSkin": ["zd_json", "kuafuboss_json", "jineng_json", "boss_json"],
    "RoleRideSkillSkin": ["name_bg_json", "zuoqi_json"],
    "ForgeEquipListSkin": ["ui_bm_duanzaowenli", "duanzao_json"],
    "BG": ["ui_bm_back4"],
    "ResultWinSkin": ["ui_bm_shengli", "jiesuan_json"],
    "TotemsItemComSkin": ["jineng_json", "tuteng_json"],
    "XianLvInfoSkin": ["chongwu_json", "ui_skill_31"],
    "PowerLabel2Skin": ["js_json"],
    "ActivityWinSkin": ["huodongdating_json", "ui_hddt_bm_kszdBG"],
    "DailyTaskItemSkin": ["chongwu_json"],
    "FieldBossDetailSkin": ["name_bg_json", "zd_json", "boss_json"],
    "GBattleTempleSceneSkin": ["ui_bm_tiaozhan", "huodongdating_json", "zd_json", "kuafubangzhan_json"],
    "CatchPetResultWinSkin": ["ui_bm_shengli", "jiesuan_json", "ui_zd_bm_taizi"],
    "AcivityEndAwardSkin": ["name_bg_json", "banghui_json", "jiesuan_json"],
    "TianshilianSkin": ["ui_fb_bm_yongchuangtiantingbg", "name_bg_json", "zd_json", "fuben_json"],
    "GameGattlePubBossSkin": ["zd_json"],
    "XianlvupStarBaseSkin": ["xianlv_json", "name_bg_json", "chongwu_json", "ui_skill_31"],
    "SmeltSelectSkin": [],
    "RoleTemplateRewardItemSkin": ["fuben_json"],
    "GangCreateItemSkin": ["name_bg_json", "banghui_json"],
    "HeadSkin2": ["boss_json"],
    "HeadSkin3": ["xiandaohui_json", "boss_json"],
    "CangbaotuItemSkin": ["fuben_json"],
    "RechargeRebateItemSkin": ["chongzhifanli_json", "chongzhi_json"],
    "DeityEquipInjectSkin": ["shenzhuang_json", "duanzao_json"],
    "UpLvWayViewSkin": ["xiyoulilian_json", "zuoqi_json", "fuben_json", "shengjitujing_json"],
    "bar2Skin": ["zd_json"],
    "HouseBuildSkin": ["fangwu_json"],
    "GangPangTaoHuiSkin": ["ui_bh_bm_pantaohuiyuanhua", "fuben_json"],
    "MyFriendSkin": ["haoyou_json"],
    "CrossBattleCityInfoSkin": ["boss_json"],
    "TeamItemComSkin": ["shenjiang_json", "bashiyinan_json"],
    "HavingShowSkin": ["ui_xn_bm_db", "xuannvxiafan_json", "jineng_json", "chongwu_json"],
    "TianshenDetailSkin": ["chongwu_json"],
    "BtnTab2Skin": ["paihangbang_json"],
    "GuaQiaRankSkin": ["chongwu_json"],
    "BossTipsSkin": ["chongwu_json"],
    "KaiFuJiJieRankWinSkin": ["chongwu_json"],
    "GangListSkin": ["guankia_json"],
    "RoleSuitTipSkin": ["js_json", "tips_json"],
    "RechargeFeedbackSkin": ["ui_lchk_bm_bj"],
    "DeityEquipAwakeSkin": ["shenzhuang_json", "duanzao_json"],
    "HavingCard": ["ui_bm_zjm_songxuannv"],
    "GameMapSkin": ["huodongdating_json"],
    "CatchPetResultFailSkin": ["ui_zd_bm_ku", "zd_json", "ui_zd_bm_taizi"],
    "ChatUeseItem": ["dati_json", "wanjiaxiangqing_json"],
    "KaiFuQiTianActivityPanelSkin": ["qitianzunxiang_json"],
    "FormationAllAttrSkin": ["name_bg_json"],
    "Btn1Skin": ["zd_json"],
    "BagEquipTypeSkin": [],
    "AcitivityAdvanceTips": ["ui_yg_bm_jct"],
    "RoleSuitEquipItemSkin": ["chibang_json", "taozhuang_json"],
    "ShouDaoXianHuaSkin": ["ui_yy_bm_qiuhuenBG"],
    "RechargeAwardSkin": ["ui_czth_bm_biaotou", "chongzhitehui_json", "ui_czth_bm_tupian02", "ui_czth_bm_tupian01"],
    "RoleElixirSkin": ["jineng_json", "ui_bm_jinengwenli"],
    "CityTypeSkin": ["huodongdating_json"],
    "FubenSkin": ["youjian_json"],
    "GBattleDragonGuardSkin": ["zuoqi_json"],
    "DestinyShowRectSkin": ["mingge_json", "zd_json"],
    "AuctionItemSkin": ["paimaihang_json"],
    "ConsumptionPanelSkin": ["ui_yyhd_bm_xiaofeiyouliBG", "fuben_json"],
    "LingLongTaItem": ["fuben_json", "name_bg_json"],
    "AuctionRecordPanelSkin": [],
    "CommonRewardsWin": [],
    "LingLongTaItemSkin": ["fuben_json", "name_bg_json"],
    "CrossBattleTeam": ["huodongdating_json", "shangcheng_json"],
    "VipMainSkin": ["ui_vip_bm_banner", "vip_json", "zuoqi_json", "chongzhi_json"],
    "GangMineTeamItemSkin": ["shenjiang_json", "huodongdating_json"],
    "CangbaotuSkin": ["name_bg_json", "ui_fb_bm_cangbaotubg", "fuben_json"],
    "KaiFuQiTianShopPanelSkin": ["jinjiekuanghuan_json", "shangcheng_json"],
    "BtnTab29Skin": ["kuafuwangzhe_json"],
    "warnFrameSkin": [],
    "RankingValueItemSkin": ["js_json", "paihangbang_json"],
    "ConsumptionItemSkin": ["fuben_json"],
    "DailyFomalhautTaskSkin": ["name_bg_json", "ui_smrw_bm_bg", "shimenrenwu_json"],
    "KaiFuQiTianOtherPanelSkin": ["fuben_json"],
    "PetZizhiSkin": ["name_bg_json", "zuoqi_json", "chongwu_json", "jiesuan_json"],
    "ShouDaoSkin": ["yinyuan_json", "ui_yy_bm_qiuhuenBG", "boss_json"],
    "GangSkillListSkin": ["guankia_json", "ui_bm_jinengwenli", "duanzao_json", "jineng_json"],
    "FuliMainSkin": ["jineng_json", "fulidating_json"],
    "DestinyShowSkin": ["mingge_json", "zd_json"],
    "MiniChatPanelSkin": [],
    "KaiFuLeiJiReChargePanelSkin": ["ui_jjkh_bm_wenbenBG", "jinjiekuanghuan_json", "fuben_json"],
    "RechargeProgressBarSkin": ["zuoqi_json"],
    "ShopEquipSkin": ["shangcheng_json"],
    "KaiFuTargetPowerPanelSkin": ["ui_kfhd_bm_zhanliBanner", "fuben_json"],
    "RechargeAwardBtnSkin": ["chongzhitehui_json"],
    "AcrossBossBoxSkin": ["chongzhi_json"],
    "MainPlayFunViewSkin": ["ui_yy_btn_xitie", "ui_yy_btn_xianhua", "ui_dt_bt_keju", "ui_yy_btn_qiuhuen", "ui_bm_xuannvxiafan", "ui_bm_zjm_songxuannv"],
    "ForgeMasterBtnSkin": ["duanzao_json"],
    "GameBattleBtnSkin": ["11001", "zd_json"],
    "FbRankSkin": ["fuben_json"],
    "GangDefendListItemSkin": ["guankia_json", "chongwu_json"],
    "PetXilianItemSkin": ["jineng_json", "ui_skill_31", "chongwu_json"],
    "DestinyNiSkin": ["mingge_json"],
    "TianShenInactiveSkin": ["shenjiang_json", "name_bg_json", "zuoqi_json", "chongwu_json", "jineng_json"],
    "BtnN5Skin": ["shitu_json"],
    "FormationSoulSkin": ["zuoqi_json", "name_bg_json", "duanzao_json"],
    "MainBottomPanelSkin": ["ui_bm_icombg1-46"],
    "DailyInfoSkin": ["xiyoulilian_json", "zuoqi_json", "boss_json", "chongwu_json"],
    "LingtongSkillDecsSkin": ["ui_skill_31"],
    "MailListSkin": ["youjian_json"],
    "RmbGiftPanelSkin": ["ui_yyhd_bm_shiyuanlibaoBG", "yunyinghuodong_json"],
    "FuliSignBoardItemSkin": ["fuben_json"],
    "GBattleGangRankSkin": ["chongwu_json"],
    "ShopCommonItemSkin": ["shangcheng_json"],
    "ShowPanelSkin": ["boss_json"],
    "XiandaoVideoItemSkin": ["xiandaohui_json"],
    "PetSkillIconSkin": ["ui_skill_31", "chongwu_json"],
    "ItemUseTipsSkin": [],
    "GBattleOutsiderSceneSkin": ["huodongdating_json", "kuafubangzhan_json", "boss_json"],
    "GangMineTeamRoleItemSkin": ["shenjiang_json", "boss_json"],
    "PetRenameSkin": [],
    "SmeltMainSkin": ["ui_bm_shuoming"],
    "PersonBossSkin": ["boss_json", "name_bg_json"],
    "FriendItemSkin": ["haoyou_json", "boss_json"],
    "DailyBoxSkin": ["xiyoulilian_json", "fuben_json"],
    "CrossBattleResultWinSkin": ["ui_bm_shengli", "jiesuan_json"],
    "PetTuJianItemIconSkin": ["chongwu_json"],
    "LingLongTa": ["fuben_json", "ui_fb_bm_linglongbaotabg"],
    "KaiFuQiTianAwardItemSkin": ["fuben_json"],
    "CrossBattleTeamItemSkin": ["huodongdating_json", "shangcheng_json", "boss_json"],
    "PetXilianTip2Skin": [],
    "FormationInfoSkin": ["name_bg_json", "zuoqi_json", "zhenxing_json", "chongwu_json", "ui_skill_31"],
    "DailyChargeGiftSkin": ["ui_mrhl_bm_bj"],
    "PetBattleSkin": ["chongwu_json"],
    "LastWeekRankItemSkin": ["kuafuwangzhe_json"],
    "PetAllAttrSkin": ["name_bg_json"],
    "ChestSkin": ["youjian_json"],
    "PetNameSkin": ["chongwu_json"],
    "RoleAttrSkin": ["jineng_json"],
    "GuanqiajiangliSkin": ["ui_bm_diwen", "guankia_json"],
    "TianShenBaoQiSkin": ["xianlv_json", "shenjiang_json", "name_bg_json", "zuoqi_json", "ui_sj_bm_wenli"],
    "LadderInfoPanelSkin": ["name_bg_json", "kuafuwangzhe_json", "boss_json"],
    "GameBattleBtn2Skin": ["11001", "zd_json"],
    "HavingUpLevelSkin": ["zuoqi_json", "name_bg_json", "jineng_json", "chongwu_json"],
    "EquipTipsSkin": ["tips_json"],
    "TeacherShowReItemSkin": ["chongwu_json"],
    "LingtongUpLevelSkin": ["zuoqi_json", "name_bg_json", "chongwu_json", "ui_skill_31"],
    "QujingMainSkin": ["qujingdonggui_json", "ui_qj_bm_ditu"],
};
//# sourceMappingURL=ref.js.map