var __reflect = (this && this.__reflect) || function (p, c, t) {
    p.__class__ = c, t ? t.push(c) : t = [c], p.__types__ = p.__types__ ? t.concat(p.__types__) : t;
};
var MessageDef = (function () {
    function MessageDef() {
    }
    MessageDef.postUseItemSuccess = "postUseItemSuccess";
    MessageDef.postInitActorInfo = "postInitActorInfo";
    MessageDef.LUCK_RECORD = "LUCK_RECORD";
    MessageDef.LUCK_RET_ANIM = "LUCK_RET_ANIM";
    MessageDef.LUCK_RET_SUC = "LUCK_RET_SUC";
    MessageDef.MAIN_CITY_INFO = "MAIN_CITY_INFO";
    MessageDef.CHANNEL_UPDATE_INFO = "CHANNEL_UPDATE_INFO";
    MessageDef.CHANNEL_UPDATE_LIST = "CHANNEL_UPDATE_LIST";
    //战斗相关
    MessageDef.BATTLE_TURN = "BATTLE_TURN";
    MessageDef.BATTLE_TURN_START = "BATTLE_TURN_START";
    MessageDef.RP_FORGE = "RP_FORGE";
    MessageDef.FORGE_UPDATE = "FORGE_UPDATE";
    MessageDef.FORGE_ITEM_01_UPDATE = "FORGE_ITEM_01_UPDATE";
    MessageDef.FORGE_ITEM_02_UPDATE = "FORGE_ITEM_02_UPDATE";
    MessageDef.FORGE_ITEM_03_UPDATE = "FORGE_ITEM_03_UPDATE";
    // 坐骑
    MessageDef.ROLE_RIDE_INIT = "ROLE_RIDE_INIT";
    MessageDef.ROLE_RIDE_UPDATE = "ROLE_RIDE_UPDATE";
    MessageDef.ROLE_RIDE_UPDATE_EXP = "ROLE_RIDE_UPDATE_EXP";
    MessageDef.ROLE_RIDE_UPDATE_EQUIP = "ROLE_RIDE_UPDATE_EQUIP";
    MessageDef.ROLE_RIDE_UPDATE_DRUG = "ROLE_RIDE_UPDATE_DRUG";
    // 翅膀
    MessageDef.ROLE_WING_UPDATE = "ROLE_WING_UPDATE";
    MessageDef.ROLE_WING_UPDATE_EXP = "ROLE_WING_UPDATE_EXP";
    MessageDef.ROLE_WING_UPDATE_DRUG = "ROLE_WING_UPDATE_DRUG";
    MessageDef.ROLE_WING_INIT = "ROLE_WING_INIT";
    MessageDef.ROLE_WING_UPDATE_EQUIP = "ROLE_WING_UPDATE_EQUIP";
    //称号
    MessageDef.ROLE_TITLE_UPDATE = "ROLE_TITLE_UPDATE";
    //时装
    MessageDef.ROLE_SKIN_UPDATE = "ROLE_SKIN_UPDATE";
    //丹药
    MessageDef.ROLE_ELIXIR_UPDATE = "ROLE_ELIXIR_UPDATE";
    // 宠物通灵
    MessageDef.PET_TONGL_UPDATE_EXP = "PET_TONGL_UPDATE_EXP";
    MessageDef.PET_TONGL_UPDATE_DRUG = "PET_TONGL_UPDATE_DRUG";
    MessageDef.PET_TONGL_UPDATE = "PET_TONGL_UPDATE";
    MessageDef.PET_TONGL_INIT = "PET_TONGL_INIT";
    MessageDef.PET_TONGL_UPDATE_EQUIP = "PET_TONGL_UPDATE_EQUIP";
    MessageDef.RP_BAG_PET_TONGL_EQUIP_UP = "RP_BAG_PET_TONGL_EQUIP_UP";
    // 神剑
    MessageDef.ROLE_SWORD_UPDATE_EXP = "ROLE_SWORD_UPDATE_EXP";
    MessageDef.ROLE_SWORD_UPDATE_DRUG = "ROLE_SWORD_UPDATE_DRUG";
    MessageDef.ROLE_SWORD_UPDATE = "ROLE_SWORD_UPDATE";
    MessageDef.ROLE_SWORD_INIT = "ROLE_SWORD_INIT";
    MessageDef.ROLE_SWORD_UPDATE_EQUIP = "ROLE_SWORD_UPDATE_EQUIP";
    MessageDef.RP_BAG_SWORD_EQUIP_UP = "RP_BAG_SWORD_EQUIP_UP";
    // 宠物兽魂
    MessageDef.PET_SHOUH_UPDATE_EXP = "PET_SHOUH_UPDATE_EXP";
    MessageDef.PET_SHOUH_UPDATE_DRUG = "PET_SHOUH_UPDATE_DRUG";
    MessageDef.PET_SHOUH_UPDATE = "PET_SHOUH_UPDATE";
    MessageDef.PET_SHOUH_INIT = "PET_SHOUH_INIT";
    MessageDef.PET_SHOUH_UPDATE_EQUIP = "PET_SHOUH_UPDATE_EQUIP";
    MessageDef.RP_BAG_PET_SHOUH_EQUIP_UP = "RP_BAG_PET_SHOUH_EQUIP_UP";
    // 玄女
    MessageDef.HAVING_UPDATE_EXP = "HAVING_UPDATE_EXP";
    MessageDef.HAVING_UPDATE_DRUG = "HAVING_UPDATE_DRUG";
    MessageDef.HAVING_UPDATE = "HAVING_UPDATE";
    MessageDef.HAVING_INIT = "HAVING_INIT";
    MessageDef.HAVING_SKILL_ITEM_UPDATE = "HAVING_SKILL_ITEM_UPDATE";
    // 玄女花辇
    MessageDef.HAVING_HUAN_UPDATE_EXP = "HAVING_HUAN_UPDATE_EXP";
    MessageDef.HAVING_HUAN_UPDATE_DRUG = "HAVING_HUAN_UPDATE_DRUG";
    MessageDef.HAVING_HUAN_UPDATE = "HAVING_HUAN_UPDATE";
    MessageDef.HAVING_HUAN_INIT = "HAVING_HUAN_INIT";
    MessageDef.HAVING_HUAN_UPDATE_EQUIP = "HAVING_HUAN_UPDATE_EQUIP";
    MessageDef.RP_BAG_HAVING_HUAN_EQUIP_UP = "RP_BAG_HAVING_HUAN_EQUIP_UP";
    // 玄女灵气
    MessageDef.HAVING_LINGQ_UPDATE_EXP = "HAVING_LINGQ_UPDATE_EXP";
    MessageDef.HAVING_LINGQ_UPDATE_DRUG = "HAVING_LINGQ_UPDATE_DRUG";
    MessageDef.HAVING_LINGQ_UPDATE = "HAVING_LINGQ_UPDATE";
    MessageDef.HAVING_LINGQ_INIT = "HAVING_LINGQ_INIT";
    MessageDef.HAVING_LINGQ_UPDATE_EQUIP = "HAVING_LINGQ_UPDATE_EQUIP";
    MessageDef.RP_BAG_HAVING_LINGQ_EQUIP_UP = "RP_BAG_HAVING_LINGQ_EQUIP_UP";
    // 守护
    MessageDef.ROLE_TIANX_UPDATE_EXP = "ROLE_TIANX_UPDATE_EXP";
    MessageDef.ROLE_TIANX_UPDATE_DRUG = "ROLE_TIANX_UPDATE_DRUG";
    MessageDef.ROLE_TIANX_UPDATE = "ROLE_TIANX_UPDATE";
    MessageDef.ROLE_TIANX_INIT = "ROLE_TIANX_INIT";
    MessageDef.ROLE_TIANX_UPDATE_EQUIP = "ROLE_TIANX_UPDATE_EQUIP";
    MessageDef.RP_BAG_TIANX_EQUIP_UP = "RP_BAG_TIANX_EQUIP_UP";
    // 仙侣法阵
    MessageDef.XIANLV_FZ_UPDATE_EXP = "XIANLV_FZ_UPDATE_EXP";
    MessageDef.XIANLV_FZ_UPDATE_DRUG = "XIANLV_FZ_UPDATE_DRUG";
    MessageDef.XIANLV_FZ_UPDATE = "XIANLV_FZ_UPDATE";
    MessageDef.XIANLV_FZ_INIT = "XIANLV_FZ_INIT";
    MessageDef.XIANLV_FZ_UPDATE_EQUIP = "XIANLV_FZ_UPDATE_EQUIP";
    MessageDef.RP_BAG_XIANLV_FZ_EQUIP_UP = "RP_BAG_XIANLV_FZ_EQUIP_UP";
    // 仙侣仙位
    MessageDef.XIANLV_XW_UPDATE_EXP = "XIANLV_XW_UPDATE_EXP";
    MessageDef.XIANLV_XW_UPDATE_DRUG = "XIANLV_XW_UPDATE_DRUG";
    MessageDef.XIANLV_XW_UPDATE = "XIANLV_XW_UPDATE";
    MessageDef.XIANLV_XW_INIT = "XIANLV_XW_INIT";
    MessageDef.XIANLV_XW_UPDATE_EQUIP = "XIANLV_XW_UPDATE_EQUIP";
    MessageDef.RP_BAG_XIANLV_XW_EQUIP_UP = "RP_BAG_XIANLV_XW_EQUIP_UP";
    // 灵童
    MessageDef.ROLE_LINGTONG_UPDATE_EXP = "ROLE_LINGTONG_UPDATE_EXP";
    MessageDef.ROLE_LINGTONG_UPDATE_DRUG = "ROLE_LINGTONG_UPDATE_DRUG";
    MessageDef.ROLE_LINGTONG_UPDATE = "ROLE_LINGTONG_UPDATE";
    MessageDef.ROLE_LINGTONG_INIT = "ROLE_LINGTONG_INIT";
    MessageDef.ROLE_LINGTONG_UPDATE_EQUIP = "ROLE_LINGTONG_UPDATE_EQUIP";
    MessageDef.RP_BAG_LINGTONG_EQUIP_UP = "RP_BAG_LINGTONG_EQUIP_UP";
    MessageDef.LINGTONG_UPDATE_INFO = "LINGTONG_UPDATE_INFO";
    MessageDef.LINGTONG_UPDATE_GIFT_INFO = "LINGTONG_UPDATE_GIFT_INFO";
    MessageDef.RP_LINGTONG = "RP_LINGTONG";
    MessageDef.LINGTONG_ACT_ITEM = "LINGTONG_ACT_ITEM";
    MessageDef.LINGTONG_RANK_ITEM = "LINGTONG_RANK_ITEM";
    MessageDef.LINGTONG_SKILL_ITEM = "LINGTONG_SKILL_ITEM";
    MessageDef.SEND_MSG_INFO_SUCCESS = "SEND_MSG_INFO_SUCCESS";
    MessageDef.GAME_SERVER_UPDATE_DAY = "GAME_SERVER_UPDATE_DAY";
    MessageDef.GAME_DEBLOCKING = "GAME_DEBLOCKING";
    MessageDef.SHOP_REFRESH = "SHOP_REFRESH";
    MessageDef.MINI_CHAT_PANEL_STATE = "MINI_CHAT_PANEL_STATE";
    MessageDef.YB_TURNTABLE_UPDATE = "YB_TURNTABLE_UPDATE";
    MessageDef.RAID_KILL_MONSTER_COUNT = "RAID_KILL_MONSTER_COUNT";
    MessageDef.FIND_ASSETS_UPDATE = "FIND_ASSETS_UPDATE";
    MessageDef.ACTOR_PRESTIGE_UPDATE = "ACTOR_PRESTIGE_UPDATE";
    MessageDef.LEVEL_CHANGE = "LEVEL_CHANGE";
    MessageDef.GOLD_CHANGE = "GOLD_CHANGE";
    MessageDef.SKILL_SORT_CHANGE = "SKILL_SORT_CHANGE"; //技能顺序改变
    MessageDef.INIT_ACTOR = "INIT_ACTOR";
    MessageDef.YB_CHANGE = "YB_CHANGE";
    MessageDef.BYB_CHANGE = "BYB_CHANGE";
    MessageDef.EXP_CHANGE = "EXP_CHANGE";
    MessageDef.NAME_CHANGE = "NAME_CHANGE";
    MessageDef.POWER_CHANGE = "POWER_CHANGE";
    MessageDef.SOUL_CHANGE = "SOUL_CHANGE";
    MessageDef.POWER_BOOST = "POWER_BOOST";
    MessageDef.GUANQIA_CHANGE = "GUANQIA_CHANGE";
    MessageDef.FUNC_OPEN_UPDATE = "FUNC_OPEN_UPDATE";
    MessageDef.GUILD_CONTRIB_UPDATE = "GUILD_CONTRIB_UPDATE"; //个人帮贡更新
    MessageDef.CHECK_HAVE_CAN = "CHECK_HAVE_CAN";
    MessageDef.VIP_LEVEL_CHANGE = "VIP_LEVEL_CHANGE";
    MessageDef.UPDATA_VIP_AWARDS = "UPDATA_VIP_AWARDS";
    MessageDef.UPDATA_VIP_EXP = "UPDATA_VIP_EXP";
    MessageDef.TITLE_SHOW = "TITLE_SHOW";
    MessageDef.SUB_ROLE_CHANGE = "SUB_ROLE_CHANGE";
    MessageDef.FUBEN_CHANGE = "FUBEN_CHANGE";
    // 切换到挑战副本
    MessageDef.CHALLENGE_FUBEN_CHANGE = "CHALLENGE_FUBEN_CHANGE";
    /**派发角色按钮提示 */
    MessageDef.ROLE_HINT = "ROLE_HINT";
    MessageDef.RP_ROLE_HINT = "RP_ROLE_HINT";
    /** 装备数量更新 */
    MessageDef.BAG_USER_EQUIP_COUNT_UPDATE = "BAG_USER_EQUIP_COUNT_UPDATE";
    /** 皮肤道具 */
    MessageDef.BAG_USER_SKIN_COUNT_UPDATE = "BAG_USER_SKIN_COUNT_UPDATE";
    MessageDef.BAG_USER_TITLE_COUNT_UPDATE = "BAG_USER_TITLE_COUNT_UPDATE";
    /** 橙装碎片 */
    MessageDef.BAG_USER_ORANGE_COUNT_UPDATE = "BAG_USER_ORANGE_COUNT_UPDATE";
    /** 副本数量更新 */
    MessageDef.FB_COUNT_UPDATE = "FB_COUNT_UPDATE";
    /*藏宝图*/
    MessageDef.FB_CBT_UPDATE = "FB_CBT_UPDATE";
    //藏宝图 奖励
    MessageDef.FB_CBT_UPDATE_REWARD = "FB_CBT_UPDATE_REWARD";
    //跨服boss
    MessageDef.ACROSS_BOSS = "ACROSS_BOSS";
    //世界地图
    MessageDef.WORLDMAP_LOCATETO = "WORLDMAP_LOCATETO";
    //地图类型变更
    MessageDef.MAP_TYPE_CHANGE = "MAP_TYPE_CHANGE";
    //天庭副本刷新
    MessageDef.FB_TIANTING_UPDATE = "FB_TIANTING_UPDATE";
    MessageDef.FB_REDPOINT_NOTICE = "FB_REDPOINT_NOTICE";
    /** 派发全民boss列表数据 */
    MessageDef.PUBLIC_BOSS_LIST_DATA = "PUBLIC_BOSS_LIST_DATA";
    MessageDef.PUBLIC_BOSS_RANK_UPDATE = "PUBLIC_BOSS_RANK_UPDATE";
    MessageDef.PUBLIC_BOSS_RECORD_UPDATE = "PUBLIC_BOSS_RECORD_UPDATE";
    MessageDef.PUBLIC_BOSS_RELIVE_UPDATE = "PUBLIC_BOSS_RELIVE_UPDATE";
    MessageDef.PUBLIC_BOSS_OWNER_CHNAGE = "PUBLIC_BOSS_OWNER_CHNAGE";
    /** 红包 */
    MessageDef.REDBAG_JM_DATA = "REDBAG_JM_DATA";
    MessageDef.ISHSAREDBAG = "ISHSAREDBAG";
    MessageDef.SKILL_UPGRADE = "SKILL_UPGRADE";
    /**派发技能一键升级消息 */
    MessageDef.SKILL_GREWUPALL = "SKILL_GREWUPALL";
    /* 技能一键红点提示 */
    MessageDef.RP_SKILL_UPGRADE = "RP_SKILL_UPGRADE";
    //商店购买变化
    MessageDef.SHOP_CHANGE = "SHOP_CHANGE";
    //法宝内容变化
    MessageDef.TREASURE_CHANGE = "TREASURE_CHANGE";
    MessageDef.TREASURE_UPDATE_LV = "TREASURE_UPDATE_LV";
    MessageDef.TREASURE_UPDATE_MAKE = "TREASURE_UPDATE_MAKE";
    MessageDef.TREASURE_LOCK = "TREASURE_LOCK";
    MessageDef.TREASURE_ITEM_CHANGE = "TREASURE_ITEM_CHANGE";
    MessageDef.RP_TREASURE = "RP_TREASURE";
    //灵童命格
    MessageDef.DESTINY_RP = "DESTINY_RP";
    MessageDef.DESTINY_UP_ITEM = "DESTINY_UP_ITEM";
    MessageDef.DESTINY_CHANGE = "DESTINY_CHANGE";
    MessageDef.DESTINY_SMELT = "DESTINY_SMELT";
    MessageDef.DESTINY_CLICK = "DESTINY_CLICK";
    MessageDef.DESTINY_GET_REWARD = "DESTINY_GET_REWARD";
    MessageDef.DESTINY_EQUIP_REWARD = "DESTINY_EQUIP_REWARD";
    //师徒数据变化
    MessageDef.TEACHER_CHANGE = "TEACHER_CHANGE";
    MessageDef.TEACHER_TURN = "TEACHER_TURN";
    //答题内容变化
    MessageDef.ANSWER_CHANGE = "ANSWER_CHANGE";
    //答题奖励弹窗界面数据
    MessageDef.ANSWER_REWARD = "ANSWER_REWARD";
    /**合成物品消息 */
    MessageDef.MIX_REUSLT = "MIX_REUSLT";
    //////////////////////////////////////////   背包   //////////////////////////////////////////////////////////////////////////////////////
    /** 派发删除道具 */
    MessageDef.DELETE_ITEM = "DELETE_ITEM";
    MessageDef.ADD_ITEM = "ADD_ITEM";
    MessageDef.CHANGE_ITEM = "CHANGE_ITEM";
    /********************* 组合字符串 *******************************/
    MessageDef.USER_TEMPLATE_RANK_UP_ = "USER_TEMPLATE_RANK_UP_";
    MessageDef.USER_TEMPLATE_RANK_REWARD_UPDATE_ = "USER_TEMPLATE_RANK_REWARD_UPDATE_";
    MessageDef.USER_TEMPLATE_RANK_REWARD_UPDATE_ALL___ = "USER_TEMPLATE_RANK_REWARD_UPDATE_ALL___";
    // 装备更新
    MessageDef.USER_TEMPLATE_EQUIP_UPDATE_ = "USER_TEMPLATE_EQUIP_UPDATE_";
    // 技能
    MessageDef.USER_TEMPLATE_SKILL_UPDATE_ = "USER_TEMPLATE_SKILL_UPDATE_";
    // 皮肤
    MessageDef.USER_TEMPLATE_SKIN_UPDATE_ = "USER_TEMPLATE_SKIN_UPDATE_";
    // 属性丹
    MessageDef.USER_TEMPLATE_ATTR_ITEM_UPDATE_ = "USER_TEMPLATE_ATTR_ITEM_UPDATE_";
    MessageDef.USER_TEMPLATE_UP_LEVEL_ITEM_UPDATE_ = "USER_TEMPLATE_UP_LEVEL_ITEM_UPDATE_";
    // 升阶丹
    MessageDef.USER_TEMPLATE_RANK_UPDATE_ = "USER_TEMPLATE_RANK_UPDATE_";
    // 装备更新红点
    MessageDef.RP_USER_TEMPLATE_EQUIP_UPDATE_ = "RP_USER_TEMPLATE_EQUIP_UPDATE_";
    // 其它红点
    MessageDef.RP_USER_TEMPLATE_UPDATE_ = "RP_USER_TEMPLATE_UPDATE_";
    /*************************************************************/
    /** 道具数量 */
    MessageDef.ITEM_COUNT_CHANGE = "ITEM_COUNT_CHANGE";
    MessageDef.ITEM_OTHER_COUNT_CHANGE = "ITEM_OTHER_COUNT_CHANGE";
    MessageDef.BAG_HUNT_STORE_CHANGE = "BAG_HUNT_STORE_CHANGE";
    MessageDef.BAG_VOL_ADD = "BAG_VOL_ADD";
    /** 背包格子数量变更 */
    MessageDef.BAG_ITEM_COUNT_CHANGE = "BAG_ITEM_COUNT_CHANGE";
    //熔炼成功消息
    MessageDef.BAG_DEAL_SMELT = "BAG_DEAL_SMELT";
    MessageDef.postEquipCheckList = "postEquipCheckList";
    /**派发背包数量快不足的提示*/
    MessageDef.BAG_WILL_FULL = "BAG_WILL_FULL";
    /**派发是否有可用道具提示*/
    MessageDef.BAG_HAS_ITEM_CAN_USE = "BAG_HAS_ITEM_CAN_USE";
    ////////////////////////////////////////   商店 //////////////////////////////////////////////////////////////////////////////////////
    MessageDef.SHOP_MEADAL_RESULT = "SHOP_MEADAL_RESULT";
    MessageDef.SHOP_MEADAL_BUY_RESULT = "SHOP_MEADAL_BUY_RESULT";
    MessageDef.SHOP_MYSTERY_REFRESH = "SHOP_MYSTERY_REFRESH";
    ////////////////////////////////////////   邮件 //////////////////////////////////////////////////////////////////////////////////////
    MessageDef.MAIL_DATA_CHANGE = "MAIL_DATA_CHANGE";
    MessageDef.OPEN_MAIL = "OPEN_MAIL";
    MessageDef.MAIL_GET_ITEM = "MAIL_GET_ITEM";
    /**派发装备改变 */
    MessageDef.CHANGE_EQUIP = "CHANGE_EQUIP";
    // public static CHANGE_GOD_EQUIP = "CHANGE_GOD_EQUIP"
    MessageDef.CHANGE_WING = "CHANGE_WING";
    MessageDef.DEITYEQUIP_ALL_NOTICE = "DEITYEQUIP_ALL_NOTICE";
    MessageDef.DEITYEQUIP_INIT = "DEITYEQUIP_INIT";
    MessageDef.EXPJADE_UPDATE = "EXPJADE_UPDATE";
    MessageDef.SHOW_OTHER_ACTOR = "SHOW_OTHER_ACTOR";
    MessageDef.SHOW_RANK_OTHER_ACTOR = "SHOW_RANK_OTHER_ACTOR";
    MessageDef.CHALLENGE_UPDATE_INFO = "CHALLENGE_UPDATE_INFO";
    /*橙装精炼*/
    MessageDef.ORANGE_EQUIP_UPDATE = "ORANGE_EQUIP_UPDATE";
    MessageDef.ORANGE_UPDATE_REFINE = "ORANGE_UPDATE_REFINE";
    /** 材料更新 */
    MessageDef.ORANGE_REFINE_UPDATE = "ORANGE_REFINE_UPDATE";
    MessageDef.GUILD_ROBBER_NOTICE = "GUILD_ROBBER_NOTICE";
    MessageDef.GUILD_UPDATE_NAME = "GUILD_UPDATE_NAME";
    MessageDef.GUILD_BOSS_CALL_INFO = "GUILD_BOSS_CALL_INFO";
    MessageDef.GUILD_BOSS_OPEN_INFO = "GUILD_BOSS_OPEN_INFO";
    MessageDef.GUILD_REWARD_WINNER_INFO = "GUILD_REWARD_WINNER_INFO";
    MessageDef.GUILD_REWARD_UPDATE_DISP_INFO = "GUILD_REWARD_UPDATE_DISP_INFO";
    MessageDef.RING_UPDATE_DATA = "RING_UPDATE_DATA";
    MessageDef.RING_INIT_DATA = "RING_INIT_DATA";
    MessageDef.RING_UPDATE_OPEN_DATA = "RING_UPDATE_OPEN_DATA";
    MessageDef.RING_UPDATE_TASK_DATA = "RING_UPDATE_TASK_DATA";
    MessageDef.RAID_RELIVE_TIME_GD_BOSS = "RAID_RELIVE_TIME_GD_BOSS";
    MessageDef.EGG_BROKEN_RESULT = "EGG_BROKEN_RESULT";
    MessageDef.LONG_HUN_ITEM_UPDATE = "LONG_HUN_ITEM_UPDATE";
    MessageDef.ELITE_BOSS_INIT_INFO = "ELITE_BOSS_INIT_INFO";
    MessageDef.ELITE_BOSS_ACTOR_INFO = "ELITE_BOSS_ACTOR_INFO";
    //天降馅饼  
    MessageDef.GOGPIE_UPDATE = "GOGPIE_UPDATE";
    MessageDef.CROSS_ACTIVITY_ALL_SERVER = "CROSS_ACTIVITY_ALL_SERVER";
    MessageDef.CROSS_ACTIVITY_UPDATE_DATA = "CROSS_ACTIVITY_UPDATE_DATA";
    MessageDef.CROSS_ACTIVITY_GROUP_BUY_UPDATE = "CROSS_ACTIVITY_GROUP_BUY_UPDATE";
    MessageDef.SHARE_FOCUSE_INFO = "SHARE_FOCUSE_INFO";
    //宠物
    MessageDef.PET_INIT_INFO = "PET_INIT_INFO";
    MessageDef.PET_UPATE_ZIZHI = "PET_UPATE_ZIZHI";
    MessageDef.PET_UPATE_INFO = "PET_UPATE_INFO";
    MessageDef.PET_ACTIVE = "PET_ACTIVE";
    MessageDef.PET_UPATE_EXP = "PET_UPATE_EXP";
    MessageDef.BZ_PET_INFO = "BZ_PET_INFO";
    // 宠物激活道具
    MessageDef.BAG_PET_ACT_ITEM = "BAG_PET_ACT_ITEM";
    MessageDef.RP_BAG_PET_ACT_ITEM = "RP_BAG_PET_ACT_ITEM";
    MessageDef.BAG_PET_LEVEL_ITEM = "BAG_PET_LEVEL_ITEM";
    MessageDef.BAG_PET_SKILL_ITEM = "BAG_PET_SKILL_ITEM";
    MessageDef.PET_BATTLE = "PET_BATTLE";
    MessageDef.RP_PET = "RP_PET";
    //仙侣
    MessageDef.XIANLV_ACTIVE = "XIANLV_ACTIVE";
    MessageDef.XIANLV_INIT_INFO = "XIANLV_INIT_INFO";
    MessageDef.XIANLV_UPATE_INFO = "XIANLV_UPATE_INFO";
    MessageDef.XIANLV_UPATE_BATTLE = "XIANLV_UPATE_BATTLE";
    MessageDef.XIANLV_UPATE_EXP = "XIANLV_UPATE_EXP";
    MessageDef.RP_XIANLV = "RP_XIANLV";
    MessageDef.BAG_XIANLV_ACT_ITEM = "BAG_XIANLV_ACT_ITEM";
    MessageDef.RP_BAG_XIANLV_ACT_ITEM = "RP_BAG_XIANLV_ACT_ITEM";
    MessageDef.BAG_XIANLV_RANK_ITEM = "BAG_XIANLV_RANK_ITEM";
    MessageDef.BAG_XIANLV_STAR_ITEM = "BAG_XIANLV_STAR_ITEM";
    MessageDef.WORLD_BOSS_UPDATE_BLOOD = "WORLD_BOSS_UPDATE_BLOOD";
    MessageDef.WORLD_BOSS_ATT_LIST = "WORLD_BOSS_ATT_LIST";
    MessageDef.WORLD_RANK_DATA = "WORLD_RANK_DATA";
    MessageDef.WORLD_OPEN = "WORLD_OPEN";
    //阵型
    MessageDef.FORMATION_ACTIVE = "FORMATION_ACTIVE";
    MessageDef.FORMATION_UPDATE_INFO = "FORMATION_UPDATE_INFO";
    MessageDef.FORMATION_UPDATE_EXP = "FORMATION_UPDATE_EXP";
    MessageDef.FORMATION_UPDATE_SOUL_EXP = "FORMATION_UPDATE_SOUL_EXP";
    MessageDef.FORMATION_USE_DRUG = "FORMATION_USE_DRUG";
    MessageDef.FORMATION_UPDATE_SKILL_INFO = "FORMATION_UPDATE_SKILL_INFO";
    MessageDef.FORMATION_ALL_NOTICE = "FORMATION_ALL_NOTICE";
    //取经东归
    MessageDef.QUJING_UPDATE_BASEINFO = "QUJING_UPDATE_BASEINFO";
    MessageDef.QUJING_SHOW_REWARD = "QUJING_SHOW_REWARD";
    MessageDef.QUJING_UPDATE_RECORD = "QUJING_UPDATE_RECORD";
    MessageDef.QUJING_UPDATE_ESCORTLIST = "QUJING_UPDATE_ESCORTLIST";
    MessageDef.QUJING_SHOW_ROBVIEW = "QUJING_SHOW_ROBVIEW";
    MessageDef.QUJING_ROBBEDFLAG_CHANGE = "QUJING_ROBBEDFLAG_CHANGE";
    //帮会
    MessageDef.GANG_INIT = "GANG_INIT";
    MessageDef.GANG_UPDATE_LIST = "GANG_UPDATE_LIST";
    MessageDef.GANG_UPDATE_APPLIED_LIST = "GANG_UPDATE_APPLIED_LIST";
    MessageDef.GANG_UPDATE_BASE_INFO = "GANG_UPDATE_BASE_INFO";
    MessageDef.GANG_UPDATE_APPLICANT_LIST = "GANG_UPDATE_APPLICANT_LIST";
    MessageDef.GANG_UPDATE_PANTAOINFO = "GANG_UPDATE_PANTAOINFO";
    MessageDef.GANG_CHANGE_NAME = "GANG_CHANGE_NAME";
    MessageDef.GANG_SKILL_UP = "GANG_SKILL_UP";
    MessageDef.GANG_SKILL_LEARN_UP = "GANG_SKILL_LEARN_UP";
    MessageDef.GANG_UPDATE_MEMBER_LIST = "GANG_UPDATE_MEMBER_LIST";
    MessageDef.GANG_UPDATE_MEMBER_INFO = "GANG_UPDATE_MEMBER_INFO";
    MessageDef.GANG_EXIT_NOTICE = "GANG_EXIT_NOTICE";
    MessageDef.GANG_UPDATA_RECORD = "GANG_UPDATA_RECORD";
    MessageDef.GANG_UPDATA_PROTECTOR_INFO = "GANG_UPDATA_PROTECTOR_INFO";
    MessageDef.GANG_UPDATA_PROTECTOR_TASK_INFO = "GANG_UPDATA_PROTECTOR_TASK_INFO";
    MessageDef.GANG_UPDATA_GANG_BOSS_INFO = "GANG_UPDATA_GANG_BOSS_INFO";
    MessageDef.GANGMAP_ONEKEYFINISH = "GANGMAP_ONEKEYFINISH";
    MessageDef.GANG_UPDATE_FBCOUNT = "GANG_UPDATE_FBCOUNT";
    MessageDef.GANG_UPDATE_CONTRIBUTECOUNT = "GANG_UPDATE_CONTRIBUTECOUNT";
    MessageDef.GANG_ID_CHANGE = "GANG_ID_CHANGE";
    MessageDef.GANG_ALL_NOTICE = "GANG_ALL_NOTICE";
    //帮会地图
    MessageDef.GANGMAP_MAPENTITY_INIT = "GANGMAP_MAPENTITY_INIT";
    MessageDef.GANGMAP_UPDATE_TASKINFO = "GANGMAP_UPDATE_TASKINFO";
    MessageDef.GANGMAP_UPDATE_EXCHANGEINFO = "GANGMAP_UPDATE_EXCHANGEINFO";
    MessageDef.GANGMAP_UPDATE_UPDATEENTITY = "GANGMAP_UPDATE_UPDATEENTITY";
    MessageDef.GANGMAP_START_PICKPLANT_NOTICY = "GANGMAP_START_PICKPLANT_NOTICY";
    MessageDef.GANGMAP_AUTO_TASK = "GANGMAP_AUTO_TASK";
    MessageDef.GANGMAP_RESET_MAPENTITY = "GANGMAP_RESET_MAPENTITY";
    MessageDef.GANGMAP_HIDEPICKPROGRESS = "GANGMAP_HIDEPICKPROGRESS";
    //帮会boss
    MessageDef.GANGBOSS_DEAD = "GANGBOSS_DEAD";
    MessageDef.GANGBOSS_RANK_NOW = "GANGBOSS_RANK_NOW";
    MessageDef.GANGBOSS_UPDATE_HP = "GANGBOSS_UPDATE_HP";
    MessageDef.GANGBOSS_BOX = "GANGBOSS_BOX";
    MessageDef.GANGBOSS_BOX_COLLENT = "GANGBOSS_BOX_COLLENT";
    MessageDef.GANGBOSS_UPDATE_INFO = "GANGBOSS_UPDATE_INFO";
    MessageDef.GANGBOSS_CHANGE = "GANGBOSS_CHANGE";
    //boss
    MessageDef.FIELD_BOSS_UPDATE = "FIELD_BOSS_UPDATE";
    MessageDef.PUBLIC_BOSS_UPDATE = "PUBLIC_BOSS_UPDATE";
    MessageDef.PERSON_BOSS_UPDATE = "PERSON_BOSS_UPDATE";
    MessageDef.PUBLIC_BOSS_RECORD = "PUBLIC_BOSS_RECORD";
    MessageDef.PUBLIC_BOSS_RECORD_KILL = "PUBLIC_BOSS_RECORD_KILL";
    MessageDef.VIP_BOSS_UPDATE = "VIP_BOSS_UPDATE";
    MessageDef.ALL_BOSS_NOTICE = "ALL_BOSS_NOTICE";
    MessageDef.PUBLIC_BOSS_REBORN = "PUBLIC_BOSS_REBORN";
    //帮会战
    MessageDef.GANGBATTLE_OPEN_GATEVIEW = "GANGBATTLE_OPEN_GATEVIEW";
    MessageDef.GANGBATTLE_UPDATE_BOSSINFO = "GANGBATTLE_UPDATE_BOSSINFO";
    MessageDef.GANGBATTLE_UPDATE_MYINFO = "GANGBATTLE_UPDATE_MYINFO";
    MessageDef.GANGBATTLE_ENTER_NEXT_GATE = "GANGBATTLE_ENTER_NEXT_GATE";
    MessageDef.GANGBATTLE_UPDATE_GANGRANK = "GANGBATTLE_UPDATE_GANGRANK";
    MessageDef.GANGBATTLE_UPDATE_PLAYERRANK = "GANGBATTLE_UPDATE_PLAYERRANK";
    MessageDef.GANGBATTLE_UPDATE_ALLGANGRANK = "GANGBATTLE_UPDATE_ALLGANGRANK";
    MessageDef.GANGBATTLE_UPDATE_ALLPLAYERRANK = "GANGBATTLE_UPDATE_ALLPLAYERRANK";
    MessageDef.GANGBATTLE_UPDATE_KINGINFO = "GANGBATTLE_UPDATE_KINGINFO";
    MessageDef.GANGBATTLE_UPDATE_DURATION = "GANGBATTLE_UPDATE_DURATION";
    MessageDef.GANGBATTLE_SHOW_GUARDTIP = "GANGBATTLE_SHOW_GUARDTIP";
    //缘份
    MessageDef.YUANFEN_UPDATE_LIST = "YUANFEN_UPDATE_LIST";
    MessageDef.YUANFEN_INIT = "YUANFEN_INIT";
    MessageDef.YUANFEN_ALL_NOTICE = "YUANFEN_ALL_NOTICE";
    //日常
    MessageDef.DAILY_PEACE_UPDATE = "DAILY_PEACE_UPDATE";
    MessageDef.DAILY_TEAM_UPDATE = "DAILY_TEAM_UPDATE";
    MessageDef.DAILY_ACTIVE_UPDATE = "DAILY_ACTIVE_UPDATE";
    MessageDef.DAILY_MEDAL_UPDATE = "DAILY_MEDAL_UPDATE";
    MessageDef.DAILY_TASKLIST_UPDATE = "DAILY_TASKLIST_UPDATE";
    MessageDef.DAILY_RETRIEVELIST_UPDATE = "DAILY_RETRIEVELIST_UPDATE";
    MessageDef.DAILY_REDPOINT_NOTICE = "DAILY_REDPOINT_NOTICE";
    MessageDef.DAILY_FOMALHAUT_MONSTERID = "DAILY_FOMALHAUT_MONSTERID";
    MessageDef.DAILY_UPDATE_RETREVE_VIEW = "DAILY_UPDATE_RETREVE_VIEW";
    //日常副本
    MessageDef.FB_INFO_UPDATE = "FB_INFO_UPDATE";
    //玲珑塔
    MessageDef.TA_INFO_UPDATE = "TA_INFO_UPDATE";
    //神兽活动
    MessageDef.GODPETACTIVE_UPDATE_INFO = "GODPETACTIVE_UPDATE_INFO";
    MessageDef.GODPETACTIVE_UPDATE_AWARDINFO = "GODPETACTIVE_UPDATE_AWARDINFO";
    MessageDef.GODPETACTIVE_UPDATE_LOTTERY = "GODPETACTIVE_UPDATE_LOTTERY";
    MessageDef.GODPETACTIVE_LOTTERY_NOTICE = "GODPETACTIVE_LOTTERY_NOTICE";
    //天神降临
    MessageDef.GODLOTTERY_UPDATE_INFO = "GODLOTTERY_UPDATE_INFO";
    MessageDef.GODLOTTERY_UPDATE_LOTTERY = "GODLOTTERY_UPDATE_LOTTERY";
    //竞技场
    MessageDef.ARENA_INFO_DATA = 'ARENA_INFO_DATA';
    MessageDef.ARENA_BUY_RESULT = 'ARENA_BUY_RESULT';
    MessageDef.ARENA_RANK_DATA = 'ARENA_RANK_DATA';
    //经脉
    MessageDef.JINGMAI_DATA_UPDATE = 'JINGMAI_DATA_UPDATE';
    //玄女法器
    MessageDef.HAVING_WASH_INFO = 'HAVING_WASH_INFO';
    MessageDef.HAVING_WASH_REPLACE_INFO = 'HAVING_WASH_REPLACE_INFO';
    //主线任务
    MessageDef.UPDATE_MAIN_TASK = 'UPDATE_MAIN_TASK';
    //聊天收缩
    MessageDef.UPDATE_CHAT_ZOOM = 'UPDATE_CHAT_ZOOM';
    // 天神
    MessageDef.TIANSHEN_ACTIVE = "TIANSHEN_ACTIVE";
    MessageDef.TIANSHEN_UPDATE_INFO = "TIANSHEN_UPDATE_INFO";
    MessageDef.TIANSHEN_BATTLE = "TIANSHEN_BATTLE";
    MessageDef.TIANSHEN_UPDATE_EXP = "TIANSHEN_UPDATE_EXP";
    MessageDef.TIANSHEN_UPDATE_DRUG = "TIANSHEN_UPDATE_DRUG";
    MessageDef.TIANSHEN_UPDATE_BREACH = "TIANSHEN_UPDATE_BREACH";
    MessageDef.TIANSHEN_BAOQI_UPDATE_INFO = "TIANSHEN_BAOQI_UPDATE_INFO";
    MessageDef.TIANSHEN_BAOQI_UPDATE_EXP = "TIANSHEN_BAOQI_UPDATE_EXP";
    MessageDef.BAG_TIANSHEN_ATTR_ITEM = "BAG_TIANSHEN_ATTR_ITEM";
    MessageDef.BAG_TIANSHEN_ACT_ITEM = "BAG_TIANSHEN_ACT_ITEM";
    MessageDef.BAG_TIANSHEN_LEVEL_ITEM = "BAG_TIANSHEN_LEVEL_ITEM";
    MessageDef.RP_BAG_TIANSHEN_ACT_ITEM = "RP_BAG_TIANSHEN_ACT_ITEM";
    MessageDef.RP_TIANSHEN = "RP_TIANSHEN";
    //玩家详情
    MessageDef.PALYER_INFO = 'PALYER_INFO';
    MessageDef.PLAYER_PREVITE_CHAT = 'PLAYER_PREVITE_CHAT';
    MessageDef.PLAYER_PREVITE_CLOSE = 'PLAYER_PREVITE_CLOSE';
    MessageDef.PLAYER_PREVITE_CHAT_SUCCESS = 'PLAYER_PREVITE_CHAT_SUCCESS';
    MessageDef.PLAYER_CHECK_ONLINE = 'PLAYER_CHECK_ONLINE';
    MessageDef.PLAYER_NEWMSG_SHOW_RED_POINT = 'PLAYER_NEWMSG_SHOW_RED_POINT';
    MessageDef.PLAYER_COPY_NAME = 'PLAYER_COPY_NAME';
    MessageDef.PLAYER_CHANGE_NAME = "PLAYER_CHANGE_NAME";
    MessageDef.PLAYER_CHANGE_SYSTEM_SETTING = "PLAYER_CHANGE_SYSTEM_SETTING";
    MessageDef.PLAYER_VIEW_ONCITYMAP = "PLAYER_VIEW_ONCITYMAP";
    //迷你聊天框(缩小)
    MessageDef.MINICHATSCAL = "MINICHATSCAL";
    MessageDef.MINICHATSCAL_ALL = "MINICHATSCAL_ALL";
    //排行榜
    MessageDef.UPDATE_PAIHANGBANG_DATA = 'UPDATE_PAIHANGBANG_DATA';
    MessageDef.PHB_REPOINT_UPDATE = 'PHB_REPOINT_UPDATE';
    //队伍
    MessageDef.UPDATE_TEAM_MYINFO = 'UPDATE_TEAM_MYINFO';
    MessageDef.UPDATE_TEAM_LIST = 'UPDATE_TEAM_LIST';
    MessageDef.TEAM_FUBEN_INFO = "TEAM_FUBEN_INFO";
    MessageDef.TEAM_UPDATE_LEAVE = "TEAM_UPDATE_LEAVE";
    MessageDef.TEAM_UPDATE_MAP_LIST = "TEAM_UPDATE_MAP_LIST";
    // 主界面显示队伍信息
    MessageDef.UPDATE_TEAM_MAIN_INFO = 'UPDATE_TEAM_MAIN_INFO';
    // 全民boss
    MessageDef.PUBLIC_BOSS_UPDATE_ATK = "PUBLIC_BOSS_UPDATE_ATK";
    // 活动大厅
    MessageDef.ACTIVITY_LIST_INFO = "ACTIVITY_LIST_INFO";
    MessageDef.ACTIVITY_OPEN_UPDATE = "ACTIVITY_OPEN_UPDATE";
    // 矿山争夺
    MessageDef.GANGMINE_UPDATE_INFO = "GANGMINE_UPDATE_INFO";
    MessageDef.GANGMINE_RANK_INFO = "GANGMINE_RANK_INFO";
    MessageDef.PAGE_BUTTON_UPDATE = "PAGE_BUTTON_UPDATE";
    // 仙道会
    MessageDef.RP_XIANDAO = "RP_XIANDAO";
    MessageDef.XIANDAO_UPDATE = "XIANDAO_UPDATE";
    MessageDef.XIANDAO_MAP_UPDATE = "XIANDAO_MAP_UPDATE";
    //跨服争霸
    MessageDef.MINI_MAP_UPDATE_LIST = "MINI_MAP_UPDATE_LIST";
    MessageDef.KFZB_ONECITY_INFO = "KFZB_ONECITY_INFO";
    MessageDef.KFZB_MAINJNFEN_INFO = "KFZB_MAINJNFEN_INFO";
    MessageDef.FUHUO_UPDATE_INFO = "FUHUO_UPDATE_INFO";
    MessageDef.JF_UPDATE_INFO = "JF_UPDATE_INFO";
    MessageDef.MOVE_UPDATE_INFO = "MOVE_UPDATE_INFO";
    MessageDef.CITYTYPE_UPDATE_INFO = "CITYTYPE_UPDATE_INFO";
    MessageDef.UP_GROUP_SHOW = "UP_GROUP_SHOW";
    MessageDef.SHOUCITY_UPDATE_INFO = "SHOUCITY_UPDATE_INFO";
    MessageDef.SEND_CITY = "SEND_CITY";
    //九重天
    MessageDef.CLOUD_NINE_RANK = "CLOUD_NINE_RANK";
    MessageDef.CLOUD_NINE_GIFT_REFRES = "CLOUD_NINE_GIFT_REFRES";
    MessageDef.CLOUD_NINE_SCENE_INIT = "CLOUD_NINE_SCENE_INIT";
    //八十一难
    MessageDef.TSUMKO_UPDATE_LIST = "TSUMKO_UPDATE_LIST";
    MessageDef.TSUMKO_RECORD = "TSUMKO_RECORD";
    MessageDef.TSUMKO_UPDATE_CHECKPOINTLIST = "TSUMKO_UPDATE_CHECKPOINTLIST";
    MessageDef.ClOSETSUMKOBASEBAGITEMPLANEL = "ClOSETSUMKOBASEBAGITEMPLANEL";
    MessageDef.TSUMKO_INFO = "TSUMKO_INFO";
    MessageDef.CHOICECHECKPOINT = "CHOICECHECKPOINT";
    // 跨服boss
    MessageDef.KF_BOSS_DEAD = "KF_BOSS_DEAD";
    MessageDef.KF_BOSS_RANK_NOW = "KF_BOSS_RANK_NOW";
    MessageDef.KF_BOSS_UPDATE_HP = "KF_BOSS_UPDATE_HP";
    MessageDef.KF_BOSS_BOX = "KF_BOSS_BOX";
    MessageDef.KF_BOSS_BOX_COLLENT = "KF_BOSS_BOX_COLLENT";
    MessageDef.KF_BOSS_UPDATE_INFO = "KF_BOSS_UPDATE_INFO";
    //好友
    MessageDef.FRIEND_DATA_REFRESH = "FRIEND_DATA_REFRESH";
    MessageDef.FRIEND_RED_POINT_CHANGE = "FRIEND_RED_POINT_CHANGE";
    //银两兑换
    MessageDef.EXCHANGE_COUNT = "EXCHANGE_COUNT";
    //婚姻
    MessageDef.YING_YUAN_HEAD = "YING_YUAN_HEAD";
    MessageDef.IS_MARRY_INFO = "IS_MARRY_INFO";
    MessageDef.QIU_MARRY_INFO = "QIU_MARRY_INFO";
    MessageDef.INVITATION_INFO = "INVITATION_INFO";
    MessageDef.FLOWER_INFO = "FLOWER_INFO";
    MessageDef.MARRY_LOVE_INFO = "MARRY_LOVE_INFO";
    //房屋
    MessageDef.HOUSE_UPDATE_INFO = "HOUSE_UPDATE_INFO";
    MessageDef.HOUSE_SHARED_NOTICE = "HOUSE_SHARED_NOTICE";
    MessageDef.HOUSE_UPDATE_SINGLE = "HOUSE_UPDATE_SINGLE";
    //福利
    MessageDef.FULI_GET_GIFT_SUCCEED = "FULI_GET_GIFT_SUCCEED";
    MessageDef.FULI_GET_REDEEMCODE = "FULI_GET_REDEEMCODE";
    MessageDef.FULI_GET_RECEIVEITEMSIGN = "FULI_GET_RECEIVEITEMSIGN";
    MessageDef.FULI_GET_RECEIVEBRIBERY = "FULI_GET_RECEIVEBRIBERY";
    MessageDef.FULI_GET_HAVEBRIBERY = "FULI_GET_HAVEBRIBERY";
    MessageDef.FULI_MONTH_WEEK_CHANGE = "FULI_MONTH_WEEK_CHANGE";
    MessageDef.FULI_GIVEGOLD_INFO = "FULI_GIVEGOLD_INFO";
    MessageDef.FULI_GOLDTREE_INFO = "FULI_GOLDTREE_INFO";
    MessageDef.RP_SIGN_UPDATE = "RP_SIGN_UPDATE";
    // 剧情
    MessageDef.PLOT_PLAY_END = "PLOT_PLAY_END";
    //充值
    MessageDef.RECHARGE_UPDATE = "RECHARGE_UPDATE";
    MessageDef.RECHARGE_FIRST_UPDATE = "RECHARGE_FIRST_UPDATE";
    MessageDef.RECHARGE_DAILY_UPDATE = "RECHARGE_DAILY_UPDATE";
    MessageDef.PLAYER_RECHARGE_UPDATE = "PLAYER_RECHARGE_UPDATE";
    /**运营 开服 活动 */
    MessageDef.ACTIVITY_JIJIE_CHANGE_TITILE = "ACTIVITY_JIJIE_CHANGE_TITILE";
    MessageDef.ACTIVITY_INFO = "ACTIVITY_INFO";
    MessageDef.ACTIVITY_UPDATE = "ACTIVITY_UPDATE";
    MessageDef.ACTIVITY_DABIAO_UPDATE = "ACTIVITY_DABIAO_UPDATE";
    MessageDef.ACTIVITY_IS_GET_AWARDS = "ACTIVITY_IS_GET_AWARDS";
    MessageDef.ACTIVITY_RACE_HISTORY = "ACTIVITY_RACE_HISTORY";
    MessageDef.ACTIVITY_ADVANCED_INFO = "ACTIVITY_ADVANCED_INFO";
    MessageDef.ACTIVITY_ADVANCED_RANK = "ACTIVITY_ADVANCED_RANK";
    MessageDef.ACTIVITY_TARGET_ShOP_LOOK = "ACTIVITY_TARGET_ShOP_LOOK";
    MessageDef.ACTIVITY_ADVANCED_ICON_SHOW = "ACTIVITY_ADVANCED_ICON_SHOW";
    MessageDef.ACTIVITY_ADVANCED_ZHUANG_PAN = "ACTIVITY_ADVANCED_ZHUANG_PAN";
    MessageDef.ACTIVITY_ADVANCED_ZHUANG_PAN_RULE = "ACTIVITY_ADVANCED_ZHUANG_PAN_RULE";
    //拍卖
    MessageDef.AUCTION_ITEM_PRICE_UPDATE = "AUCTION_ITEM_PRICE_UPDATE";
    MessageDef.AUCTION_LIST_UPDATE = "AUCTION_LIST_UPDATE";
    MessageDef.AUCTION_RECORD_UPDATE = "AUCTION_RECORD_UPDATE";
    MessageDef.AUCTION_REDPOINT_UPDATE = "AUCTION_REDPOINT_UPDATE";
    //预告
    MessageDef.SHOWFATEEFF = "SHOWFATEEFF";
    //登陆活动
    MessageDef.LOGINDAYGIF = "LOGINDAYGIF";
    MessageDef.LADDER_PLAYER_BACK = "LADDER_PLAYER_BACK";
    MessageDef.LADDER_PRE_WEEK_REWARD = "LADDER_PRE_WEEK_REWARD";
    MessageDef.LADDER_UPWEEK_RANK_UPDATE = "LADDER_UPWEEK_RANK_UPDATE";
    MessageDef.LADDER_WINNER = "LADDER_WINNER";
    MessageDef.LADDER_CHANGE = "LADDER_CHANGE";
    //图腾
    MessageDef.TOTEMS_UPDATEACTIVATION = "TOTEMS_UPDATEACTIVATION";
    MessageDef.TOTEMS_INFO = "TOTEMS_INFO";
    MessageDef.TOTEMS_REDPOINT_NOTICE = "TOTEMS_REDPOINT_NOTICE";
    //升級途径-我要变强
    MessageDef.UPLVWAY_ACQUIRE_ITEM = "UPLVWAY_ACQUIRE_ITEM";
    MessageDef.UPLVWAY_CHANGE_SCORE = "UPLVWAY_CHANGE_SCORE";
    MessageDef.UPLVWAY_REDPOINT_NOTICE = "UPLVWAY_REDPOINT_NOTICE";
    // 摇钱树
    MessageDef.MONEY_INFO_CHANGE = "MONEY_INFO_CHANGE";
    MessageDef.MONEY_RECHARGE_GIFT_CHANGE = "MONEY_RECHARGE_GIFT_CHANGE";
    //阵位预告
    MessageDef.POSITION_AWARD_CHANGE = "POSITION_AWARD_CHANGE";
    MessageDef.POSITION_STATE_CHANGE = "POSITION_STATE_CHANGE";
    return MessageDef;
}());
__reflect(MessageDef.prototype, "MessageDef");
//# sourceMappingURL=MessageDef.js.map